### ISSUE TITLE
Geoimage.at MaxRes is erroring

### ISSUE THREAD

**Issue by MakiWolf** [osmlab/editor-layer-index#1000]
Geoimage.at MaxRes is erroring in the App Vespucci and in the ID Editor, but in JOSM it works. I have reported it there before, but I should report it here.
[https://github.com/MarcusWolschon/osmeditor4android/issues/1298](https://github.com/MarcusWolschon/osmeditor4android/issues/1298)
[https://github.com/openstreetmap/iD/issues/8218](https://github.com/openstreetmap/iD/issues/8218)

**Comment by rbuffat** [comment]
@MakiWolf Thanks for reporting. It looks as the domain of the server has changed. I created a pull request to fix the url: https://github.com/osmlab/editor-layer-index/pull/1001

Also, this is the 1000th issue! 🎉🥳

**Comment by rbuffat** [comment]
Solved with https://github.com/osmlab/editor-layer-index/pull/1001
