### ISSUE TITLE
Invalid WMS projections

### ISSUE THREAD

**Issue by don-vip** [osmlab/editor-layer-index#1020]
## URL of the imagery
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/ee/EstoniaBasemap-Maaamet.geojson

As you surely know, we have an [ELI-JOSM comparison](https://josm.openstreetmap.de/wiki/ImageryCompare) script.
The recent WMS projections rework here raised a lot of projection differences to check. So many that @Klumbumbus and I lost motivation to check that immediately... Yesterday I began to [add EPSG:3301 projection for Estonian entries](https://josm.openstreetmap.de/wiki/Maps/Estonia?action=diff&version=28).

It [resulted in an error](https://josm.openstreetmap.de/jenkins/job/JOSM-Imagery-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.imagery/ImageryPreferenceTestIT/EE_Maaamet_Estonia_Basemap/) for all three related layers in our integration tests:

https://kaart.maaamet.ee/wms/alus-geo?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&Layers=pohi_vr2&SRS=EPSG:3301&WIDTH=512&HEIGHT=512&BBOX=352833.7397322,-13251583.0013191,20390342.0825215,6785925.3414702
`msWMSLoadGetMapParams(): WMS server error. Invalid SRS given : SRS must be valid for all requested layers.`

I checked manually: EPSG:3301 is advertised in WMS capabilities, but it doesn't work (tested both in WMS 1.1.1 and 1.3.0).

I don't understand how the [ELI watchdog](https://rbuffat.github.io/eli_watchdog/) considers this imagery as working:

![image](https://user-images.githubusercontent.com/596867/104183875-ea2e9d00-5412-11eb-8bbd-98feee89f8d2.png)

Does the watchdog make actual WMS GetMap calls?

**Comment by rbuffat** [comment]
It seems as the GetCapabilities of this WMS server advertise EPSG:3301 but does not support this projection.

The WMS sync bot as well as the watchdog both assume that the information of the GetCapabilities request is correct.   

The WMS sync bot currently does the following:
* Upgrade the WMS URL for the newest support WMS version the server understands if the image hash of the old WMS version is the same as for the new WMS version for meaningful image hashes. 
* Updates the available_projections from the GetCapabilities request. The projections advertised by the WMS server are filtered by deprecated projections (based on the pyproj library) and projections that are not used within the bounding box region of the geometry of a source. 
* The bot currently runs once a week.

See also the relevant code of the bot: https://github.com/osmlab/editor-layer-index/blob/gh-pages/scripts/sync_wms.py#L585-L744

Both the wms_sync bot as well as the watchdog use the WMS GetCapabilities information as this is a much cheaper operation than a GetMap request (Unlike a tms a WMS server generates with a GetMap request an image on the fly).  Especially for often running scripts, I think it is valuable to be conservative about the resources that are used. However, if there is a significant number of misconfigured/not behaving as specified WMS servers then it might be a better option to check every projection with a GetMap request.

**Comment by don-vip** [comment]
> The WMS sync bot as well as the watchdog both assume that the information of the GetCapabilities request is correct.

This is a big problem, as it does not work like this in the real world. Many servers are badly configured and support more projections than advertised, or do not support said projections.

> Both the wms_sync bot as well as the watchdog use the WMS GetCapabilities information as this is a much cheaper operation than a GetMap request (Unlike a tms a WMS server generates with a GetMap request an image on the fly). Especially for often running scripts, I think it is valuable to be conservative about the resources that are used. However, if there is a significant number of misconfigured/not behaving as specified WMS servers then it might be a better option to check every projection with a GetMap request.

You cannot rely on GetCapabilities only. One optimization could be to make more frequent calls to GetCapabilities requests than GetMap calls, but you cannot skip them entirely, especially when you create pull requests behind.

**Comment by rbuffat** [comment]
> This is a big problem, as it does not work like this in the real world. Many servers are badly configured and support more projections than advertised, or do not support said projections.

Do you have an estimate about how many WMS server advertise a projection and do not actually support it?
Checking for each projection if a GetMap request returns an image should be fairly easy to implement.

**Comment by don-vip** [comment]
> Do you have an estimate about how many WMS server advertise a projection and do not actually support it?

Difficult to say, but it's very frequent. I would not be surprised to see 20/25% of servers not behaving exactly as the exposed capabilities.

> Checking for each projection if a GetMap request returns an image should be fairly easy to implement.

Yes, that's what we do. We just don't check all projections as we assume the projections listed on the wiki have been manually checked by us or the community.

**Comment by rbuffat** [comment]
With https://github.com/osmlab/editor-layer-index/pull/1021 each projection is checked if a GetMap request returns an image. When I run the updated script locally the following sources were modified: 

```
        modified:   sources/europe/ee/EstoniaBasemap-Maaamet.geojson
        modified:   sources/europe/ee/EstoniaCIR-Maaamet.geojson
        modified:   sources/europe/ee/EstoniaCadastre(Maaamet).geojson
        modified:   sources/europe/it/PCN2012-Italy.geojson
        modified:   sources/europe/no/KartverketAviationObstructionsoverlay.geojson
        modified:   sources/europe/no/KartverketContourLinesoverlay.geojson
        modified:   sources/europe/se/SollentunaOrthophoto.geojson
        modified:   sources/north-america/ca/Canvec-French.geojson
        modified:   sources/north-america/ca/Canvec.geojson
        modified:   sources/north-america/us/USDA-NAIP.geojson
```

@don-vip If you find more issues I would be happy to hear them.

**Comment by rbuffat** [comment]
> Yes, that's what we do. We just don't check all projections as we assume the projections listed on the wiki have been manually checked by us or the community.

The purpose of the script is to synchronize the sources with the capabilities of the WMS server. If only projections are checked that are manually added then newly added projections are never detected.

**Comment by rbuffat** [comment]
Resolved for now with https://github.com/osmlab/editor-layer-index/pull/1021,  respectively https://github.com/osmlab/editor-layer-index/pull/1025

**Comment by don-vip** [comment]
Sorry it took me dome days to check. There are still some issues. 

I checked the first difference reported by our comparison script:
`* Projections differ ('EPSG:2056 EPSG:21780 EPSG:21781 EPSG:3857 EPSG:4258 EPSG:4326' != 'EPSG:2056 EPSG:21780 EPSG:21781 EPSG:21782 EPSG:3857 EPSG:4258 EPSG:4326'): [CH] Kanton Zurich, Surface Hillshade 2017 [OGDLidarZH-DOM-2017]`
[Capabilities](https://wms.zh.ch/OGDLidarZH?VERSION=1.3.0&SERVICE=WMS&REQUEST=GetCapabilities) advertise **EPSG:21782**. [JOSM lists this projection](https://josm.openstreetmap.de/wiki/Maps/Switzerland#KantonZurichSurfaceHillshade2017), but [ELI doesn't](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/ch/Kanton_Zurich_dom_hillshade_2017_wms.geojson?short_path=ee44c35#L8).

I checked and [it works](https://wms.zh.ch/OGDLidarZH?LAYERS=dom2017_relief&STYLES=&FORMAT=image/jpeg&CRS=EPSG:21782&WIDTH=512&HEIGHT=512&BBOX=84539.2889789,52629.5296424,162810.8059430,130901.0466064&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap):

```
2021-01-21 22:21:25.219 INFO: GET https://wms.zh.ch/OGDLidarZH?LAYERS=dom2017_relief&STYLES=&FORMAT=image/jpeg&CRS=EPSG:21780&WIDTH=512&HEIGHT=512&BBOX=84539.2889789,52629.5296424,162810.8059430,130901.0466064&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap -> HTTP/1.1 200 (84 ms; 12.5 kB)
2021-01-21 22:21:25.426 INFO: GET https://wms.zh.ch/OGDLidarZH?LAYERS=dom2017_relief&STYLES=&FORMAT=image/jpeg&CRS=EPSG:21781&WIDTH=512&HEIGHT=512&BBOX=621113.3217849,231996.8614134,699384.8387489,310268.3783774&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap -> HTTP/1.1 200 (85 ms; 18.3 kB)
2021-01-21 22:21:25.617 INFO: GET https://wms.zh.ch/OGDLidarZH?LAYERS=dom2017_relief&STYLES=&FORMAT=image/jpeg&CRS=EPSG:21782&WIDTH=512&HEIGHT=512&BBOX=84539.2889789,52629.5296424,162810.8059430,130901.0466064&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap -> HTTP/1.1 200 (81 ms; 12.5 kB)
```

Shouldn't it be have been added by your WMS sync bot?

**Comment by rbuffat** [comment]
The WMS sync bot filters out deprecated projections (except if EPSG:3857 is not present it keeps one alias) and projections that have an area of use outside of the bounding box of the source geometry.
 
The source you mention is for the Canton of Zurich in Switzerland. EPSG:21782 is for the country of Lichtenstein and its area of use ([WGS84 Bounds: 9.4800, 47.0900, 9.6400, 47.3000](https://spatialreference.org/ref/epsg/21782/)) does not overlap with the source geometry.

**Comment by don-vip** [comment]
OK thank you! Indeed this is a test I didn't think of, I will add it as well. Closing the issue for now, will reopen if I find something else.
