### ISSUE TITLE
Orthophot Imagery layer Uruguay

### ISSUE THREAD

**Issue by c-leitner** [osmlab/editor-layer-index#1032]
## URL of the imagery
https://mapas.ide.uy/geoserver-raster/ortofotos/ows?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=ORTOFOTOS_2019&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

## Two letter country code
UY

## Desired layer name
Ortofotos 2018-2019 (IDEuy)

## License
OGL
https://www.gub.uy/agencia-gobierno-electronico-sociedad-informacion-conocimiento/sites/agencia-gobierno-electronico-sociedad-informacion-conocimiento/files/documentos/publicaciones/licencia_de_datos_abiertos_0.pdf

## Is the license compatible with OSM?
Yes.

## Attribution (text, URL, required?)
Yes following information is required:
[Infraestructura de Datos Espaciales, Licencia de Datos Abiertos – Uruguay, Ortofotos 2018-2019 (IDEuy)](https://www.gub.uy/infraestructura-datos-espaciales/)

## Privacy policy (URL)
https://www.gub.uy/infraestructura-datos-espaciales/politica-de-privacidad

## Icon
[https://www.gub.uy/infraestructura-datos-espaciales/sites/infraestructura-datos-espaciales/files/inline-images/ideuy_compacto_rgb_473px_0.png](https://www.gub.uy/infraestructura-datos-espaciales/sites/infraestructura-datos-espaciales/files/inline-images/ideuy_compacto_rgb_473px_0.png)

## Bounding polygon
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-53.39417,-33.73912],[-53.36321,-33.73654],[-52.7723,-34.11526],[-54.84598,-35.43046],[-57.8368,-34.67596],[-57.94731,-34.50839],[-58.10591,-34.33987],[-58.32661,-34.1545],[-58.35468,-34.04255],[-58.43356,-33.91484],[-58.48687,-33.57513],[-58.44819,-33.34742],[-58.38993,-33.28049],[-58.38202,-33.12817],[-58.32557,-33.09757],[-58.16997,-33.09102],[-58.15416,-33.05485],[-58.09264,-32.99502],[-58.13014,-32.9048],[-58.17173,-32.57208],[-58.20964,-32.49023],[-58.19965,-32.38414],[-58.11897,-32.31946],[-58.10797,-32.28872],[-58.10976,-32.25882],[-58.19279,-32.16252],[-58.15555,-31.99616],[-58.21151,-31.88502],[-58.16655,-31.83213],[-58.07958,-31.80889],[-58.05117,-31.753],[-57.99045,-31.58082],[-58.01563,-31.53429],[-58.08248,-31.49754],[-58.0893,-31.45387],[-57.98953,-31.3845],[-58.00086,-31.36114],[-57.99013,-31.31653],[-57.91549,-31.21258],[-57.92309,-31.12277],[-57.88265,-31.07346],[-57.87449,-31.03768],[-57.91342,-30.95708],[-57.91249,-30.92896],[-57.88545,-30.90965],[-57.81848,-30.91097],[-57.81523,-30.70483],[-57.84823,-30.66661],[-57.85598,-30.62477],[-57.89666,-30.58898],[-57.8969,-30.51973],[-57.848,-30.46047],[-57.65198,-30.33447],[-57.62623,-30.2508],[-57.65546,-30.18887],[-57.62208,-30.17726],[-57.55556,-30.20287],[-57.54561,-30.23006],[-57.55656,-30.25322],[-57.52148,-30.27576],[-57.46416,-30.25602],[-57.41239,-30.26915],[-57.37351,-30.26382],[-57.3491,-30.26973],[-57.31343,-30.24786],[-57.26076,-30.25694],[-57.17194,-30.23258],[-57.1769,-30.19318],[-57.10241,-30.08319],[-56.86723,-30.06385],[-56.64675,-30.19962],[-56.48435,-30.33677],[-56.48647,-30.38426],[-56.45595,-30.37685],[-56.43652,-30.42235],[-56.41135,-30.42169],[-56.38793,-30.4441],[-55.7272,-30.93064],[-55.66499,-30.85799],[-55.64115,-30.8379],[-55.57395,-30.82386],[-55.53884,-30.88318],[-55.48042,-30.9196],[-55.03716,-31.26212],[-54.99902,-31.25958],[-54.7533,-31.41455],[-54.66672,-31.44411],[-54.58167,-31.44799],[-54.49515,-31.5203],[-54.44391,-31.59583],[-54.44269,-31.64897],[-54.09106,-31.9203],[-54.03301,-31.88543],[-53.96594,-31.90848],[-53.95458,-31.94696],[-53.84307,-31.9933],[-53.73821,-32.07166],[-53.71537,-32.0953],[-53.4577,-32.47652],[-53.44727,-32.51761],[-53.39024,-32.57522],[-53.36665,-32.56037],[-53.28722,-32.61118],[-53.27332,-32.59512],[-53.24477,-32.59553],[-53.23283,-32.62039],[-53.18117,-32.63624],[-53.08408,-32.72221],[-53.17261,-32.823],[-53.28527,-32.90351],[-53.29632,-32.96987],[-53.46784,-33.07679],[-53.51141,-33.14506],[-53.51996,-33.20665],[-53.49112,-33.4279],[-53.52106,-33.66162],[-53.51577,-33.67975],[-53.43607,-33.68487],[-53.42085,-33.73068],[-53.39417,-33.73912]]]}}]}

**Comment by rbuffat** [comment]
From the license:

> Nota de Origen. A los efectos de utilizar los datos abiertos y metadatos abiertos en los
> términos referidos en el artículo anterior se deberá en todos los casos citar la siguiente
> información:
> - el nombre del proveedor,
> - la referencia a la "Licencia de Datos Abiertos – Uruguay".
> - la referencia al conjunto de datos que está siendo utilizado.
> Los cambios, las ediciones, los nuevos diseños o modificaciones deben ser
> mencionados en la nota de origen.

Google Translate:
> Note of Origin. In order to use open data and open metadata in the
> terms referred to in the previous article must in all cases cite the following
> information:
> - the name of the provider,
> - the reference to the "Open Data License - Uruguay".
> - the reference to the data set that is being used.
> Changes, edits, new designs or modifications must be
> mentioned in the note of origin.

Does this need a waiver for the attribution?

**Comment by rbuffat** [comment]
https://josm.openstreetmap.de/wiki/Maps/Uruguay#IDE.uyOrtophotos2019 refers to https://www.gub.uy/agencia-gobierno-electronico-sociedad-informacion-conocimiento/sites/agencia-gobierno-electronico-sociedad-informacion-conocimiento/files/documentos/publicaciones/licencia_de_datos_abiertos_0.pdf

**Comment by c-leitner** [comment]
> https://josm.openstreetmap.de/wiki/Maps/Uruguay#IDE.uyOrtophotos2019 refers to https://www.gub.uy/agencia-gobierno-electronico-sociedad-informacion-conocimiento/sites/agencia-gobierno-electronico-sociedad-informacion-conocimiento/files/documentos/publicaciones/licencia_de_datos_abiertos_0.pdf
I got the current version directly from the website:
https://www.gub.uy/agencia-gobierno-electronico-sociedad-informacion-conocimiento/comunicacion/publicaciones/licencia-datos-abiertos-uruguay-0
Could be an old Version in JOSM

**Comment by c-leitner** [comment]
> From the license:
> 
> > Nota de Origen. A los efectos de utilizar los datos abiertos y metadatos abiertos en los
> > términos referidos en el artículo anterior se deberá en todos los casos citar la siguiente
> > información:
> > 
> > * el nombre del proveedor,
> > * la referencia a la "Licencia de Datos Abiertos – Uruguay".
> > * la referencia al conjunto de datos que está siendo utilizado.
> >   Los cambios, las ediciones, los nuevos diseños o modificaciones deben ser
> >   mencionados en la nota de origen.
> 
> Google Translate:
> 
> > Note of Origin. In order to use open data and open metadata in the
> > terms referred to in the previous article must in all cases cite the following
> > information:
> > 
> > * the name of the provider,
> > * the reference to the "Open Data License - Uruguay".
> > * the reference to the data set that is being used.
> >   Changes, edits, new designs or modifications must be
> >   mentioned in the note of origin.
> 
> Does this need a waiver for the attribution?

The formulation would suggest it. I will try to contact someone at the ministry to check with them and if necessary get the waiver signed. I think they have also a motivation that OSM get better in that region since the UY Government is using OSM heavily (https://visualizador.ide.uy/ideuy/core/load_public_project/ideuy/ for example as a base layer to show all kinds of data)

**Comment by rbuffat** [comment]
@c-leitner I'm sorry for the long response time.  https://wiki.openstreetmap.org/wiki/Contributors#Uruguay includes already IDE, where it is referred to https://wiki.openstreetmap.org/wiki/File:AGESIC_confirmation_notice.png. I'm not sure what the conversation was that lead to this answer. 

From the license text it looks as the data is open data but needs to be attributed. The crucial point is if they are OK with the way that OSM attributes sources using the Contributors wiki page.

**Comment by c-leitner** [comment]
I could ask Jorge (who sent the email) if he could share the conversation history to verify that this way of attributing is OK for them. I could also ask again at agesic.

**Comment by rbuffat** [comment]
@c-leitner That would be great if you could contact Jorge and ask if they were aware of how OSM attributes data and if they consent to it.

Also, there seems to be a stall PR for maybe the same dataset: https://github.com/osmlab/editor-layer-index/pull/719

**Comment by c-leitner** [comment]
OK I am going to do that. #719 is the same dataset (I think some tests are failing). I will include all the missing information from there into my PL request so there is a PL without issues.

**Comment by cicku** [comment]
@c-leitner updates?

**Comment by matheusgomesms** [comment]
I contacted Jorge and he sent me the original e-mail. I've updated the page and added English transcript and translation: 
https://wiki.openstreetmap.org/wiki/File:AGESIC_confirmation_notice.png

Looks good to me, can I explore further #719?

**Comment by matheusgomesms** [comment]
I've added and updated some properties that were missing or outdated. All checks passed. Tested in iD the URL and no problem. For me, looks good to be merged, but I'll wait a couple of days to wait someone else to chime in. Please check #719.

**Comment by matheusgomesms** [comment]
PS.: just to add further information. Last year, the Uruguayan statistical body (INE) contact me to help them input their data directly on OSM. They were doing their census, and used OSM for routing, but had internal information to improve OSM road data. They are pretty aware about OSM, and even gave another full INE->OSM explicit permission: https://wiki.openstreetmap.org/wiki/File:AutorizacionINECensoUy.pdf

Finally, AGESIC and INE are correlated.

**Comment by matheusgomesms** [comment]
#719
