### ISSUE TITLE
Rhode Island 2019 Spring Aerial Imagery

### ISSUE THREAD

**Issue by ZeLonewolf** [osmlab/editor-layer-index#1035]
When **requesting the addition of an imagery layer**, please provide the following information. Otherwise, delete the text and type your issue.

## URL of the imagery
https://maps.edc.uri.edu/rigis/services/IMG/RI_201904_RGB_3in_web/ImageServer/WMSServer?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

## Two letter country code
US

## Desired layer name
Rhode Island Spring 2019 Aerial Imagery

## License
~~CC BY 4.0~~ Released without license per state authorities

## Is the license compatible with OSM?
See: https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data
This layer automatically loads in the layer list in JOSM.

## Attribution (text, URL, required?)
This dataset is provided 'as is.’ The producer(s) of this dataset, contributors to this dataset, the Rhode Island Geographic Information System (RIGIS) consortium, the State of Rhode Island, and the University of Rhode Island do not make any warranties of any kind for this  dataset, and are not liable for any loss or damage however and whenever caused by any use of this dataset.  Please acknowledge both RIGIS and the primary producer(s) of this dataset in any derived products.  Versions of the RIGIS logo suitable for both printed and web-based products are available at https://info.rigis.org/logos/.
https://www.rigis.org/pages/2019-spring-imagery

## Privacy policy (URL)
None listed

## Icon
https://data.rigis.org/assets/img/favicon.ico

## Bounding polygon
[RI.txt](https://github.com/osmlab/editor-layer-index/files/5899046/RI.txt)

**Comment by rbuffat** [comment]
There seems to be no metadata page, but on https://www.rigis.org/ at the bottom it is linked to https://creativecommons.org/licenses/by/4.0/

@ZeLonewolf Thanks for creating this new issue.  As in https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data pointed out CC BY 4.0 requires a waiver.  Unfortunately, being included in the JOSM index does not guarantee the existence of such a waiver, as this is not checked in JOSM. Currently, I did not yet find an existing one. 

CC @Klumbumbus @don-vip @stoecker

**Comment by ZeLonewolf** [comment]
Hello, we've research this more and received clarification from the State of RI.  It turns out that all RIGIS source data is released "openly, without license", and it is only their web pages and search/sort/visualization tools from the University of RI that are licensed CC-BY.  Therefore, this layer should be good to go for the ELI.

Email is here.
https://wiki.openstreetmap.org/wiki/File:RIGIS_license_email.png

**Comment by cicku** [comment]
You can close this now.
