### ISSUE TITLE
OS OpenMap Local

### ISSUE THREAD

**Issue by TurnrDev** [osmlab/editor-layer-index#1057]
When **requesting the addition of an imagery layer**, please provide the following information. Otherwise, delete the text and type your issue.

## URL of the imagery
tms[17]:https://{switch:a,b,c}.os.openstreetmap.org/layer/gb_os_om_local_2020_04/{zoom}/{x}/{y}.png

But it looks like there's a new URL for every release. Maybe we could add each release in?
They can all be found here: https://os.openstreetmap.org/

## Two letter country code
GB

## Desired layer name
OS OpenMap Local - April 2020

## License
OGL v3 as detailed on the [wiki](https://wiki.openstreetmap.org/wiki/Ordnance_Survey_OpenData#OS_VectorMap_District)  and on the [website](https://www.ordnancesurvey.co.uk/business-government/products/open-map-local)

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
OS OpenMap Local

## Privacy policy (URL)
https://www.ordnancesurvey.co.uk/governance/policies/privacy

## Icon
https://wiki.openstreetmap.org/wiki/File:OS-SV.png

## Bounding polygon
Should be the same as OS OpenData StreetView as this is the updated version of it

**Comment by TurnrDev** [comment]
I will create a PR for this over the coming days. Possibly tonight. The plan is:

- Add an include all historical versions of OpenData StreetView and OpenMap Local

**Comment by boothym** [comment]
@TurnrDev interesting, didn't know this layer was available for use in OSM. Looks like a updated / improved version of OSSV. Has a PR been created?

**Comment by TurnrDev** [comment]
A PR hasn't - I'll make one now
