### ISSUE TITLE
Link update to Geoportal 2, Poland

### ISSUE THREAD

**Issue by maro-21** [osmlab/editor-layer-index#1060]
The main imagery for Poland, Geoportal 2, will change its URL soon:
https://www.geoportal.gov.pl/o-geoportalu/aktualnosci/-/asset_publisher/HCHq0YGNRszn/content/15-02-2021-nowe-uslugi-wms-i-wmts-dla-ortofotomapy?redirect=%2F&inheritRedirect=true

For https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson we need to change the URL to the new one. The old one is still working but soon wil be turned off.

old one: `https://mapy.geoportal.gov.pl/wss/service/img/guest/ORTO/MapServer/WMSServer`
new one: `https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/StandardResolution`

Please also add `- "i18n": true"`.

**Comment by matkoniecz** [comment]
https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md#translations (explanation of i18n)

**Comment by matkoniecz** [comment]
https://forum.openstreetmap.org/viewtopic.php?pid=819505#p819505 mentions longer link. Is the different part added automatically by iD?

**Comment by Asteliks** [comment]
The requested changes have been merged into the repository as such this issue can be closed.

**Comment by maro-21** [comment]
> https://forum.openstreetmap.org/viewtopic.php?pid=819505#p819505 mentions longer link. Is the different part added automatically by iD?

I didn't paste the whole URL, it was just the server URL without parameters.
