### ISSUE TITLE
Swisstopo data

### ISSUE THREAD

**Issue by paulw1010** [osmlab/editor-layer-index#1071]
Today the Federal Office of Topography (Swisstopo) in Switzerland released their data for open access use. ~~Many layers are now available for use in OSM~~ (**edit: discussions on use of data still ongoing**) including the national map, hi-res imagery, and hillshade. They cover both Switzerland and Liechtenstein.

## URL of the imagery
https://wms.geo.admin.ch/

## Two letter country code
CH and LI

## Desired layers

Here are some of the layers most useful for OSM. Others can be found [here](https://map.geo.admin.ch/). To make a WMS link, use the following format 

`https://wms.geo.admin.ch/?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=<YOUR LAYER HERE>&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}`

- Swisstopo national map (1:10,000) ([WMS link](https://wms.geo.admin.ch/?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=ch.swisstopo.landeskarte-farbe-10&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}))

- Swissimage (most recent) ([WMS link](https://wms.geo.admin.ch/?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=ch.swisstopo.swissimage&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}))

- SwissALTI3D Multidirectional Hillshade ([WMS link](https://wms.geo.admin.ch/?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=ch.swisstopo.swissalti3d-reliefschattierung&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}))

## License

No CC license or anything, just this disclaimer...

> The conditions of use allow free use for all purposes and oblige the user to indicate the source as “Source: Federal Office of Topography swisstopo” or “© swisstopo”.

source: https://www.swisstopo.admin.ch/en/swisstopo/free-geodata.html#ui-collapse-694

## Is the license compatible with OSM?
~~I believe so.~~ Edit: **discussion is still underway**

## Attribution (text, URL, required?)

"Source: Federal Office of Topography swisstopo" or “© swisstopo”

## Privacy policy (URL)
https://www.swisstopo.admin.ch/en/swisstopo/documents.detail.document.html/swisstopo-internet/en/documents/karto-documents/shop/App-Ds_EN.pdf.html

## Icon
[Coat of arms of Switzerland, used by swisstopo](https://commons.wikimedia.org/wiki/File:Coat_of_Arms_of_Switzerland_(Pantone).svg)

## Bounding polygon
[Switzerland+Liechtenstein border.osm.zip](https://github.com/osmlab/editor-layer-index/files/6063787/Switzerland%2BLiechtenstein.border.osm.zip)

**Comment by simonpoole** [comment]
Currently no layers or data from this release is available for use in OSM (a fact that a cursory search would have immediately turned up). As soon as we have negotiated a solution to the issues with swisstopo we can revisit this.

See further https://github.com/cividi/geohackmin/discussions/31 for a statement by swisstopo themselves that the current terms do not work for OSM.

**Comment by rbuffat** [comment]
@paulw1010 As far as I'm informed there is at the moment an ongoing discussion if the terms and conditions of the data are compatible with OSM. There is a disussion on the talk-ch mailing list: http://lists.openstreetmap.ch/pipermail/talk-ch/2021-February/010831.html
Also see https://github.com/osmlab/editor-layer-index/issues/961#issuecomment-786883390

CC @simonpoole

**Comment by paulw1010** [comment]
Thank you both for your responses. Apologies for being unaware of previous discussions on this.

**Comment by simonpoole** [comment]
@paulw1010 sorry for being a bit grumpy yesterday, but I spent a large part of the day and more back to 2020 on the topic. It is rather unsatisfactory that the issues couldn't be resolved -before- the release leading to the situation now in which we have to stop people from jumping the gun.

**Comment by simonpoole** [comment]
We can move forward with the swissimage and the hillshade layers (I have verbal agreement that the data derived from the photos isn't "geobasisdaten" and does not require further downstream attribution), the national map will have to wait (this is actually outside of our current discussions with swisstopo and has the additional complexity of being covered by normal copyright). @paulw1010 could you prepare a pull request?

**Comment by simonpoole** [comment]
IMHO this issue can be closed. In fall 2021 swisstopo modified their attribution requirements so that in principle anything that they have published as open data can be utilized in OSM, naturally the actual dataset needs to be listed on the wiki contributors page.
