### ISSUE TITLE
Make clear that "Geoportal 2: High Resolution" may contain ancient photos

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/editor-layer-index#1083]
https://github.com/openstreetmap/iD/issues/8383#issuecomment-795221136

> Basically, when there are several maps for one region the standard server (“Geoportal 2: Orthophotomap (aerial image)”) sorts the maps collected by the creation date and the high-resolution (“Geoportal 2: High Resolution Orthophotomap (aerial image)”) sorts them by the resolution.

> TLDR.: “Geoportal 2: High Resolution Orthophotomap (aerial image)” can have older maps but they are also the latest maps available in higher quality.

This info is very useful and not currently not clear at all.

So I propose to use “Geoportal 2: High Resolution Orthophotomap, may be old and outdated (aerial image)” as layer name

And rename  "Geoportal 2: Orthophotomap (aerial image)" to  "Geoportal 2: Orthophotomap (latest aerial imagery)"

**Comment by rbuffat** [comment]
@matkoniecz Would you be willing to create a PR or would you prefer if somebody else would create one?

**Comment by matkoniecz** [comment]
@rbuffat Yes, I was planning this. Though it is not high on my TODO list given large number of PRs waiting for review ( I am skipping ones with waitfor ) - see https://github.com/osmlab/editor-layer-index/pulls?q=is%3Apr+is%3Aopen+-label%3A%22waitfor+-+license+%2F+usage+permission%22+-label%3A%22waitfor+-+other%22

**Comment by rbuffat** [comment]
@matkoniecz This would be great! I would not be discouraged by this fact. Most of the PRs that get stuck are complicated with respect to the license situation. "Trivial" changes like renaming something should be mergeed a lot quicker.

**Comment by matkoniecz** [comment]
> Most of the PRs that get stuck are complicated with respect to the license situation. 

https://github.com/osmlab/editor-layer-index/pulls?q=is%3Apr+is%3Aopen+-label%3A%22waitfor+-+license+%2F+usage+permission%22+-label%3A%22waitfor+-+other%22 excludes PRs tagged with `"waitfor - license / usage permission` and `waitfor - other` labels.

**Comment by rbuffat** [comment]
Not sure what you want to say. Most of them are quite complex.
