### ISSUE TITLE
AGIS 2020 question

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#1092]
@rbuffat the 2020 AGIS imagery for the canton Aargau was released on the 10th. The entry for the 2019 imagery that is proxied by us (SOSM) actually points to a WMS server that shows the "current" imagery, so modulo stuff that is cached it is now showing the 2020 data.

As a tendency I would change the current 2019 entry on our side to actually show only 2019 data and add a 2020 entry for the new imagery as I find the "newest" imagery concept doesn't really work for us. OK with you?

**Comment by rbuffat** [comment]
@simonpoole sounds good to me!
