### ISSUE TITLE
please update the polygon for jp/JapanGSIStandardMap.geojson

### ISSUE THREAD

**Issue by mzaki-jp** [osmlab/editor-layer-index#1102]
The polygon for jp/JapanGSIStandardMap.geojson is narrower than the supported region.
Please update the polygon as same as that for jp/JapanGSIseamlessphotoImagery.geojson

**Comment by rbuffat** [comment]
@mzaki-jp Thanks for this input. https://github.com/osmlab/editor-layer-index/pull/1104 replaced the geometry of JapanGSIStandardMap.geojson with the one of JapanGSIseamlessphotoImagery.geojson.
