### ISSUE TITLE
Virginia Imagery layer is down

### ISSUE THREAD

**Issue by cicku** [osmlab/editor-layer-index#1112]
![image](https://user-images.githubusercontent.com/686438/113495140-41e21f00-94bd-11eb-8dbb-c76e8c18d94a.png)

**Comment by rbuffat** [comment]
@cicku 
The source was updated 29 days ago: https://github.com/osmlab/editor-layer-index/pull/1076
It looks as iD still uses the old URL. Typically iD only updates the imagery with a new release.

**Comment by cicku** [comment]
Ok let me wait for another 3 months to use that layer.

I'm fine with that.

**Comment by rbuffat** [comment]
@cicku I also find this frustrating. I don't see a reason why iD could not be redeployed with an updated ELI every few weeks. But this is up to the people that manage the deployment of iD and I don't know who exactly this is. Maybe there are good reasons for this that I'm not aware of.

@grischard maybe you know more about this?

Meanwhile, it is quite easy to get a local version of iD running on Unix based systems when you have npm installed:

```
rm -rf node_modules/editor-layer-index/
cp -r up/to/date/editor-layer-index/ node_modules/
npm install
npm run imagery
npm run all
npm start
```
