### ISSUE TITLE
mapproxy.openstreetmap.se not reachable

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1172]
It looks as openstreetmap.se is not reachable for more than a year ([Archive.org has the last entry from April 7th 2020](https://web.archive.org/web/2020*/http://openstreetmap.se)).

There are currently 3 sources pointing to this server: https://github.com/osmlab/editor-layer-index/search?q=mapproxy.openstreetmap.se

Does somebody know if this server will come back from the dead eventually or has contact with the people that were operating openstreetmap.se?

@grischard @NKAmapper @don-vip

**Comment by NKAmapper** [comment]
https://github.com/karlwettin/carto-style-hydda/issues/3

@karlwettin

**Comment by rbuffat** [comment]
@grischard @simonpoole @cquest 
Is there some OSM infrastructure available to host imagery specific for OSM mapping/purposes?  I assume not all local OSM communities have the resources to host imagery on their own. 

That said, I also do not know if there is still a demand for these datasets. At least for Helsingborg, there seems to be newer data available in public domain: https://helsingborg.opendatasoft.com/explore/dataset/flygbilder/information/

**Comment by simonpoole** [comment]
SOSM has plenty of resources for such things and continues to operate a mapproxy instance.

But I suppose we really need some feedback from the SE community if the layers are/were really useful.

**Comment by grischard** [comment]
Yes there's a server to host imagery directly. A shared mapproxy would be possible too, but no one has ever volunteered the time to set it up.

**Comment by rbuffat** [comment]
Closing this issue as there seems to be no interest.
