### ISSUE TITLE
[Watchdog] Imagery "South Tyrol Topomap": sources/europe/it/SouthTyrolTopomap.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1179]
Watchdog failed for 5 consecutive days for:
"South Tyrol Topomap" -> [sources/europe/it/SouthTyrolTopomap.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/it/SouthTyrolTopomap.geojson)

Reason:
Error: No zoom level reachable. (Tested: 0,1,2,3,17,18,19,20) Tiles might not be present at tested location: 11.22990796612587,46.655735

CC contributors to this imagery:
@Klumbumbus, @rbuffat, @iandees, @Marc-marc-marc, @tyrasd, @grischard

**Comment by tyrasd** [comment]
works for me.

[![a working tile](https://geoservices.buergernetz.bz.it/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=P_BZ_BASEMAP_TOPO&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&TILEMATRIX=GoogleMapsCompatible%3A17&TILEROW=46284&TILECOL=69624&FORMAT=image%2Fjpeg&foo={width})](https://geoservices.buergernetz.bz.it/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=P_BZ_BASEMAP_TOPO&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&TILEMATRIX=GoogleMapsCompatible%3A17&TILEROW=46284&TILECOL=69624&FORMAT=image%2Fjpeg&foo={width})

**Comment by tyrasd** [comment]
@rbuffat it would be nice to get more debug output from the watchdog. e.g. what tiles/requests it actually tried, what error code the server returned, etc.

**Comment by tyrasd** [comment]
(closing for now)
