### ISSUE TITLE
Add CyclOSM layer

### ISSUE THREAD

**Issue by LySioS** [osmlab/editor-layer-index#1181]
Hi everyone,
The requested feature is in the title.

Excuse me if this issue report is not good enough, this is my first time.

Thanks for your work.
Lysios

## URL of the imagery
I think that's the one > `https://{s}.tile-cyclosm.openstreetmap.fr/[cyclosm|cyclosm-lite]/{z}/{x}/{y}.png`

## Two letter country code
world

## Desired layer name
CyclOSM

## Licenses
[https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/LICENSE.md](https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/LICENSE.md)

## Is the license compatible with OSM?
(required)

## Attribution (text, URL, required?)
I do not know

## Privacy policy (URL)
I do not know

## Icon
[https://raw.githubusercontent.com/cyclosm/cyclosm-website/master/images/logo.png](https://raw.githubusercontent.com/cyclosm/cyclosm-website/master/images/logo.png)

## Bounding polygon
(if possible, provide a bounding polygon where the imagery is valid, e.g. as a GeoJSON or OSM file.)<br/>
See FAQ at https://github.com/osmlab/editor-layer-index/blob/gh-pages/FAQ.md#how-can-i-draw-a-bounding-polygon) for information about how to draw a bounding polygon.

**Comment by Asteliks** [comment]
is this done?
