### ISSUE TITLE
[Watchdog] Imagery "BD Carthage": sources/europe/fr/BDCarthage.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1186]
Watchdog failed for 5 consecutive days for:
"BD Carthage" -> [sources/europe/fr/BDCarthage.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/fr/BDCarthage.geojson)

Reason:
Error: No zoom level reachable. (Tested: 6,7,8,9,17,18,19,20) Tiles might not be present at tested location: 0.8649189002685986,46.30642

CC contributors to this imagery:
@rbuffat, @Marc-marc-marc, @grischard

**Comment by Marc-marc-marc** [comment]
temporary failure related to https://github.com/osm-fr/infrastructure/issues/312

**Comment by rbuffat** [comment]
Imagery seems to work again.
