### ISSUE TITLE
[Watchdog] Imagery "Route 500": sources/europe/fr/Route500.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1188]
Watchdog failed for 5 consecutive days for:
"Route 500" -> [sources/europe/fr/Route500.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/fr/Route500.geojson)

Reason:
Error: No zoom level reachable. (Tested: 12,13,14,15,17,18,19,20) Tiles might not be present at tested location: 0.8649189002685986,46.30642

CC contributors to this imagery:
@rbuffat, @Marc-marc-marc, @grischard

**Comment by Marc-marc-marc** [comment]
temporary failure related to https://github.com/osm-fr/infrastructure/issues/312

**Comment by rbuffat** [comment]
Imagery seems to work again.
