### ISSUE TITLE
[Watchdog] Imagery "BANO": sources/europe/fr/BANO.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1189]
Watchdog failed for 5 consecutive days for:
"BANO" -> [sources/europe/fr/BANO.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/fr/BANO.geojson)

Reason:
Error: No zoom level reachable. (Tested: 12,13,14,15,17,18,19,20) Tiles might not be present at tested location: -60.999952248360714,14.634522650000001

CC contributors to this imagery:
@Klumbumbus, @Olyon, @rbuffat, @Marc-marc-marc, @grischard, @tyrasd

**Comment by Marc-marc-marc** [comment]
temporary failure related to https://github.com/osm-fr/infrastructure/issues/312

**Comment by rbuffat** [comment]
@Marc-marc-marc Thanks for providing this information!

**Comment by rbuffat** [comment]
Imagery seems to work again.
