### ISSUE TITLE
ORTOS_DGT_2018_WMS URL is wrong

### ISSUE THREAD

**Issue by don-vip** [osmlab/editor-layer-index#1190]
Europe/pt ORTOS_DGT_2018_WMS uses same URL as ORTOS_DGRF_2004_06:

https://ortos.dgterritorio.gov.pt/wms-inspire/ortos2004-2006?LAYERS=Ortos2004-2006-RGB&STYLES=default&FORMAT=image/jpeg&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap

See JOSM ORTOS_DGT_2018 entry for correct link.

**Comment by rbuffat** [comment]
Thanks  @don-vip ! I messed this up in https://github.com/osmlab/editor-layer-index/commit/dbdb1f7a71ea9e90dff2d51bebfc17c2802a1256
