### ISSUE TITLE
[Watchdog] Imagery "Rio Mosaic 2013": sources/south-america/br/Rio_2013.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1202]
Watchdog failed for 5 consecutive days for:
"Rio Mosaic 2013" -> [sources/south-america/br/Rio_2013.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/br/Rio_2013.geojson)

Reason:
Error: WMS -: Error: No Capabilities Element present: Root tag: html
Error: WMS 1.3.0: Error: No Capabilities Element present: Root tag: html
Error: WMS 1.1.1: Error: No Capabilities Element present: Root tag: html
Error: WMS 1.1.0: Error: No Capabilities Element present: Root tag: html
Error: WMS 1.0.0: Error: No Capabilities Element present: Root tag: html

CC contributors to this imagery:
@tyrasd, @rbuffat, @Skippern, @grischard, @Klumbumbus, @Marc-marc-marc

**Comment by matheusgomesms** [comment]
Fixed on PR #1251

**Comment by rbuffat** [comment]
Imagery seems to work again.
