### ISSUE TITLE
It is not possible to see Brazilian Army Topographic Maps layer data on OSM

### ISSUE THREAD

**Issue by felypeforte** [osmlab/editor-layer-index#1210]
Hi,

Can anyone help me with the following issue:

I used to use a layer called 'Cartas Topográficas do Exército Brasileiro' [Topographic Charts of the Brazilian Army] in Brazil, to map the peaks from my region, and now I cannot see anything when I select the layer. What could be happening?

I have posted this issue on another place and I was instructed to post this issue here. 

https://github.com/openstreetmap/iD/issues/8592#issuecomment-888246938 
(Here's their comment: "I see iD populating url pattern correctly, i suppose the imagery url needs to be updated.
@felypeforte please file an issue here: https://github.com/osmlab/editor-layer-index/issues
This file needs an update: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/south-america/br/Brazilian_Army_Topographic_Maps.geojson")

BDGEx: https://bdgex.eb.mil.br/bdgexapp/mobile/

Thank you guys, sorry if I put anything wrong, I am a lay person, not a developer.

**Comment by rbuffat** [comment]
It looks as this source is now since 126 days broken. Personally, I don't really feel comfortable with Brazil imagery, as I'm neither familiar with the language nor the local laws. 

@naoliv @afmenez or @willemarcel  Could you have a look at this imagery?

**Comment by matheusgomesms** [comment]
@felypeforte, it doesn't seem that the layer is broken. It just looks that the server is very very slow nowadays. Sometimes it works (maybe you have to wait a bit, like a minute or two), sometimes it doesn't. The URL on the layer seems correct. I tried it manually on Custom tab on iD and JOSM and it works sometimes as well.

https://bdgex.eb.mil.br/mapcache?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=ctmmultiescalas_mercator&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

Regarding policy, @rbuffat, it looks like Brazilian Army [allows anyone to use it](https://bdgex.eb.mil.br/portal/index.php?option=com_content&view=article&id=74&Itemid=337&lang=pt).

![exercito](https://user-images.githubusercontent.com/86851490/130507279-d395bbbb-d3f1-4c0e-948c-2e96c3ac17e9.png)

**Comment by eduardoaddad** [comment]
The Brazilian army allows its use (https://wiki.openstreetmap.org/wiki/BDGEx_Tile_Layer or https://wiki.openstreetmap.org/wiki/File:Relatorio-Pedido-BDGEx-2018.pdf)

**Comment by felypeforte** [comment]
Thank you guys. I will try to use it then.
