### ISSUE TITLE
Determine (automatically) which WMTS services support the OGC WMTS Simple Profile

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#1213]
Not very many OSM editors support WMTS sources, however those WMTS servers that have a TileMatrixSet that conforms to the OGC WMTS Simple Profile provide an URL that can be used for tile access just like as for a OSM/google compatible tile server.

If the OGC WMTS Simple Profile is supported it could make sense to either automatically add a new field with the URL to WMTS ELI entries, or simply duplicate them as normal "TMS" entries, so that these can be used without clients having to implement full blown WMTS support. 

 But as a first step, it would simply be interesting to know how many of the existing entries have a conformant TileMatrixSet.

**Comment by rbuffat** [comment]
This is a good idea.

TODOs would be:
- [ ] Query WMTS sources to check if they support the Simple Profile / urn:ogc:def:wkss:OGC:1.0:GoogleMapsCompatible
- [ ] Construct tms URLs from the service metadata
- [ ] Ideally, there should be support for mirrors in ELI (or wmts sources are deleted in favor of TMS)
- [ ] Add check for new wmts sources if simple profile is supported

**Comment by rbuffat** [comment]
Currently, there are not a lot of WMTS sources in ELI. Two of those sources support EPSG3857 and could be added as tms, but for them already an alternative server with WMS is available. But it would be good to switch these to tms.

```
MCGIS-County-NAIP-Imagery-2019 https://mcgis.mesacounty.us/image/rest/services/Mosaic_Datasets/MesaCounty_2019/ImageServer/WMTS/1.0.0/WMTSCapabilities.xml
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::3742

Bern-AmtlicheVermessung https://map.bern.ch/arcgis/rest/services/AV_farbig/MapServer/WMTS?
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::2056

npi-svalbard-landsat https://geodata.npolar.no/arcgis/rest/services/Basisdata/NP_Satellitt_Svalbard_WMTS_25833/MapServer/WMTS/
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::25833

NPI-Svalbard-ortofoto https://geodata.npolar.no/arcgis/rest/services/Basisdata/NP_Ortofoto_Svalbard_WMTS_25833/MapServer/WMTS/
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::25833

npi-svalbard-fkb https://geodata.npolar.no/arcgis/rest/services/Basisdata/FKB_Svalbard_WMTS_25833/MapServer/WMTS/
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::25833

npi-svalbard-topo https://geodata.npolar.no/arcgis/rest/services/Basisdata/NP_Basiskart_Svalbard_WMTS_25833/MapServer/WMTS/
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::25833

NPI-JanMayen-topo https://geodata.npolar.no/arcgis/rest/services/Basisdata/NP_Basiskart_JanMayen_WMTS_25829/MapServer/WMTS/
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::25829

South_Africa-CapeTown-Aerial-2017 https://citymaps.capetown.gov.za/agsext1/rest/services/Aerial_Photography_Cached/AP_2017_Jan/MapServer/WMTS/1.0.0/WMTSCapabilities.xml
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::3857
ID: GoogleMapsCompatible tile_matrix_crs: urn:ogc:def:crs:EPSG:6.18.3:3857

South_Africa-CapeTown-Aerial-2018 https://citymaps.capetown.gov.za/agsext1/rest/services/Aerial_Photography_Cached/AP_2018_Feb/MapServer/WMTS/1.0.0/WMTSCapabilities.xml
ID: default028mm tile_matrix_crs: urn:ogc:def:crs:EPSG::3857
ID: GoogleMapsCompatible tile_matrix_crs: urn:ogc:def:crs:EPSG:6.18.3:3857
```

https://github.com/osmlab/editor-layer-index/pull/1243 intends to add a check for new wmts sources if they contain a layer that could be added as tms. (=> they have a TileMatrixSet that supports urn:ogc:def:crs:EPSG::3857)

**Comment by rbuffat** [comment]
The WMTS standard defines the `GoogleMapsCompatible` TileMatrixSet. This TileMatrixSet requires tiles to be of 256x256 pixels. Only filtering for `urn:ogc:def:crs:EPSG::3857` could find TileMatrixSet with tiles of different resolution. Is this an issue for OSM editors?

> E.4 GoogleMapsCompatible (urn:ogc:def:wkss:OGC:1.0:GoogleMapsCompatible)
> 
> This well-known scale set has been defined to be compatible with Google Maps and
Microsoft Live Map projections and zoom levels. Level 0 allows representing the whole
world in a single 256x256 pixels. The next level represents the whole world in 2x2 tiles
of 256x256 pixels and so on in powers of 2. Scale denominator is only accurate near the
equator.
https://portal.ogc.org/files/?artifact_id=35326

**Comment by simonpoole** [comment]
> The WMTS standard defines the `GoogleMapsCompatible` TileMatrixSet. This TileMatrixSet requires tiles to be of 256x256 pixels. Only filtering for `urn:ogc:def:crs:EPSG::3857` could find TileMatrixSet with tiles of different resolution. Is this an issue for OSM editors?
> 
I was originally thinking of just filtering for 'GoogleMapsCompatible'. In any case I suspect most editors can handle 512 and other multiples of 256, but we would need to include that in the config (there's a tile-size attribute so we can convey that info).

**Comment by cicku** [comment]
I've found few exceptions at USGS WMTS. It appears that different zoom level has different GoogleMapsCompatible name.

Here is an example for Hurricane Ida: https://storms.ngs.noaa.gov/storms/ida/services/WMTSCapabilities.xml

**Comment by rbuffat** [comment]
@cicku @simonpoole  The strict_check should now warn if there is a compatible tms URL available. For the WMTS Url of https://github.com/osmlab/editor-layer-index/issues/1213#issuecomment-917650745
the script now returns:

```
WARNING:root:Layer 20210902a-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210902a-rgb/{zoom}/{x}/{y}
WARNING:root:Layer 20210831a-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210831a-rgb/{zoom}/{x}/{y}
WARNING:root:Layer 20210901b-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210901b-rgb/{zoom}/{x}/{y}
WARNING:root:Layer 20210831b-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210831b-rgb/{zoom}/{x}/{y}
WARNING:root:Layer 20210830a-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210830a-rgb/{zoom}/{x}/{y}
WARNING:root:Layer 20210902b-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210902b-rgb/{zoom}/{x}/{y}
WARNING:root:Layer 20210830b-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210830b-rgb/{zoom}/{x}/{y}
WARNING:root:Layer 20210901a-rgb could be represented as type 'tms' and the URL: https://stormscdn.ngs.noaa.gov/20210901a-rgb/{zoom}/{x}/{y}
```
