### ISSUE TITLE
Maxar Premium

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/editor-layer-index#1217]
Hi,

For about one week, I have no more imagery of Maxar Premium :
- in the beginning, imagery was blurry at some zoom.
- now, all is black

It was the best imagery in Bolivia so this bug is a big lost.

Here an example of a place with no more imagery :
https://www.openstreetmap.org/edit#map=18/-22.53417/-67.28902

Best regards

**Comment by grischard** [comment]
Abuse issues on the Maxar side, unfortunately. Hopefully it'll be fixed soon.

**Comment by cicku** [comment]
I think the issue can be closed now.

**Comment by Mahabarata** [comment]
I'm not sure : yes I agree that now we have something.
But one month ago I created tracks in desert because these tracks were only visible on Maxar Premium (more recent and better definition).
This one for exemple :
https://www.openstreetmap.org/edit#map=19/-22.87779/-67.42185
a 44 km links between 2 lakes in a park.

These tracks are no longer visible : it looks like Maxar Premium is not Maxar Premium but Maxar Standard.

I don't know what your contract is with them but, for Bolivia, they don't "sell" you what they say they "sell" you.
Best regards
Mahab

**Comment by cicku** [comment]
In this case, you should contact Maxar directly regarding the issue.

This is the link: https://www.maxar.com/contact-us

**Comment by Mahabarata** [comment]
I can see that now there is only one Maxar imagery (Maxar Premium), Maxar Standard has been deleted (even if, for Bolivia, we have the old Maxar Standard and not the new Maxar Premium, because the new track of my last post is still no more visible).
So with only one Maxar imagery, this issue is solved for me.
I close it.

**Comment by Mahabarata** [comment]
Just to illustrate the problem in another way :
here you have a crossroads =
https://www.openstreetmap.org/edit?way=924980260#map=19/38.75468/-90.65398

If you look at all satellite images, espacially Maxar, the ways seem to be at the wrong places. But it is false : imagery is old and the ways are ok. You can see it if you open ggle earth and look at the history of images, the most recents are from septembre 2021 and fit the new crossroads on osm.

The problem is that these recent images are from... Maxar. Why, on osm, we don't have them ?

Best regards.

**Comment by simonpoole** [comment]
As has already been pointed out you need to ask maxar. They provide whatever they want to in the context of this free service and are under no obligation to do anything specific.

**Comment by Mahabarata** [comment]
Both examples above (my comments on 21 Nov 2021 and on 6 Nov 2021/28 Aug 2021) are working now : Maxar Premium is back, great !
