### ISSUE TITLE
[Watchdog] Imagery "Mesa County GIS NAIP 2017": sources/north-america/us/co/MesaCountyImagery2017.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1256]
Watchdog failed for 5 consecutive days for:
"Mesa County GIS NAIP 2017" -> [sources/north-america/us/co/MesaCountyImagery2017.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/co/MesaCountyImagery2017.geojson)

Reason:
Error: WMS -: Error: Could not parse XML.
Error: WMS 1.3.0: Error: Could not parse XML.
Error: WMS 1.1.1: Error: Could not parse XML.
Error: WMS 1.1.0: Error: Could not parse XML.
Error: WMS 1.0.0: Error: Could not parse XML.

CC contributors to this imagery:
@rbuffat, @tsmock, @Marc-marc-marc, @grischard

**Comment by tsmock** [comment]
It looks like they have removed that imagery (it is also no longer downloadable).

**Comment by rbuffat** [comment]
Imagery seems to work again.
