### ISSUE TITLE
[Watchdog] Imagery "IBGE Nomes de Ruas": sources/south-america/br/IBGE_Street_Names.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1261]
Watchdog failed for 5 consecutive days for:
"IBGE Nomes de Ruas" -> [sources/south-america/br/IBGE_Street_Names.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/br/IBGE_Street_Names.geojson)

Reason:
Error: No zoom level reachable. (Tested: 4,5,6,7,19,20,21,22) Tiles might not be present at tested location: -49.60756145539132,-14.398

CC contributors to this imagery:
@willemarcel, @naoliv, @rbuffat

**Comment by naoliv** [comment]
The summary is: somebody abused it (at the end of August) and they suspended the account.
![](https://user-images.githubusercontent.com/982338/132967061-acb7e6f7-2a80-4d40-8367-3eb88ddd66f4.png)
![](https://user-images.githubusercontent.com/982338/132967067-65876bbb-364d-4e1c-8835-c409deac6661.png)

**Comment by rbuffat** [comment]
@naoliv Thanks for the heads up! Does this reset automatically?

**Comment by willemarcel** [comment]
@rbuffat I created a PR with the solution to this issue: https://github.com/osmlab/editor-layer-index/pull/1302
