### ISSUE TITLE
[Watchdog] Imagery "Delaware 2017 Orthophotography": sources/north-america/us/de/Delaware2017Orthophotography.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1264]
Watchdog failed for 5 consecutive days for:
"Delaware 2017 Orthophotography" -> [sources/north-america/us/de/Delaware2017Orthophotography.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/de/Delaware2017Orthophotography.geojson)

Reason:
Error: WMS -: Error: Could not parse XML.
Error: WMS 1.3.0: Error: Could not parse XML.
Error: WMS 1.1.1: Error: Could not parse XML.
Error: WMS 1.1.0: Error: Could not parse XML.
Error: WMS 1.0.0: Error: Could not parse XML.

CC contributors to this imagery:
@rbuffat, @grischard

**Comment by cicku** [comment]
https://github.com/osmlab/editor-layer-index/pull/1242

**Comment by rbuffat** [comment]
Imagery seems to work again.
