### ISSUE TITLE
[Watchdog] Imagery "Delaware 2012 Orthophotography": sources/north-america/us/de/Delaware2012Orthophotography.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1265]
Watchdog failed for 5 consecutive days for:
"Delaware 2012 Orthophotography" -> [sources/north-america/us/de/Delaware2012Orthophotography.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/de/Delaware2012Orthophotography.geojson)

Reason:
Error: WMS -: Error: Could not parse XML.
Error: WMS 1.3.0: Error: Could not parse XML.
Error: WMS 1.1.1: Error: Could not parse XML.
Error: WMS 1.1.0: Error: Could not parse XML.
Error: WMS 1.0.0: Error: Could not parse XML.

CC contributors to this imagery:
@Klumbumbus, @grischard, @rbuffat, @Marc-marc-marc, @simon04

**Comment by cicku** [comment]
https://github.com/osmlab/editor-layer-index/pull/1242

**Comment by cicku** [comment]
For DE 2012 imagery, please just remove the file as it does not serve any value in fall 2021. It is almost from 10 years ago.

Moreover, 2017 imagery is already dated as well. State of Delaware update orthoimagery every 5 years, 2022 imagery will be published in the next year.

**Comment by rbuffat** [comment]
Imagery seems to work again.
