### ISSUE TITLE
Difference between icon and logo-image?

### ISSUE THREAD

**Issue by cicku** [osmlab/editor-layer-index#1295]
Hi,

What is the difference between these two?

Thank you.

**Comment by andrewharvey** [comment]
Per the schema

https://github.com/osmlab/editor-layer-index/blob/01a00af75d10fb353e95b14dd11e8f91a90cda55/schema.json#L180-L182

icon needs a description in the schema, but it's used in the menu list of imagery next to the name (compared to logo-image) which is a kind of watermark logo in the bottom corner of the map for attribution.
