### ISSUE TITLE
[Watchdog] Imagery "Orthophoto (1994–1999), B&W, 1:30000, Latvia": sources/europe/lv/lv_orthophoto_cycle1_1994-1999.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1313]
Watchdog failed for 5 consecutive days for:
"Orthophoto (1994–1999), B&W, 1:30000, Latvia" -> [sources/europe/lv/lv_orthophoto_cycle1_1994-1999.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/lv/lv_orthophoto_cycle1_1994-1999.geojson)

Reason:
Error: WMS -: Error: Could not parse XML.
Error: WMS 1.3.0: Error: Could not parse XML.
Error: WMS 1.1.1: Error: Could not parse XML.
Error: WMS 1.1.0: Error: Could not parse XML.
Error: WMS 1.0.0: Error: Could not parse XML.

CC contributors to this imagery:
@rbuffat, @soshial

**Comment by soshial** [comment]
Updated the server URL in the PR #1315.

**Comment by rbuffat** [comment]
Imagery seems to work again.
