### ISSUE TITLE
MapMetrics

### ISSUE THREAD

**Issue by Lee-Carre** [osmlab/editor-layer-index#1316]
## Category
Overlay. QA for routing.

Background info:
* [Happy birthday, OpenStreetMap!](http://www.tomtom.com/blog/maps/tomtom-openstreetmaps-mapmetrics-map-editing/) (introductory announcement)
* [The battle for quality maps](http://www.tomtom.com/blog/maps/the-battle-for-quality-maps/) (more details, including refinement of their dataset (by excluding false-positives))

## URL of the imagery
There are multiple tilesets comprising combinations of dates (usually per-month, with (delta\|diff)s) & types (average, median, median_count). See [MapMetrics Web-UI](http://mapmetrics-world.innovation.tomtom-global.com/).

Example: http://mapmetrics-world.innovation.tomtom-global.com/tiles/median_count/OSM202109/{zoom}/{x}/{y}.png ([source](http://www.teddit.net/r/openstreetmap/comments/qfmgci/the_battle_for_high_quality_maps/))

Values for {zoom} seem to be: 8, 10, 16. However, I've not exhaustively tested & verified those numbers.

## Two letter country code
Global / World-wide

## Desired layer name
“MapMetrics”(?)

## License
Unclear. However, having read the [FAQ](http://github.com/osmlab/editor-layer-index/blob/gh-pages/FAQ.md), this source isn't for tracing, but simply finding areas with problematic routing. See the background info links up top.

Besides, they make the dataset available both as a compressed archive and via an [API](http://mapmetrics-world.innovation.tomtom-global.com/apiDoc.html). So, seems that the intent is permissive usage. The likely goal seems to be to (enable the community to) improve OSM data.

Although I'm a non-lawyer, it might be possible to argue that the data is a derivative of OSM's, since it's the result of comparing OSM's road network data (used to produce routing paths) & the GNSS traces of actual drivers (which I think would be public domain(?) in terms of copyright, separately from privacy concerns).

## Is the license compatible with OSM?
Being a QA overlay, I would think so.

## Attribution (text, URL, required?)
“TomTom MapMetrics”?

I couldn't find any mention, on the site, of a required attribution string.

## Privacy policy (URL)
http://www.tomtom.com/privacy/

## Icon
Perhaps the site's /favicon.ico but there's probably copyright & trademark entanglements with doing that.

## Bounding polygon
Data is planet-wide, so not applicable.

**Comment by cicku** [comment]
I don’t think Tomtom products can be used for OSM. It is just another kind of google maps.

However, an explicit waiver/statement should be obtained from Tomtom if you really think it is possible. Apple Maps uses OSM as well, but it does not mean you can use it in a reverse way.
