### ISSUE TITLE
Geoportal 2 imagery: Longer loading times than expected

### ISSUE THREAD

**Issue by Asteliks** [osmlab/editor-layer-index#1324]
@rbuffat @andrewharvey 

Something seems to be wrong with iD editor. In Poland the Geoportal 2 layers are loading painstakingly long. At first I thought that this is something with the provider but the exact same layers load instantly in JOSM. Thus I'll need some help concerning this topic.

**Comment by rbuffat** [comment]
@Asteliks does JOSM use a different server or does JOSM cache tiles locally?

**Comment by Asteliks** [comment]
I made sure to use the same server and clear the cache

**Comment by Asteliks** [comment]
@rbuffat I've brought up the same issue here: https://github.com/openstreetmap/iD/issues/8789
Just to make sure, dose iD support WMTS? What do you think about switching the geoportal sources from WMS to WMTS?

**Comment by rbuffat** [comment]
To my knowledge, iD does not support WMTS*. The main issue is that WMTS serves datasets in specific coordinate projections. Unlike WMS, which reprojects data on the fly in a projection iD understands. Under some circumstances, some of these projections can be used with iD (See https://github.com/osmlab/editor-layer-index/issues/1213). These datasets can then be added as tms sources.  As far as I'm aware, there is no javascript library that supports accurate coordinate transformation for arbitrary projections. Thus implementing WMTS support in iD might be challenging.

**Comment by tyrasd** [comment]
> Just to make sure, dose iD support WMTS?

See answer in https://github.com/openstreetmap/iD/issues/8789#issuecomment-961714182.

iD can _work_ with all WMTS sources which support the "standard slippy map tile scheme" used by OSM/Leaflet/Google/etc. – The same is true for WMS sources as well, where iD can only use services which support at least one of a few projections iD understands (which would be `EPSG:3857`, `EPSG:4326` and their synonyms, if I'm not mistaken).

As already mentioned in https://github.com/openstreetmap/iD/issues/8789, in this particular instance, the "Geoportal 2" service does support a tileset compatible with iD. This is the corresponding TMS URL which could be used instead of the slow WMS service:

```
https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTOFOTOMAPA&STYLE=default&FORMAT=image/jpeg&tileMatrixSet=EPSG:3857&tileMatrix=EPSG:3857:{zoom}&tileRow={y}&tileCol={x}
```

**Comment by tyrasd** [comment]
I've prepared #1326 to add the WMTS variant for this layer. Not sure if it's worth it to keep the WMS around (JOSM has both). What do you think?

**Comment by Asteliks** [comment]
I would keep them just as a backup in case TMS is down, unless they are on the same server

**Comment by Asteliks** [comment]
Note that the source you updated is just the tip of an iceberg because there are other layers that may require this update:

- [ ] https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Ewidencjabudynk%C3%B3wWMS.geojson
- [ ] https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Ewidencjagrunt%C3%B3w.geojson
- [ ] https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Nazwyulic.geojson
- [x] https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson
- [ ] https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2OrthophotomapHighQuality(aerialimage).geojson
- [ ] https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2PRNG(geonames).geojson
- [ ] https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Punktyadresowe.geojson

The official source can be found here: https://www.geoportal.gov.pl/uslugi/usluga-przegladania-wms

Some of these are overlays

**Comment by tyrasd** [comment]
For now I have only updated the "latest" layer because:

* the "latest" layer is marked to be `best` (i.e. default) one for this region
* the overlay layers I tested don't seem to be particularly slow even on the WMS
* the "high resolution, but outdated" of the WMS also seems to be not as painfully slow as the "latest" imagery is, and since the layer seems to be discouraged for editing (as being _outdated_), I'm not sure if it would be worth the effort

> I would keep them just as a backup in case TMS is down, unless they are on the same server

AFAICS they are on the same server, but it could still be the case that in some situations one of the services is down while the other might continue to work.

**Comment by Asteliks** [comment]
> For now I have only updated the "latest" layer because:
> 
> * the "latest" layer is marked to be `best` (i.e. default) one for this region

<3

> * the overlay layers I tested don't seem to be particularly slow even on the WMS

That is true

> * the "high resolution, but outdated" of the WMS also seems to be not as painfully slow as the "latest" imagery is, and since the layer seems to be discouraged for editing (as being _outdated_), I'm not sure if it would be worth the effort

Well technically the high resolution isn't outdated. It is the same as the best layer, the difference is that the default layer depicts the latest tiles (not necessary in high resolution) for the region and the high resolution one choses the latest tiles that are in higher resolution (and thus potentially outdated). Also the high resolution variant is only available for bigger cities. I would recommend not omitting this layer as it is a vital one for accurate mapping in Poland. 

> 
> > I would keep them just as a backup in case TMS is down, unless they are on the same server
> 
> AFAICS they are on the same server, but it could still be the case that in some situations one of the services is down while the other might continue to work.

In that case I would recommend keeping the old one just in case

**Comment by tyrasd** [comment]
> I would recommend not omitting this layer as it is a vital one for accurate mapping in Poland.

OK, let's include the "high res" layer in the PR as well. :+1: Then everything should be fine to use.

**Comment by tyrasd** [comment]
> > I would recommend not omitting this layer as it is a vital one for accurate mapping in Poland.
> 
> OK, let's include the "high res" layer in the PR as well. +1 Then everything should be fine to use.

Surprisingly, the WMTS endpoint of the "highResolution" layer does not offer a compatible tileset which is supported by iD. This is a bit strange since the other layer does support the EPSG:3857 tile scheme. man_shrugging So, sadly, there's not much we can do to improve that layer at the moment.

**Comment by Asteliks** [comment]
> > > I would recommend not omitting this layer as it is a vital one for accurate mapping in Poland.
> > 
> > 
> > OK, let's include the "high res" layer in the PR as well. +1 Then everything should be fine to use.
> 
> Surprisingly, the WMTS endpoint of the "highResolution" layer does not offer a compatible tileset which is supported by iD. This is a bit strange since the other layer does support the EPSG:3857 tile scheme. man_shrugging So, sadly, there's not much we can do to improve that layer at the moment.

Ok, now I got it to work. Thanks.

This change leads us to another problem: https://brouter.de/brouter-web/#map=17/52.20936/20.95505/cyclosm&lonlats=20.953449,52.205529;20.954511,52.212012
With these changes the router chooses a poor quality street over the high quality kurhan street:
![image](https://user-images.githubusercontent.com/62251475/140508918-706938ce-4033-41cf-a810-0f92be82dc93.png)
