### ISSUE TITLE
[Watchdog] Imagery "Ukraine - Vinnytsia TG 2021": sources/europe/ua/Ukraine-Vinnytsia2021.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1342]
Watchdog failed for 5 consecutive days for:
"Ukraine - Vinnytsia TG 2021" -> [sources/europe/ua/Ukraine-Vinnytsia2021.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/ua/Ukraine-Vinnytsia2021.geojson)

Reason:
Error: No zoom level reachable. (Tested: 14,15,16,17,18,19) Tiles might not be present at tested location: 28.571171740718196,49.26765

CC contributors to this imagery:
@bezdna

**Comment by bezdna** [comment]
maybe its for only for Ukraine IP
i have access https://maps2.vmr.gov.ua/OpenData/ofp/2021-03/GoogleMapsCompatible/18/89765/151810.png?ver=03082021
link opens this image:
![image](https://user-images.githubusercontent.com/518939/142589265-41df5bd5-c945-4b0b-8c35-4b8ed04905c2.png)

**Comment by rbuffat** [comment]
Imagery seems to work again.

**Comment by rbuffat** [comment]
@bezdna Thanks for checking! The script to check the imagery sources should be fixed with https://github.com/rbuffat/eli_watchdog/commit/d1941deee320ab291aa7020730f56812f9e2f6d4
