### ISSUE TITLE
Layer names missing in Transifex

### ISSUE THREAD

**Issue by ignaciolep** [osmlab/editor-layer-index#1355]
Hi,
I noticed that the [Argentina's imagery](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/ar) are missing the translations in iD.

![IGN layers](https://user-images.githubusercontent.com/13091755/144255572-995c84bb-a47c-4b93-adcb-128db9e7f416.png)

The [Transifex imagery resource](https://www.transifex.com/openstreetmap/id-editor/translate/#es/imagery/) is 100% translated to Spanish, but is doesn't have those strings. Any idea why?

Thanks!

**Comment by grischard** [comment]
The strings should be on transifex now. Thank you!

**Comment by ignaciolep** [comment]
Hi @grischard ,
Unfortunately it didn't work. Argentina's layers are still missing, and there are now 139 untranslated strings that were already translated before this change.
