### ISSUE TITLE
[Watchdog] Imagery "Postcode centroids": sources/europe/gb/Code-Point_Open.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1358]
Watchdog failed for 5 consecutive days for:
"Postcode centroids" -> [sources/europe/gb/Code-Point_Open.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/gb/Code-Point_Open.geojson)

Reason:
Error: URL validation error:  https://www.raggedred.net/tiles/codepoint/{zoom}/{x}/{y}.png
Error: No zoom level reachable. (Tested: 16,17,18,19,20) Tiles might not be present at tested location: -2.3869499000000003,54.6982799

CC contributors to this imagery:
@Cj-Malone

**Comment by Cj-Malone** [comment]
Presumably that is lon/lat, not lat/lon.

It's in the middle of nowhere, a [transparent tile](https://www.raggedred.net/tiles/codepoint/20/517335/333188.png) is the expected result.

**Comment by rbuffat** [comment]
@Cj-Malone There was a white space character in front of the URL. I was probably too tired to spot it when I looked at it the first time.

**Comment by Cj-Malone** [comment]
Whoops, my bad. Thank you.

**Comment by rbuffat** [comment]
No worries, I also didn't spot it the first time in https://github.com/osmlab/editor-layer-index/pull/1219#issuecomment-907762136
