### ISSUE TITLE
New GB OS Imagery Oct 2021

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/editor-layer-index#1362]
The file: [../europe/gb/OSOpenMapLocal.geojson](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OSOpenMapLocal.geojson) (added by @TurnrDev ) currently refers to the April 2021 imagery in GB, which is currently being hosted at [os.openstreetmap.org](https://os.openstreetmap.org/) and is usable within iD.

However, @Firefishy uploaded the new [October 2021 imagery](https://github.com/openstreetmap/chef/pull/471) to the same server, which I believe is accessible via the URL structure: https://{switch:a,b,c}.os.openstreetmap.org/layer/gb_os_om_local_2021_10/{zoom}/{x}/{y}.png

Does the editor-layer-index prefer a new reference file for the new imagery, or could the existing [../europe/gb/OSOpenMapLocal.geojson](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OSOpenMapLocal.geojson) file be updated to make use of the newest image data?

**Comment by boothym** [comment]
@Cj-Malone would it be possible to create a PR to add the newest OS Local from April 2022? It seems to be located at 
https://{switch:a,b,c}.os.openstreetmap.org/layer/gb_os_om_local_2022_04/{zoom}/{x}/{y}.png

**Comment by Cj-Malone** [comment]
<del>Yeah, I can do that soon.</del> Opened #1534

Do we know who runs os.osm.org? Maybe we could get a `latest` redirect?

**Comment by boothym** [comment]
Thanks. I think it must be Grant aka Firefishy as mentioned above.

I've just found where it was committed a couple of weeks ago.  https://github.com/openstreetmap/chef/commit/be28146ca2e5f5c3a11d9cb6b57d6287b2abb1d8
