### ISSUE TITLE
World Imagery Wayback

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/editor-layer-index#1364]
It would be nice get [World Imagery Wayback](https://livingatlas.arcgis.com/wayback/) ([via](https://www.openstreetmap.org/user/Deane%20Kensok/diary/397014)) into editors. I don't know how hard it would be to add, there is [WMTS Server](https://wayback.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/WMTS/1.0.0/WMTSCapabilities.xml) but for some reason I can't get it to work in JOSM.

**Comment by rbuffat** [comment]
@Cj-Malone What are the license/terms of this data?

**Comment by Cj-Malone** [comment]
These are old versions of World Imagery. World Imagery is [available](https://wiki.openstreetmap.org/wiki/Esri) for OSM mappers. An Esri employee has [publicly documented](https://www.openstreetmap.org/user/Deane%20Kensok/diary/397014) how to use Wayback in iD, so I don't see any reason to believe that the historical World Imagery is licenced any differently to the current.

**Comment by rivermont** [comment]
This sounds like something that would be more of use to OHM. I don't really see how using old imagery benefits OSM, except maybe to confirm change.

**Comment by cicku** [comment]
This layer has nothing to do with OpenStreetMap. Please bring it to https://wiki.openstreetmap.org/wiki/Open_Historical_Map.

**Comment by andrewharvey** [comment]
> This layer has nothing to do with OpenStreetMap. Please bring it to https://wiki.openstreetmap.org/wiki/Open_Historical_Map.

I think in normal mapping work it's useful to have historical imagery. It helps give context to other changes and edits.

For example if an area the data doesn't match the imagery, you can compare older imagery, if you find the data matches older imagery you know that the data is outdated and you can update it, rather than the data being newer than the imagery in which case you can't.

**Comment by Cj-Malone** [comment]
> > This layer has nothing to do with OpenStreetMap. Please bring it to https://wiki.openstreetmap.org/wiki/Open_Historical_Map.
> 
> I think in normal mapping work it's useful to have historical imagery. It helps give context to other changes and edits.
> 
> For example if an area the data doesn't match the imagery, you can compare older imagery, if you find the data matches older imagery you know that the data is outdated and you can update it, rather than the data being newer than the imagery in which case you can't.

I often look at older imagery when there is a building in OSM, but not in the current imagery. Is the building newer than imagery? Under trees? Or demolished?
