### ISSUE TITLE
[Watchdog] Imagery "Hamburg DK5 (HH LGV DK5 2021)": sources/europe/de/Hamburg-DK5.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1367]
Watchdog failed for 5 consecutive days for:
"Hamburg DK5 (HH LGV DK5 2021)" -> [sources/europe/de/Hamburg-DK5.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/de/Hamburg-DK5.geojson)

Reason:
Error: Layers '1' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@rbuffat, @hauke96, @simon04, @Klumbumbus, @tyrasd, @iandees, @grischard

**Comment by hauke96** [comment]
Yeah, the LGV recently changed the layer name. I created the PR #1368.

**Comment by hauke96** [comment]
Since the PR is already merged, I guess this can be closed?

**Comment by rbuffat** [comment]
@hauke96 We can close it, but the script that checks the imagery each night should also close the issue when it detects that the imagery is again reachable.
