### ISSUE TITLE
[Watchdog] Imagery "PNOA Spain": sources/europe/es/PNOASpain.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1386]
Watchdog failed for 5 consecutive days for:
"PNOA Spain" -> [sources/europe/es/PNOASpain.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/es/PNOASpain.geojson)

Reason:
Error: WMS -: URL: https://www.idee.es/wms/PNOA/PNOA?SERVICE=WMS&REQUEST=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://www.idee.es/wms/PNOA/PNOA?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://www.idee.es/wms/PNOA/PNOA?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://www.idee.es/wms/PNOA/PNOA?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://www.idee.es/wms/PNOA/PNOA?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0 Error: Could not parse XML.
Error: WMS -: URL: https://www.idee.es/wms/PNOA/PNOA?service=WMS&request=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://www.idee.es/wms/PNOA/PNOA?service=WMS&request=GetCapabilities&version=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://www.idee.es/wms/PNOA/PNOA?service=WMS&request=GetCapabilities&version=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://www.idee.es/wms/PNOA/PNOA?service=WMS&request=GetCapabilities&version=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://www.idee.es/wms/PNOA/PNOA?service=WMS&request=GetCapabilities&version=1.0.0 Error: Could not parse XML.

CC contributors to this imagery:
@alejandroscf, @rbuffat, @grischard, @Klumbumbus, @simon04, @iandees, @tyrasd

**Comment by rbuffat** [comment]
There is also a TMS source for this imagery available: https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/europe/es/PNOASpain-TMS.geojson

Should we just remove this one?

**Comment by alejandroscf** [comment]
They just changed the domain and url, now its here: 
http://www.ign.es/wms-inspire/pnoa-ma?request=GetCapabilities&service=WMS
I'll try to update the geojson
