### ISSUE TITLE
[Watchdog] Imagery "GURS: Building outlines": sources/europe/si/GURSBuildingoutlines.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1389]
Watchdog failed for 5 consecutive days for:
"GURS: Building outlines" -> [sources/europe/si/GURSBuildingoutlines.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/si/GURSBuildingoutlines.geojson)

Reason:
Error: No zoom level reachable. (Tested: 8,9,10,11,16,17,18,19) Tiles might not be present at tested location: 14.630883704654067,46.153435

CC contributors to this imagery:
@stefanb, @grischard, @rbuffat

**Comment by rbuffat** [comment]
Imagery seems to work again.

**Comment by stefanb** [comment]
Yeah, there was a bug with automatic petiodic update, fixed in https://github.com/fossgis/wms.openstreetmap.de/commit/33e19fd5d0578e18ab546e7dea90c4ccc778c3b9

Tnx for checking it!
