### ISSUE TITLE
[Watchdog] Imagery "National Geographic Institute Mosaic 50k (TMS)": sources/south-america/ar/IGN-Cartas-50k.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1393]
Watchdog failed for 5 consecutive days for:
"National Geographic Institute Mosaic 50k (TMS)" -> [sources/south-america/ar/IGN-Cartas-50k.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/ar/IGN-Cartas-50k.geojson)

Reason:
Error: No zoom level reachable. (Tested: 0,1,2,3,12,13,14,15) Tiles might not be present at tested location: -64.27297196589531,-38.725905

CC contributors to this imagery:
@Zalitoar

**Comment by Zalitoar** [comment]
Hi @rbuffat,

Critical errors were produced while updating some images in that mosaic layer, it crashed the whole GeoSever instance.
Since then at @ign-argentina we're analyzing the problem after the rest of the service was restored.

We hope to solve the problem on the coming days.

**Comment by rbuffat** [comment]
@Zalitoar Thanks for the heads up! These issues are created automatically by a script: https://github.com/rbuffat/eli_watchdog They should be closed automatically once the script detects that the imagery is working again. (The script runs once per day).

**Comment by rbuffat** [comment]
Imagery seems to work again.
