### ISSUE TITLE
[Watchdog] Imagery "PEMA Orthoimagery - Adams County (2021)": sources/north-america/us/pa/Adams_PEMA_2021.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1399]
Watchdog failed for 5 consecutive days for:
"PEMA Orthoimagery - Adams County (2021)" -> [sources/north-america/us/pa/Adams_PEMA_2021.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/pa/Adams_PEMA_2021.geojson)

Reason:
Error: URL validation error: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?FORMAT=image/jpeg&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=2&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
Error: WMS None: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetCapabilities
Error: WMS 1.3.0: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
Error: WMS 1.1.1: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1
Error: WMS 1.1.0: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0
Error: WMS 1.0.0: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0
Error: WMS None: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?service=WMS&request=GetCapabilities
Error: WMS 1.3.0: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?service=WMS&request=GetCapabilities&version=1.3.0
Error: WMS 1.1.1: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?service=WMS&request=GetCapabilities&version=1.1.1
Error: WMS 1.1.0: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?service=WMS&request=GetCapabilities&version=1.1.0
Error: WMS 1.0.0: Could not parse URL: wms:https://imagery.pasda.psu.edu/arcgis/services/pasda/PEMAImagery_AdamsCounty2021/MapServer/WmsServer?service=WMS&request=GetCapabilities&version=1.0.0

CC contributors to this imagery:
@cicku

**Comment by cicku** [comment]
Fixed in https://github.com/osmlab/editor-layer-index/commit/63a325a0a609c6ea25af806e331da72f2d903638
