### ISSUE TITLE
[Question] About creating an Issue or plural Issues for multiple datasets

### ISSUE THREAD

**Issue by nyampire** [osmlab/editor-layer-index#1400]
I recently discovered that a number of GeoTIFFs are available under an open license as part of a project called Plateau, run by the Japanese government.
(This is a multiple license under the Japanese government's open data license agreement, CC-BY4.0, ODC-BY or ODbL)

OSM Foundation Japan branch is currently converting the data into tiles and making them available for use in OSM mapping and quality assurance work for Plateau data importing.
There are 24 cities in the GeoTIFF data set, but the cities are far from each other, so there will be multiple layers for each data set.
We are concerned that the number of issues will be too much because there are 24.

Is it acceptable to submit issues one by one for each layer?
Or is it better to create multiple configuration geojson-files and register them as a single issue?

**Comment by cicku** [comment]
What kind of REST service they use to publish these tiles? WMS? WMTS? JSON?

**Comment by nyampire** [comment]
It will be xyz TMS, and will be created for each city.

**Comment by cicku** [comment]
If each place will be assigned an unique TMS URL then you have to submit 24 different files. You can submit one by one or all in one, it is up to you and there is no issue as long as they are free to go.

However, if 24 cities are published under one TMS URL then it is not needed, GeoJSON supports multiple places together in one file.

**Comment by nyampire** [comment]
Thanks a lot, I understood! And I'm glad to know we can use multipolygon feature to indicate multiple places.

I'll discuss this to our team which approach could be better. (to use, to operate and/or to update in future and so on.)

**Comment by nyampire** [comment]
(This issue could be closed)

**Comment by nyampire** [comment]
Hello team, sorry to add re-open comment on this issue. @cicku 

I'm writing the geojson to register 24 cities of Japan.
(Plateau project starts TMS service as official finally!)

It could be `FeatureCollection` I guess, but `FeatureCollection` could not include `properties`.

Could you give me a hint to write properties for this layer-index as valid format?

My WIP file is here. 
https://github.com/nyampire/editor-layer-index/blob/Add_JP_plateau/sources/asia/jp/JapanMLIT-PlateauOfficial.geojson

**Comment by cicku** [comment]
An example is here:

https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/ar/ADOP_2017_6in.geojson

**Comment by nyampire** [comment]
Thank you so much! @cicku 
I have successfully created the geojson file. Separately, I would like to submit a PR.
