### ISSUE TITLE
Ohio Statewide Imagery Program III

### ISSUE THREAD

**Issue by 1ec5** [osmlab/editor-layer-index#1407]
For some reason, the Ohio Statewide Imagery Program never updated their “[OSIP 6in Imagery Most Current Available](https://github.com/osmlab/editor-layer-index/blob/bd09c22eff54bbe6334c6f109de5b81420e4b8b5/sources/north-america/us/oh/Ohio_OSIP_6in.geojson?short_path=52718e8)” layer to include the OSIP&nbsp;III imagery collected in 2020 in several southeastern Ohio counties. This imagery wound up in a separate layer instead. Unfortunately, the separate layer is not WMS-enabled, so we’ll need to rely on the `exportImage` verb as in #611.

## URL of the imagery
https://geo1.oit.ohio.gov/arcgis/rest/services/OSIP/OSIPIII_6in/ImageServer/
or
https://geo1.oit.ohio.gov/arcgis/rest/services/OSIP/OSIPIII_2020_6in/ImageServer/ (seems to be identical)

## Two letter country code
US

## Desired layer name
OSIP III 6in

## License
[Public domain](https://ogrip.oit.ohio.gov/Portals/0/PDFs/OSIP%20Program%20Description.pdf#page=2)

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
> [Ohio Statewide Imagery Program](https://ogrip.oit.ohio.gov/ProjectsInitiatives/StatewideImagery.aspx)

(not required)

## Privacy policy (URL)
https://ogrip.oit.ohio.gov/privacy.aspx

## Bounding polygon
[Overpass query](https://overpass-turbo.eu/s/1fB6)

**Comment by 1ec5** [comment]
OGRIP now offers [separate ImageServers](https://geo1.oit.ohio.gov/arcgis/rest/services/OSIP) for 72 of Ohio’s 88 counties, all of them at 6-inch resolution. We’d be able to indicate the vintage year of each county’s OSIP layer, since each county was flown over only within the same year. We could confidently mark many of these layers as `best`, except where Bing imagery is more recent and at a reasonable resolution. The bounding polygon for each layer can be exported from OSM and simplified.

**Comment by cicku** [comment]
Are you trying to add 72 new files here?

**Comment by 1ec5** [comment]
After [discussing the matter](https://osmus.slack.com/archives/C7Q912JDT/p1641893164008500) with other Ohio-based mappers in OSMUS Slack, we agreed that the 72 per-county layers would be less convenient than the single layer for all 72 counties, because it’s very common to need to draw something across county lines. If there’s a particular county where Bing is very poor and OSIP III was taken in 2020 (as opposed to earlier like 2017), then we might consider adding that county’s layer and marking it `best`.

**Comment by 1ec5** [comment]
Here’s the URL template a few of us have been using temporarily in iD:

```
https://geo1.oit.ohio.gov/arcgis/rest/services/OSIP/OSIPIII_6in/ImageServer/exportImage?f=image&bbox={bbox}&imageSR={wkid}&bboxSR={wkid}&SR={proj}&size={width}%2C{height}
```
