### ISSUE TITLE
"best" imagery is wrongly placed in the "overlay" list in iD

### ISSUE THREAD

**Issue by sanderd17** [osmlab/editor-layer-index#141]
When editing in Flanders, we noticed that our best imagery (from AGIV) is suddenly located in the overlay part of the list, and not in the main selection (see http://www.openstreetmap.org/edit?editor=id#map=19/51.21350/3.23967 as example)

Maybe it's a good idea to add an extra flag to include imagery in the "overlay" or the "regular" list. In any case, the AGIV imagery doesn't belong in the overlay list.

**Comment by bhousel** [comment]
[Found it here](https://github.com/osmlab/editor-layer-index/blob/9a84b2b9f193d1a9f4bb7fc327c899eb8bf0320a/sources/europe/BE_OrthoPhoto_Flanders_TMS.json#L5-L6).  It looks like "best" and "overlay" are both set for this source.

If I'm understanding, it sounds like the overlay property should be removed.  Overlay sources are supposed to be used for transparent raster tiles that sit on top of the base imagery layer.  (Like the TIGER shapefiles we use in the USA to find missing roads).

**Comment by sanderd17** [comment]
Heh, a mistake from my side then; thanks for fixing this.
