### ISSUE TITLE
MassGIS LIDAR Shaded Relief is just showing as black on OSM iD editor

### ISSUE THREAD

**Issue by kaspesla** [osmlab/editor-layer-index#1412]
I'm not sure this the right place to report, but as of the last few weeks the MassGIS LIDAR Shaded Relief layer is just showing as black on OSM iD editor.

**Comment by rbuffat** [comment]
Thanks for reporting! It looks like the URL has changed  from 
`https://tiles.arcgis.com/tiles/hGdibHYSPO59RG1h/arcgis/rest/services/Shaded_Relief_LiDAR/MapServer/tile/19/194309/159125`
to 
`https://tiles.arcgis.com/tiles/hGdibHYSPO59RG1h/arcgis/rest/services/LiDAR_ShadedRelief/MapServer/tile/15/12116/9872?blankTile=false`


@cicku @gdt 

Unfortunately, the server returns HTTP Code 200 (OK) with:

```
<html>

<body>
  <h2>Error</h2>
  
  <div class="restBody">
    <h3>Requested Service not available.</h3><br/>
    <b>Code: </b>404<br/><br/>
    
  </div>
</body>
</html>
```

🤦🤦🤦 Thus our watchdog script didn't detect the issue. I need to update the watchdog to actually test for an image and not just HTTP code 200...

**Comment by gdt** [comment]
MassGIS has changed their layer names and URLs around.    We in the MA OSM commmunity are figuring this out and I will submit a PR with a fixed URL fairly soon.

**Comment by gdt** [comment]
And @kaspesla  you could join talk-us-massachusetts@ where we tend to have MassGIS news.

**Comment by cicku** [comment]
Is it a temporary change or permanent? I have no idea what MassGIS is doing there. We can fix the URL but I want to make sure that they won't change again any time soon.

**Comment by gdt** [comment]
It is a permanent change, and associated with releasing a somewhat reprocessed layer from the raw data.  While I didn't expect this URL change, I don't see this as likely to be unstable in the future in the 1-year timeframe.  (5 years, everything is unstable.)

**Comment by cicku** [comment]
Fixed.

**Comment by gdt** [comment]
Great, thank you.
