### ISSUE TITLE
[Watchdog] Imagery "SDFE Surface Shadow Map (40 cm)": sources/europe/dk/SDFESurfaceShadowMap(40cm).geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1415]
Watchdog failed for 5 consecutive days for:
"SDFE Surface Shadow Map (40 cm)" -> [sources/europe/dk/SDFESurfaceShadowMap(40cm).geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/dk/SDFESurfaceShadowMap(40cm).geojson)

Reason:
Error: Layers 'dhm_overflade_skyggekort' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@rbuffat, @grischard

**Comment by sulfo** [comment]
Hi @rbuffat & @grischard.

Multiple of the SDFE resources has been updated with new login credentials. They can be found here: https://josm.openstreetmap.de/wiki/Maps/Denmark

I'm more than happy trying to update the resource (if I can figure it out 😄 )

Ref #1416 #1405
