### ISSUE TITLE
[Watchdog] Imagery "Ministerio de Agricultura, Ganadería y Pesca (WMS)": sources/south-america/ar/Ministry-of-Agriculture_wms.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1421]
Watchdog failed for 5 consecutive days for:
"Ministerio de Agricultura, Ganadería y Pesca (WMS)" -> [sources/south-america/ar/Ministry-of-Agriculture_wms.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/ar/Ministry-of-Agriculture_wms.geojson)

Reason:
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.
Error: Exception: Could not parse XML.

CC contributors to this imagery:
@Zalitoar

**Comment by Zalitoar** [comment]
Hi @rbuffat that service was moved or deleted. The ministry responsible of it didn't announced a replacement or a new URL. I could remove it from this index until further notice.

**Comment by rbuffat** [comment]
Imagery seems to work again.
