### ISSUE TITLE
[Watchdog] Imagery "Mesa County GIS Valleywide 2018": sources/north-america/us/co/MesaCountyValleywideImagery2018.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1427]
Watchdog failed for 5 consecutive days for:
"Mesa County GIS Valleywide 2018" -> [sources/north-america/us/co/MesaCountyValleywideImagery2018.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/co/MesaCountyValleywideImagery2018.geojson)

Reason:
Error: WMS -: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0 Error: Could not parse XML.
Error: WMS -: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?service=WMS&request=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_Color_2018/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.0.0 Error: Could not parse XML.

CC contributors to this imagery:
@Marc-marc-marc, @tsmock, @rbuffat, @grischard

**Comment by tsmock** [comment]
It looks like it is down on their website as well.

I really ought to look into building a custom tile server for it. Specifically, one for 2020 (the most current imagery) which is not in ELI since it is WMTS only.

**Comment by rbuffat** [comment]
@tsmock  Thanks for the information! The issue was generated by our imagery test script (I should definitely change the user that creates these issues!) The script should close the issue automatically when it would detect that the imagery is online again. I'm not sure how likely this is given.

I did a quick search and found the following image server, that seems to host a WMS service for 2020 imagery: https://mcgis.mesacounty.us/image/rest/services/Mosaic_Datasets/City_County_2020/ImageServer
https://mcgis.mesacounty.us/image/rest/services/Mosaic_Datasets

These ArcGIS server sometimes include a REST endpoint that can be used as WMS source. See https://github.com/osmlab/editor-layer-index/search?q=exportimage for examples.

**Comment by tsmock** [comment]
It does have an `exportimage` parameter for WMS usage.

Example: https://mcgis.mesacounty.us/image/rest/services/Mosaic_Datasets/City_County_2020/ImageServer/exportImage?f=image&bbox=707158.8192363052%2C4321403.386123106%2C723414.8517483702%2C4329379.0020743385&imageSR=102206&bboxSR=102206&size=1920%2C942

While the server they use technically has that feature, it something _I've_ been avoiding, since I don't know what additional resources are required for it. And since I'm not running the server, I've wanted to be careful in how badly their servers are hit.

And thus, I haven't made a PR for the 2020 imagery (see #734 ).
I really need to look into setting up a mapproxy server.

**Comment by rbuffat** [comment]
@tsmock the linked service is also exposed as WMS:

```
....
{
    "properties": {
        "name": "City_County_2020",
        "type": "wms",
        "url": "https://mcgis.mesacounty.us/image/services/Mosaic_Datasets/City_County_2020/ImageServer/WMSServer?LAYERS=0&STYLES=default&FORMAT=image/jpeg&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap",
        "description": "2020 Air Photo. Eagleview project between city and county GIS",
        "available_projections": [
            "CRS:84",
            "EPSG:3742",
            "EPSG:4326"
        ],
...

```

But the server does not state any access constraints/license information. Thus, if there are not some other places with this information we should contact them anyway to ask for this information.
