### ISSUE TITLE
[Watchdog] Imagery "Ruda Śląska: Orthophotomap (aerial image)": sources/europe/pl/RudalskaOrthophotomap(aerialimage).geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1429]
Watchdog failed for 5 consecutive days for:
"Ruda Śląska: Orthophotomap (aerial image)" -> [sources/europe/pl/RudalskaOrthophotomap(aerialimage).geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/pl/RudalskaOrthophotomap(aerialimage).geojson)

Reason:
Error: WMS -: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?SERVICE=WMS&REQUEST=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0 Error: Could not parse XML.
Error: WMS -: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?service=WMS&request=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?service=WMS&request=GetCapabilities&version=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?service=WMS&request=GetCapabilities&version=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?service=WMS&request=GetCapabilities&version=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://rudaslaska.geoportal2.pl/map/wmsorto/wms.php?service=WMS&request=GetCapabilities&version=1.0.0 Error: Could not parse XML.

CC contributors to this imagery:
@Asteliks, @rbuffat, @grischard

**Comment by rbuffat** [comment]
@Asteliks  would it possible for you to have a look at this issue?

**Comment by Vieja** [comment]
Checked the source, the orthophotomap layer is unavailable and will no longer be. I will create a PR that will remove the file from the repository and mention @Asteliks

**Comment by Asteliks** [comment]
I confirm that this service is no longer available
