### ISSUE TITLE
Bing maps does not contain a slippy map URL

### ISSUE THREAD

**Issue by pietervdvn** [osmlab/editor-layer-index#1441]
In the [Bing source file](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/world/Bing.geojson), the `url` field merely links to `bing.com/maps`.

As this is not a slippy map tile URL format, I'm wondering how to use this entry.

**Comment by tyrasd** [comment]
Bing uses a special protocol, which you have to implement manually. This is indicated by the `"type": "bing"` property here. You can find information about how to load bing tiles on the following Microsoft documentation pages: https://docs.microsoft.com/en-us/bingmaps/rest-services/directly-accessing-the-bing-maps-tiles, https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system, etc.

**Comment by tyrasd** [comment]
PS: You might also take a look at how other editors implement the Bing layer:

e.g. iD implements it in [`background_source.js`](https://github.com/openstreetmap/iD/blob/develop/modules/renderer/background_source.js#L263).

Note that you will also need an API key for your map editor. @mbrzakovic might be able to help with that??

**Comment by simonpoole** [comment]
> Note that you will also need an API key for your map editor. @mbrzakovic might be able to help with that??

Just in case it isn't clear, pls do not use one of the keys used by another editor.

**Comment by pietervdvn** [comment]
Allrights, thanks for clarifying!
