### ISSUE TITLE
Thunderforest layers

### ISSUE THREAD

**Issue by gravitystorm** [osmlab/editor-layer-index#145]
From #143 

> if you ever want your tiles added to the OSM editors please open an issue or pull request

I'm happy for any of my Thunderforest tile layers to be added. If mappers are finding them useful then that's great! I don't use any of them as background layers myself, so I don't know which ones would be best.

**Comment by bhousel** [comment]
Thanks!  We expose the [OpenCycleMap style](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/world/OpenCycleMap.json) already, though we fetch those tiles from `http://tile.opencyclemap.org/cycle/{zoom}/{x}/{y}.png`

I think [landscape](http://www.thunderforest.com/maps/landscape/) might be even more useful for editors than OpenCycleMap, so I'd like to support that one in iD instead.
`https://[abc].tile.thunderforest.com/landscape/{z}/{x}/{y}.png`

[The usage terms](http://www.thunderforest.com/terms/) look great, but I don't want to hit your tile servers with iD, Potlatch, Vespucci traffic unless you are ok with this.

**Comment by gravitystorm** [comment]
> We expose the OpenCycleMap style already, though we fetch those tiles from http://tile.opencyclemap.org/cycle/{zoom}/{x}/{y}.png

It's best update this to use the thunderforest URLs, since they have https support.

> so I'd like to support that one in iD instead.

Feel free to do both. I think the previous discussion focussed on elevation data but I don't know if some mappers like other things (e.g. route relations) to be obvious when mapping. Anyway, you're closer to the action here so go with your instinct.

>  you are ok with this.

Sure, more than happy. I already support a boat-load of traffic by having styles on the front page of www.osm.org so I know what I'm getting into :-)

**Comment by bhousel** [comment]
Sounds good, thanks!  I will update the OpenCycleMap url and add Landscape to the list too..
