### ISSUE TITLE
Preset for Maxar

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/editor-layer-index#1451]
Hi,

I'm not sure if this issue is a editor-layer-index issue or an id-tagging-schema issue :
in transifex, we have almost all the imageries (name and description) but not Maxar Premium Imagery : could you add it ?

Best regards

**Comment by davidhicks** [comment]
Maxar Premium is not freely licensed per requirements at https://github.com/osmlab/editor-layer-index/blob/gh-pages/FAQ.md#what-imagery-licenses-are-compatible-with-this-index

See Maxar's EULA for OpenStreetMap at https://wiki.openstreetmap.org/wiki/Maxar#Legal_permissions and MapBox's EULA at section 1.5 of https://www.mapbox.com/legal/service-terms for the very explicit permissions granted to trace Maxar and MapBox imagery (being largely Maxar imagery anyway) for OpenStreetMap use only.

OpenStreetMap's iD editor handles Maxar imagery in a special case per https://github.com/openstreetmap/iD/blob/HEAD/data/manual_imagery.json (obfuscated URL containing an API key unique to iD editor to try and prevent people misusing it).

JOSM handles Maxar imagery in a special case too per https://josm.openstreetmap.de/wiki/Maps/Worldwide#MaxarPremiumImagery and https://github.com/JOSM/josm/blob/HEAD/src/org/openstreetmap/josm/io/imagery/ApiKeyProvider.java where again there is an API key unique to JOSM that is obfuscated to try and prevent people misusing it.

You'll need to speak to Maxar and arrange licensing

**Comment by Mahabarata** [comment]
Hi,

this is not my asking : see this capture
![Capture d’écran 2022-03-12 125237](https://user-images.githubusercontent.com/3121119/158025094-63049ca7-ef0c-4f7a-be3d-111a16ed8ad9.png)

The first line is not in polish or english but in french because in transifex you add the original text so we may translate it.
Same thing for the 2d, 3rd, 4th, 6th, 7th, 8th... in fact all the lines are not the original ones but a translation.

Except the line 5 (Maxar Premium Imagery) : the text is the original because the text is not in transifex so impossible to translate it.

Same thing with the texts under the mouse :
* for the first line, we have a translation :
![Capture d’écran 2022-03-12 130732](https://user-images.githubusercontent.com/3121119/158025675-85c6c881-3655-46ef-a6ba-beb29ef2a87f.png)

* same thing for the line 4 :
![Capture d’écran 2022-03-12 130754](https://user-images.githubusercontent.com/3121119/158025680-5263082c-9852-4947-a6f8-4a69c1a108de.png)

* same thing for the other lines

* but not for Maxar, the test is in english, not in transifex so impossible to translate it.
![Capture d’écran 2022-03-12 130848](https://user-images.githubusercontent.com/3121119/158025689-b7f26c8f-4187-42b2-a1dd-c342e31a8c5c.png)

My asking is to be able to translate the 3 texts about Maxar (name, description and attribution) like for all other lines.

Best regards

**Comment by andrewharvey** [comment]
Maxar imagery isn't in this index, it's hard coded into iD, therefore the translation should happen within iD.

**Comment by Mahabarata** [comment]
??? Sorry I don't understand.
I know the Maxar imagery is not in this index, my issue is to ask to add it !

**Comment by grischard** [comment]
You should open an issue in https://github.com/openstreetmap/iD/

**Comment by Mahabarata** [comment]
Ok, thanks
