### ISSUE TITLE
Default layer for Lesotho is unavailable in Lesotho

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/editor-layer-index#1471]
https://www.openstreetmap.org/edit?editor=id#map=16/-29.6480/28.0250

![screen](https://user-images.githubusercontent.com/899988/155304098-1586a761-9546-41ad-9c77-39a64b207d4f.png)

(Likely enclave !!fun!!)

**Comment by cicku** [comment]
Looks like port 443 is not open.

**Comment by cicku** [comment]
Oh ignore my previous comment, I know the issue now.

![image](https://user-images.githubusercontent.com/686438/192111813-7d250639-5a21-4baf-b74c-ad9b8e7bc5ed.png)

**Comment by matkoniecz** [comment]
So 

> (Likely enclave !!fun!!)

guess was right :)
