### ISSUE TITLE
Texas Orthophotos

### ISSUE THREAD

**Issue by talllguy** [osmlab/editor-layer-index#149]
This WMS source comes from @mvexel on the OSMUS Slack. Image service URL is http://r.tnris.org/arcgis/rest/services/TOP/TOP_2015_50CM_NC/ImageServer/

**Comment by mvexel** [comment]
I just got this info:

> The url for the tiles (for the main texas layer) are 
> 
> https://txgi.tnris.org/tiles/texas/{z}/{x}/{y} 

Can we work with this?

**Comment by talllguy** [comment]
Not sure if this is relevant, but that URL asks for a password.
![image](https://cloud.githubusercontent.com/assets/1827881/18726414/52364404-8012-11e6-8c6f-10f10832c531.png)

**Comment by talllguy** [comment]
@mvexel I think this would actually work!

http://r.tnris.org/arcgis/rest/services/TOP

**Comment by talllguy** [comment]
All kinds of data on here, here's WMS for statewide NAIP data. http://r.tnris.org/arcgis/services/NAIP/NAIP_2014_1M_NC/ImageServer/WMSServer?request=GetCapabilities&service=WMS

CC0

**Comment by mvexel** [comment]
More! 

> These are the WMS/WMTS versions, but you can strip it down like the example below.
> WMS: https://txgi.tnris.org/login/path/ecology-fiona-poem-romeo/wms
> WMTS: https://txgi.tnris.org/login/path/ecology-fiona-poem-romeo/wmts/1.0.0/WMTSCapabilities.xml

**Comment by hakuchi** [comment]
Here is the link to usein iD, Potlatch2 and Josm:
iD:
http://whoots.mapwarper.net:80/tms/{z}/{x}/{y}/0/http://r.tnris.org/arcgis/services/TOP/TOP_2015_50CM_NC/ImageServer/WMSServer
Potlatch:
http://whoots.mapwarper.net:80/tms/$z/$x/$y/0/http://r.tnris.org/arcgis/services/TOP/TOP_2015_50CM_NC/ImageServer/WMSServer
Josm:
http://r.tnris.org/arcgis/services/TOP/TOP_2015_50CM_NC/ImageServer/WMSServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

**Comment by simon04** [comment]
Adding `texas` tiles from https://txgi.tnris.org/login/path/ecology-fiona-poem-romeo/wmts/1.0.0/WMTSCapabilities.xml since they provide full coverage w/o having to differentiate between different years …

**Comment by mvexel** [comment]
Hey all -- I got in touch with TNRIS because I have a suspicion that they don't have the proper license to redistribute this layer to us. I asked them to comment here. If they get back to me over email I'll update this thread.

**Comment by grischard** [comment]
@mvexel did you ever hear back from TNRIS about the license to redistribute their ortho layer? Thanks!

**Comment by mvexel** [comment]
If this is what I I seem to remember it is, it's imagery licensed from Google for TX internal purposes and we are not allowed to use it.

**Comment by grischard** [comment]
Thanks!

**Comment by tyrasd** [comment]
The service seems to be down at the moment (reported in https://www.openstreetmap.org/user/JavaCoyote/diary/43867): Requests like [this one](https://txgi.tnris.org/login/path/ecology-fiona-poem-romeo/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=texas&STYLE=&FORMAT=image/png&tileMatrixSet=0to20&tileMatrix=0to20:14&tileRow=6790&tileCol=3710) just return a 403 "Forbidden" error message.

Maybe just a temporary downtime? Or does the service now require login or some kind of access key?

**Comment by richlv** [comment]
Still returning 403.

The one listed at https://tnris.org/data-catalog/entry/texas-orthoimagery-program-top-2015-50cm-nc-cir/ works currently, and the licence seems to be usable (assuming the publisher had the rights).

**Comment by don-vip** [comment]
Link is dead (see #597). I think we can use the one listed [there](https://tnris.org/data-catalog/entry/texas-orthoimagery-program-top-2015-50cm-nc-cir/) as it is explicitly licensed "Public Domain (Creative Commons CC0)"

**Comment by MrSpoon** [comment]
Updated links for [Texas Orthoimagery Program](https://data.tnris.org/collection/b7e5b638-99f0-4676-9411-c88d06d49943) ([WMS](https://webservices.tnris.org/arcgis/services/TOP/TOP15_NC_CIR_50cm/ImageServer/WMSServer)) This is often the best imagery available for rural Texas.

**Comment by rbuffat** [comment]
@MrSpoon @talllguy @tyrasd  @richlv  In https://github.com/osmlab/editor-layer-index/pull/920 and https://github.com/osmlab/editor-layer-index/pull/921, orthophotos for Texas were added and the existing ones were fixed. Does this resolve this issue?
