### ISSUE TITLE
New Layer Request: USGS 3D Elevation Program

### ISSUE THREAD

**Issue by OptikalCrow** [osmlab/editor-layer-index#1490]
These two layers appear to be the most useful of the USGS 3D Elevation Program WMS services. One is a general hillshade which is useful for determining stream flowpaths, track roads through forested areas, and in some areas foot trails. The other is a dynamic contour lines layer useful as an overlay to assess land gradients at finer detail than scanned USGS topographic maps.

[JOSM includes the hillshade layer as an extra option](https://josm.openstreetmap.de/wiki/Maps/USA%20Country#USGS3DElevationProgram) not found in this layer index, so there is some precedent for adding it. It also includes a contour layer from the USFS, although the 3DEP should supercede this layer as the USFS availabilty is only found in USFS-administered areas. 

## URL of the imagery
https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer
layers: 
3DEPElevation:Hillshade Multidirectional
3DEPElevation:Contour 25

## Two letter country code
US, CA, MX

## Desired layer name
USGS 3D Elevation Program - Hillshade
USGS 3D Elevation Program - Contour Lines

## License
[Public Domain as listed by [U.S. Code, Title 43 – Public Lands, Chapter 46: GEOSPATIAL DATA](https://uscode.house.gov/view.xhtml?hl=false&edition=2019&path=%2Fprelim%40title43%2Fchapter46&req=granuleid%3AUSC-2019-title43-chapter46&num=0&saved=L3ByZWxpbUB0aXRsZTQzL2NoYXB0ZXI0Ng%3D%3D%7CZ3JhbnVsZWlkOlVTQy1wcmVsaW0tdGl0bGU0My1jaGFwdGVyNDY%3D%7C%7C%7C0%7Cfalse%7Cprelim)](https://uscode.house.gov/view.xhtml?hl=false&edition=2019&path=%2Fprelim%40title43%2Fchapter46&req=granuleid%3AUSC-2019-title43-chapter46&num=0&saved=L3ByZWxpbUB0aXRsZTQzL2NoYXB0ZXI0Ng%3D%3D%7CZ3JhbnVsZWlkOlVTQy1wcmVsaW0tdGl0bGU0My1jaGFwdGVyNDY%3D%7C%7C%7C0%7Cfalse%7Cprelim)

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
U.S. Geological Survey

## Privacy policy (URL)
not sure

## Icon
https://wim.usgs.gov/styleguide/assets/branding/usgs/USGS_Green_Banneronly_fullres.png

## Bounding polygon
USA including Alaska, Hawaii, Puerto Rico
Mexico
Canada

**Comment by cicku** [comment]
Thank you for mentioning this. I am already aware of the data here.

**Comment by petercooperjr** [comment]
I'm not sure if this is related enough or should be a separate ticket, but I would have expected the current National Map USPS Topographic maps to be in ELI somewhere (rather than just what look to be scanned paper maps).

Map Server: https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer

I found it on the list of USGS Services: https://apps.nationalmap.gov/services/

Copyright info: https://www.usgs.gov/faqs/are-usgs-topographic-maps-copyrighted

I find it works fine in iD for me when I put a "Custom" background of `https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{zoom}/{y}/{x}`
But I don't know if there's some nuance here I'm unaware of which is a reason it isn't available already as a background in iD.

Similarly, a bit more on topic for this, I can put in a custom background of
`https://basemap.nationalmap.gov/arcgis/rest/services/USGSShadedReliefOnly/MapServer/tile/{zoom}/{y}/{x}`
To see the shaded relief map that I think this issue is asking for.

I guess I'm just trying to understand why the USGS Imagery is in the list but the other USGS tile services aren't, and if there are any roadblocks to adding them. Thanks.

**Comment by endolith** [comment]
This is much better than satellite photos for identifying cliff edges (useful for rock climbing and hiking). Please add it!

https://community.openstreetmap.org/t/is-it-ok-to-adjust-cliffs-to-match-usgs-3dep/98910

https://wiki.openstreetmap.org/wiki/USGS_3D_Elevation_Program#Using_the_USGS_3DEP_Digital_Elevation_Model

@petercooperjr 

> Similarly, a bit more on topic for this, I can put in a custom background of
> https://basemap.nationalmap.gov/arcgis/rest/services/USGSShadedReliefOnly/MapServer/tile/{zoom}/{y}/{x}
> To see the shaded relief map that I think this issue is asking for.

That URL doesn't seem to provide the best resolution available?

![image](https://github.com/osmlab/editor-layer-index/assets/58611/f1afae8e-64f6-49fc-872b-6c688482a095)


This URL:

`https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WMSServer?FORMAT=image/png32&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=3DEPElevation:Hillshade%20Multidirectional&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}`

produces this imagery:

![image](https://github.com/osmlab/editor-layer-index/assets/58611/2ace4694-d2b6-452d-9137-3e4c1f5c5e72)


(though it sometimes doesn't load and the underlay is just black)

**Comment by cicku** [comment]
I've added the Hillshade Gray layer as the white background is not very clear sometimes, let me know if you need anything else.

**Comment by endolith** [comment]
I think the multidirectional hillshade is better than the regular if you're only adding one

**Comment by endolith** [comment]
Or maybe the multidirectional is misleading?

![2023-07-14 16_56_59- General  OpenStreetMap — Mozilla Firefox](https://github.com/osmlab/editor-layer-index/assets/58611/c58625b6-d208-4eb6-88dc-a4aea9088020)

Unidirectional shows its more of a ridge and the cliff top should be lower:

![2023-07-14 16_57_10- General  OpenStreetMap — Mozilla Firefox](https://github.com/osmlab/editor-layer-index/assets/58611/827a5780-6879-4fc5-aad5-6da2e8a61844)

**Comment by endolith** [comment]
For reference here are the different options:

`Aspect Degrees`:
![YYYY Aspect Degrees 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/0c71339b-bc82-4101-bdaf-34daee0038d7)

`Aspect Map`:
![YYYY Aspect Map 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/267fea9f-62f6-48b5-b501-fe17c420af02)

`Hillshade Elevation Tinted`:
![YYYY Hillshade Elevation Tinted 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/0a8e75b4-8df5-4c3d-a5e7-7381328d6160)

`Hillshade Gray`:
![YYYY Hillshade Gray 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/3ade72ac-649a-47c0-bc84-f8821197f015)

`GreyHillshade_elevationFill` (identical to above?):
![YYYY GreyHillshade_elevationFill 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/d1ea8d43-6010-4b87-9020-acb33f4f285f)

`Hillshade Multidirectional` (shows details in shadow a little better):
![YYYY Hillshade Multidirectional 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/17bda3f4-011d-454e-90f3-f452618c0268)

`Slope Degrees`:
![YYYY Slope Degrees 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/a6763e94-75bc-4a39-bf95-ce27da3d43a4)

`Slope Map`:
![YYYY Slope Map 2024-05-26](https://github.com/osmlab/editor-layer-index/assets/58611/308da02b-de24-455c-ab86-9497ef7d4a58)
