### ISSUE TITLE
End support for Maryland Transportation Basemap

### ISSUE THREAD

**Issue by talllguy** [osmlab/editor-layer-index#1493]
Wearing several hats, here... my organization, MDOT State Highway Administration, is no longer maintaining or updating our Maryland Transportation Basemap, which is part of this index (see #155). **Please remove it from the OSM Editor Index** as it is now woefully out of date and will soon be removed. 

[The layer is here in the index](https://github.com/osmlab/editor-layer-index/blob/6c1d2877943ef57997c9d85752eb75c3bc2edda0/sources/north-america/us/md/MD_TransportationBasemap.geojson).

[The map service is posted here](https://geodata.md.gov/imap/rest/services/Transportation/MD_ColorBasemap/MapServer), but it will soon be taken offline. That will cause the layer to fail here. Therefore, I wanted to prevent that by letting the team know here, first.

Thanks!

**Comment by cicku** [comment]
Done.
