### ISSUE TITLE
North Carolina OneMap Latest Orthoimagery broken

### ISSUE THREAD

**Issue by scottAnselmo** [osmlab/editor-layer-index#1507]
**Problem:** 

Both the _NC OneMap Latest Orthoimagery (Infrared)_ and _NC OneMap Latest Orthoimagery (Natural)_ do not return imagery.

**How to Replicate:**

1. Open up iD where the imagery is available such as: https://www.openstreetmap.org/edit?editor=id&way=118493442#map=20/35.52652/-82.95962
2. Select both imagery layers
3. Validate that black tiles are returned for both layers

**Other Notes:**

The government service does not seem to be working correctly: https://services.nconemap.gov/secure/rest/services/Imagery/Orthoimagery_CIR/ImageServer/exportImage?f=html&format=png&imageSR=3857&bboxSR=3857&bbox=-9235045.31910118,4235719.703319281,-9235007.100587044,4235757.921833418&size=256,256&foo=EPSG:3857

Previous people that seemed to have [worked on getting this into iD](https://github.com/osmlab/editor-layer-index/search?q=services.nconemap.gov) and thus might have connections to the NC government to notify them of government service issues are @cicku and @rbuffat

**Comment by cicku** [comment]
Hi,

Thank you for the issue.

It was already fixed via https://github.com/osmlab/editor-layer-index/commit/d16fb614303b3eae2f1cdaaeec07a54bfa9ffddd. But iD has not released a new version for a while so the wrong URL is still there.

**Comment by rbuffat** [comment]
CC @tyrasd
