### ISSUE TITLE
NDOP and USGS National Map

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#151]
NDOP supports several statewide aerial photography and orthoimagery programs.
This page has a list of several statewide programs
http://www.ndop.gov/data.html

USGS National Map looks interesting too:
http://nationalmap.gov/ortho.html#data

**Comment by bhousel** [comment]
Update on USGS National Map:  https://www.usgs.gov/news/usgs-national-map-orthoimagery-map-services-transition-and-other-map-service-changes

See discussion here:
https://lists.openstreetmap.org/pipermail/talk-us/2016-December/016887.html

I think this means we need to change something in the imagery index, but I really can't follow the thread.
@iandees can you open an issue for what needs to change?

**Comment by iandees** [comment]
My understanding is that the "large scale imagery" layer as we know it is gone and won't be replaced. I'm trying to find someone who can give me more information.

**Comment by iandees** [comment]
It looks like [the USGS National Map imagery-only layer](https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer) has pre-tiled NAIP and higher-res imagery down to z19. The server doesn't render anything with better resolution even when it's clear that the imagery supports it (I was looking in Chicago, for example). The description on that layer says to use [the USGSImageOnlyLarge](http://services.nationalmap.gov/arcgis/rest/services/USGSImageOnlyLarge/MapServer) layer for requests beyond z19, but I can't find anywhere in the US where that service gives back better imagery.

So the confusion for me is what happened to the higher-res imagery. I wouldn't have set the USGS Large Scale imagery layer to go to zoom 22 without a reason 😄 .

**Comment by bhousel** [comment]
Yeah I'm kind of confused too.  NDOP seems to be gone now, but my remembering of it was that:
* All the individual states are supposed to have their own orthoimagery programs
* There was some minimum resolution that they were supposed to support by some date
* NAIP was somewhere around 5m resolution (which is not great for tracing) but getting better (1m now?)
* Some of the states already well exceed this minimum (e.g. NJ, MD, which we've added this index)
* USGS was going to merge all the state imagery into a single national map (is that what `NAIP-Plus` layer is?)

I might be misremembering some of it..

**Comment by iandees** [comment]
Hi everyone listening to this ticket: I discovered that this layer will still work, it's just that the server I'm caching from starts at z16. I've adjusted the tile server so that it should return a 404 if you request a tile < z16 instead of proxying the white images they send us.

So basically: if you're zoomed in a bunch you can continue using the USGS Large Scale imagery and if you're zoomed out use the USGS NAIP imagery.

**Comment by gregcrago** [comment]
Still getting BLURRY and SHARP Topo map in ID Editor near Spencer, NY, see attached pic
![topo still blurry and sharp spencer ny](https://cloud.githubusercontent.com/assets/7635234/23171029/31a47d16-f806-11e6-8800-639505e850cd.JPG)

**Comment by iandees** [comment]
The topo maps are still gone and not published anywhere else for us to query.

**Comment by iandees** [comment]
I just switched the OSM US imagery source to use caltopos.com's scanned topographic maps. They should have complete coverage and are all pre-rendered so it should be very quick.

This change probably won't get picked up until @bhousel releases a new version of iD.

**Comment by gregcrago** [comment]
Found a BLURRY Topo map at N41° 30.777' W84° 08.901' using ID Editor 2.1.3
![topo still blurry on id editor 2 1 3](https://cloud.githubusercontent.com/assets/7635234/24767107/5aebc3c0-1aaa-11e7-8c28-f882789c1e9e.JPG)

**Comment by bhousel** [comment]
Oh I missed this back in February - I guess they are officially sunsetting NDOP.  We'll need to collect imagery for this index state-by-state after all.  😭 

>The USGS announces the sunset of National Map High Resolution Orthoimagery Data and Service
The National Geospatial Program (NGP) is planning to retire the High Resolution Orthoimagery (HRO) portion of imagery data and services by October 1, 2017.

https://www.usgs.gov/news/imagery-services-update-national-map

**Comment by iandees** [comment]
Gah, curse you USGS!

I have plans to work on an "OpenAddresses for aerial imagery" at some point this year… Perhaps that could replace this.

**Comment by grischard** [comment]
Closing this for now then :/
