### ISSUE TITLE
NL's pdok layer has incorrect region

### ISSUE THREAD

**Issue by thibaultmol** [osmlab/editor-layer-index#1518]
The imagery in the netherland 'pdok' seems to have an area of Netherlands with a buffer region around it. Maybe in the past they used to take imagery outside of the Netherlands, but atleast the most recent one seems to only be the Netherlands.
So the boundary box should be modified to not go over other countries like Belgium anyway, because the imagery doesn't show anything here.
![image](https://user-images.githubusercontent.com/1010226/170453667-214277a7-a4d9-440d-a827-8db1db2e4819.png)

**Comment by AllroadsNL** [comment]
@thibaultmol
After a iD editor update two days ago, 
Is it now better?

**Comment by thibaultmol** [comment]
Yep, is fixed. :+1:
