### ISSUE TITLE
Layer “BJ / Benin: Cotonou Pleiade 2016” should be removed

### ISSUE THREAD

**Issue by sommerluk** [osmlab/editor-layer-index#1522]
Layer “BJ / Benin: Cotonou Pleiade 2016” should be removed.

It has been added in #157 a couple of years ago. At this time, it was the only available imagery of this region. Therefore, it is marked as “best image”.

Currently, the image is not available any more. It seems that the whole imagery server is down. I did not get an answer from @stlejer-morvrini if this is a temporary or permanent issue, neither [on GitHub](https://github.com/osmlab/editor-layer-index/issues/157#issuecomment-1128907376) nor on e-mail. Given that even the whole subdomain geoxxx.agrocampus-ouest.fr does not respond, I suppose it’s a permanent issue.

Today, Bing, Esri, Mapbox and Maxar provide imagery that is of higher quality and much more up-to-date than “Cotonou Pleiade 2016”. So removing it would make the user experience better.

**Comment by cicku** [comment]
Will remove later.

**Comment by sommerluk** [comment]
Any news on this?

Because of this image no longer available, and because it's marked as "best" image, iD users get currently a black background instead of satellite imagery in Cotonou.

**Comment by sommerluk** [comment]
Thanks a lot!
