### ISSUE TITLE
South Tyrol Orthofoto error

### ISSUE THREAD

**Issue by GoedendagMC** [osmlab/editor-layer-index#1566]
When trying to edit, for example https://www.openstreetmap.org/edit#map=17/46.84214/12.23228 and selecting any of the "South Tyrol" options, the screen goes black. https://osmlab.github.io/editor-layer-index/ Here one can look up the existing URLs. http://daten.buergernetz.bz.it/de/organization/provbz?q=orthofoto&sort=score+desc%2C+metadata_modified+desc Here one can look up what the correct URLs should be, it appears there are always 2 options but one of them (the one used by OSM) broke. Example for 2020 Orthofoto: http://daten.buergernetz.bz.it/de/dataset/ortofoto-20201 which leads to http://geocatalogo.retecivica.bz.it/geokatalog/#!home&layer=p_bz%3AOrthoimagery%3AAerial-2020-RGB as the first option, where the second option (https://geoservices.buergernetz.bz.it/mapproxy/p_bz-Orthoimagery/ows?service=WCS&version=1.1.0) broke for OSM.

**Comment by tyrasd** [comment]
This one should already have been "fixed" with e7998818e1f77b3d127f17928cfb632b22c2b043. Can you perhaps double-check whether the new URLs work as expected for you?

Unfortunately, the above mentioned fix has not yet been rolled out in form of a released "stable" version of iD yet.

**Comment by GoedendagMC** [comment]
> Can you perhaps double-check whether the new URLs work as expected for you?

It worked! Thanks.
