### ISSUE TITLE
Add satellite image of Cotonou (Benin)

### ISSUE THREAD

**Issue by sommerluk** [osmlab/editor-layer-index#157]
Recently, there was a crowdfounding campain to buy satelite imagery for Cotonou (Benin) for the usage in OSM: https://fr.ulule.com/imagerie-cotonou/ The crowdfounding compain was successful. They include images of Cotonou and a smaller part in Grand&nbsp;Popo. This image is available at wmts:http://geoxxx.agrocampus-ouest.fr/owsifl/gwc/service/wmts?SERVICE=WMTS&REQUEST=GetCapabilities with the layer name Benin:cotonou_pleiade_2016 The image was bought and is provided especially for use in OSM. See also http://taches.francophonelibre.org/project/6

This satelite image is really important for OSM in Benin, because Cotonou is the biggest city of this country and Bing and Mapbox do not have a good resolution for Cotonou (only landsat quality). So it would be really great to have this image available in the OSM editors.

**Comment by sommerluk** [comment]
Cross-reference: Data from inclusion in JOSM (URL, shape…):
https://josm.openstreetmap.de/wiki/Maps/Benin

**Comment by bhousel** [comment]
Can you provide the license for this source?  Would love to get this added to the OSM editors.

**Comment by sommerluk** [comment]
In e-mail exchange with the organizator, he told me that a link to http://taches.francophonelibre.org/project/6 would be enough.

**Comment by sommerluk** [comment]
cc @stlejer-morvrini

**Comment by bhousel** [comment]
> In e-mail exchange with the organizator, he told me that a link to http://taches.francophonelibre.org/project/6 would be enough.

We're still waiting for a link to an actual imagery license.

**Comment by sommerluk** [comment]
In recent e-mail exchange with the organizers, they told me that they will provide the license as meta data. However, I do not know the tecnical details and not the time frame. Should I close this issue in the meantime and reopen once the license is available?

**Comment by sommerluk** [comment]
Finally, permission is available here:

http://geoxxx.agrocampus-ouest.fr/geonetwork/apps/georchestra/?uuid=85a6d684-3350-4166-815f-3e0b93a038f7

**Comment by bhousel** [comment]
Thanks @sommerluk looks like it is CC-BY-SA?  @pnorman, @iandees  does this look ok?

> Contraintes légales
Contraintes d'accès:  Licence: Restriction induite par l’existence d’une licence
Contraintes d'utilisation:  Licence: Restriction induite par l’existence d’une licence
Autres contraintes: Licence Airbus Defence and Space
Diffusion libre des flux OGC par OSM Benin, Les libres Géographes (cc-by-sa)

**Comment by iandees** [comment]
It seems OK to me. SA would apply to the images, but maybe not the extracted data?

**Comment by stlejer-morvrini** [comment]
Hi Ian,

What do you mean by "extracted data"?

Rod

On 01/07/16 17:16, Ian Dees wrote:
> It seems OK to me. SA would apply to the images, but maybe not the
> extracted data?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/osmlab/editor-layer-index/issues/157#issuecomment-229973457>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACj974vvgtln8GH08__sMe1jGuPLO1TMks5qRS84gaJpZM4Im3cx>.
> 


-- 
Rod Béra,  MCF Géomatique                /   Lecturer, Geomatics
           et SIG pour l'Environnement  /    and Environmental GIS
Agrocampus-Ouest|65 r.Saint-Brieuc|CS84215|35042 Rennes cedex|France
+33 (0) 223 48 5553 - roderic.bera@agrocampus-ouest.fr

**Comment by iandees** [comment]
I mean that data traced or otherwise extracted from the imagery ("derived")
might have different expectations. I don't know, just bringing it up.

**Comment by stlejer-morvrini** [comment]
On 04/07/16 12:01, Ian Dees wrote:
> I mean that data traced or otherwise extracted from the imagery ("derived")
> might have different expectations. I don't know, just bringing it up.

My understanding:

Tracing data using this imagery is possible (it's the reason we bought it).
Deriving (processing) data from this imagery is possible (e.g. process
automated classification).
copying imagery (through download) is possible as long as the original
licenses apply. (e.g. you can't resell your copy, but you can distribute
it for free).

Regards,

Rod




> 
> On Mon, Jul 4, 2016, 10:15 Rod Béra <notifications@github.com> wrote:
> 
>> Hi Ian,
>>
>> What do you mean by "extracted data"?
>>
>> Rod
>>
>> On 01/07/16 17:16, Ian Dees wrote:
>> > It seems OK to me. SA would apply to the images, but maybe not the
>> > extracted data?
>> >
>> > —
>> > You are receiving this because you were mentioned.
>> > Reply to this email directly, view it on GitHub
>> > <
>>
> https://github.com/osmlab/editor-layer-index/issues/157#issuecomment-229973457
>> >,
>> > or mute the thread
>> > <
>>
> https://github.com/notifications/unsubscribe/ACj974vvgtln8GH08__sMe1jGuPLO1TMks5qRS84gaJpZM4Im3cx
>> >.
>> >
>>
>>
>> --
>> Rod Béra, MCF Géomatique / Lecturer, Geomatics
>> et SIG pour l'Environnement / and Environmental GIS
>> Agrocampus-Ouest|65 r.Saint-Brieuc|CS84215|35042 Rennes cedex|France
>> +33 (0) 223 48 5553 - roderic.bera@agrocampus-ouest.fr
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>>
> <https://github.com/osmlab/editor-layer-index/issues/157#issuecomment-230231732>,
>> or mute the thread
>>
> <https://github.com/notifications/unsubscribe/AAP90EjeoZjPrGbK1QVJ7rk-RpbOzZgSks5qSMEzgaJpZM4Im3cx>
>> .
>>
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/osmlab/editor-layer-index/issues/157#issuecomment-230253928>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACj970QK5FMXcrvCnQ_qpL-KOZCMAhRRks5qSNoUgaJpZM4Im3cx>.
> 


-- 
Rod Béra,  MCF Géomatique                /   Lecturer, Geomatics
           et SIG pour l'Environnement  /    and Environmental GIS
Agrocampus-Ouest|65 r.Saint-Brieuc|CS84215|35042 Rennes cedex|France
+33 (0) 223 48 5553 - roderic.bera@agrocampus-ouest.fr

**Comment by sommerluk** [comment]
Is the shape from the JOSM wiki okay or do you need another format for the shape?

**Comment by sommerluk** [comment]
Is there anything else we can do about?

**Comment by simonpoole** [comment]
@sommerluk you need to create a PR containing the file that should be added, see https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md

**Comment by sommerluk** [comment]
Wow, now it’s getting complicated …

- “type” should be one of "tms", "wms", "bing", "scanex". But the image source is WMTS. What to do about?
- URL: Is wmts:http://geoxxx.agrocampus-ouest.fr/owsifl/gwc/service/wmts?SERVICE=WMTS&REQUEST=GetCapabilities the correct form?
- Is there a possibility to pre-select the correct WMTS layer? It is: Benin:cotonou_pleiade_2016
- "id": "A unique identifier for the source; used in imagery_used changeset tag". I do not understand how to use this.
- After reading CONTRIBUTING.md I still do not fully understand the usage of polygons and bbox.
    - bbox is supposed to be the bounding box for all polygons together, right?
    - Why are the polygons called “test polygons”. Do they exist only for testing, or will they be really used?
    - The imagery covers Cotonou and Grand Popo. So I would make 2 polygons, right?
    - I would like to mark this imagery as the best at its place. That’s also correct for 98% of its surface. But in the Cotonou part there is a hole in the image (covering only water/wetland of a lake). I suppose this doesn’t matter much …

**Comment by sommerluk** [comment]
Thanks a lot!

I’ve tested the TMS URL as coustom URL in iD and it works great!

However, neither at http://openstreetmap.org nor at https://openstreetmap.us/iD/master/ it is currently available in the layer menu when working at the Cotonou region…

**Comment by simon04** [comment]
For iD, the imagery layers are updated manually from time to time, see https://github.com/openstreetmap/iD/commits/master/data/imagery.json

**Comment by sommerluk** [comment]
Apparently, this imagery is no longer available. It seems that the whole service at http://geoxxx.agrocampus-ouest.fr does not respond any more.

@stlejer-morvrini Do you know if this is a temporary or a permanent issue?
