### ISSUE TITLE
sources in iD but not index

### ISSUE THREAD

**Issue by jfirebaugh** [osmlab/editor-layer-index#16]
These need to be cross-checked against current P2/JOSM lists:

* [ ] Port au Prince - GeoEye Jan 2010 (http://gravitystorm.dev.openstreetmap.org/imagery/haiti/{z}/{x}/{y}.png)
* [x] Haiti - IOM Drone Imagery, 2012-13 (http://wms.openstreetmap.fr/tms/1.0.0/iomhaiti/{zoom}/{x}/{y})
* [ ] NAIP (http://cube.telascience.org/tilecache/tilecache.py/NAIP_ALL/{z}/{x}/{y}.png)
* [ ] Austria - geoimage.at (http://geoimage.openstreetmap.at/4d80de696cd562a63ce463a58a61488d/{z}/{x}/{y}.jpg)
* [ ] Russia - Kosmosnimki.ru IRS Satellite (http://irs.gis-lab.info/?layers=irs&request=GetTile&z={z}&x={x}&y={y})
* [ ] Belarus - Kosmosnimki.ru SPOT4 Satellite (http://irs.gis-lab.info/?layers=spot&request=GetTile&z={z}&x={x}&y={y})
* [ ] Switzerland - Canton Solothurn - SOGIS 2007 (http://mapproxy.sosm.ch:8080/tiles/sogis2007/EPSG900913/{z}/{x}/{y}.png?origin=nw)
* [ ] Poland - Media-Lab fleet GPS masstracks (http://masstracks.media-lab.com.pl/{z}/{x}/{y}.png)

**Comment by bhousel** [comment]
closing as stale
