### ISSUE TITLE
[Watchdog] Imagery "Gothenburg Hillshade": sources/europe/se/gothenburg_dtm.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1625]
Watchdog failed for 5 consecutive days for:
"Gothenburg Hillshade" -> [sources/europe/se/gothenburg_dtm.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/se/gothenburg_dtm.geojson)

Reason:
Error: Layer 'terranglutning' does not support style 'hojdmodell-v2:terranglutning'

CC contributors to this imagery:
@rbuffat

**Comment by cicku** [comment]
False positive.
