### ISSUE TITLE
Delaware 2012 Orthophotography

### ISSUE THREAD

**Issue by talllguy** [osmlab/editor-layer-index#165]
> This data set consists of 0.3-meter pixel resolution (approximately 1-foot), 4-band true color and near infrared (R, G, B, IR) orthoimages covering New Castle, Kent and Sussex Counties in Delaware.

Hi-res! :grinning: 

[WMTS](https://firstmap.delaware.gov/arcgis/rest/services/DE_Imagery/DE_Imagery_2012/ImageServer/WMTS/1.0.0/WMTSCapabilities.xml)
[WMS](https://firstmap.delaware.gov/arcgis/services/DE_Imagery/DE_Imagery_2012/ImageServer/WMSServer?request=GetCapabilities&service=WMS)
[REST](https://firstmap.delaware.gov/arcgis/rest/services/DE_Imagery/DE_Imagery_2012/ImageServer)

**Comment by Klumbumbus** [comment]
Is it really allowed to trace from this imagery in osm?
at https://firstmap.delaware.gov/arcgis/rest/services/DE_Imagery/DE_Imagery_2012/ImageServer I see 
> Copyright Text: Digital Aerial Solutions, LLC 

and at https://firstmap.delaware.gov/pdfs/public/DEImageryMetadata.pdf (page 15)

> Credit
Digital Aerial Solutions, LLC
Usage
Public Domain Information with citation of the U.S. Geological Survey for products derived from these data.

**Comment by bhousel** [comment]
Public Domain should be ok, but we should link to the firstmap usage page with `license_url` and add some attribution text.

**Comment by Klumbumbus** [comment]
Do they really mean "Public Domain"?
"with citation of the U.S. Geological Survey for products derived from these data." contradicts with it.

**Comment by talllguy** [comment]
[Deleware copyright law is hazy](http://copyright.lib.harvard.edu/states/delaware/) but the Usage declaration in the metadata is clear. Use of U.S. Geological Survey (USGS) products are allowable because [works of USGS are public domain](https://www2.usgs.gov/laws/info_policies.html) as are any works of the US Federal Government:

> Copyright protection under this title is not available for any work of the United States Government, but the United States Government is not precluded from receiving and holding copyrights transferred to it by assignment, bequest, or otherwise.
> (Pub. L. 94–553, title I, § 101, Oct. 19, 1976, 90 Stat. 2546.)
> [source](https://www.law.cornell.edu/uscode/text/17/105#)

**Comment by Klumbumbus** [comment]
seems it can be closed again.
