### ISSUE TITLE
What licenses are appropriate for contributed imagery?

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#166]
It would be great to have a section in README or CONTRIBUTING about what we require in regards to licensing of the imagery.

**Comment by bhousel** [comment]
I should also add that the text [on the osm wiki](http://wiki.openstreetmap.org/wiki/Legal_FAQ#2._Contributing) about tracing from imagery seems outdated ("a very small amount of imagery... negotiated by local OSM communities") and unhelpful ("survey the data yourself"). 😕

**Comment by tyrasd** [comment]
Yeah, but it's quite hard to write down a good definition of what's *appropriate* in this context. Some aerial imagery may be totally non-open data, but have exceptions in their terms of usage that make it possible to use it for OSM (like bing). On the other hand, even some open data licenses may or may not be open enough to derive OSM data from them (cc-nc probably, idk).

It's probably best to list the most common cases that are OK for our use case. Maybe the [LWG](http://wiki.osmfoundation.org/wiki/Licensing_Working_Group) could help us out formulating them? //cc @pnorman

**Comment by pnorman** [comment]
> even some open data licenses may or may not be open enough to derive OSM data from them (cc-nc probably, idk).

cc-nd is not an open license, but there are open licenses where this is true.

**Comment by simonpoole** [comment]
IMHO CC0 and (really) PD are clear, anything else needs an explicit statement that manual digitizing/tracing does not create a derivative work.

**Comment by simon04** [comment]
There's a nice ODbL compatibility matrix in the wiki: https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility

**Comment by simonpoole** [comment]
Except that the table  is a) not a document of the LWG, b) misses some salient points particularly wrt CC by licenses

**Comment by andrewharvey** [comment]
> anything else needs an explicit statement that manual digitizing/tracing does not create a derivative work.

Noting that https://wiki.osmfoundation.org/wiki/Licence/Waiver_and_Permission_Templates has a Template text for aerial imagery waivers which people can use.
