### ISSUE TITLE
Latvia - correct boundary

### ISSUE THREAD

**Issue by RudyTheDev** [osmlab/editor-layer-index#1662]
Hello! How does one go about fixing the bounding polygon of a country? In this case, Latvia has several locations mapped somewhat approximately.

![lvpolybad](https://user-images.githubusercontent.com/3857299/200125536-ebf7d298-856c-4439-a178-336a8af32817.png)

It seem all the poly files are similarly incorrect.

https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/lv

Something like geofabrik has a "real" country border at https://download.geofabrik.de/europe/latvia.html but this of course goes outside the extents of the (usable) imagery.

Does one need to draw this oneself?

**Comment by grischard** [comment]
You can import https://download.geofabrik.de/europe/latvia.poly to https://geojson.io and edit that into the ELI files. The geofabrik poly conveniently cuts through the Baltic but that means it includes the island of Ruhnu; you might want to re-align that by dragging points on geojson.io, or in JOSM if you use that.

**Comment by cicku** [comment]
For the example in the screenshot, mapped somewhat approximately is expected when there is nothing useful in the water (Gulf of Riga).

It does not matter much honestly. Most of the polygons here are not 100% accurate to reduce the geojson file size.

**Comment by cicku** [comment]
@RudyTheDev One possible "fix" is to cut the boundary like this 
![image](https://user-images.githubusercontent.com/686438/202860614-14639064-c958-40ab-96a7-c1ec56e5f6b7.png)

The imagery is like this, and we can safely ignore the blank tiles.
![image](https://user-images.githubusercontent.com/686438/202860714-fc814988-e9eb-44d2-9da2-dacbd32059db.png)

Again, I would not like to see any detailed boundary accepted as it is not really needed, but if you have any better idea, feel free to let me know.

**Comment by RudyTheDev** [comment]
@cicku If this can't be fixed in this repository, where should I ask for this? iD editor only links to this repo for imagery problems. Should I ask directly at iD and JOSM repos? I don't know the details of where they keep imagery boundaries.

**Comment by cicku** [comment]
Hmm...What are the "imagery problems"? From our side, if the imagery is not broken, there should not be any problems.

**Comment by RudyTheDev** [comment]
Sorry, let me elaborate. iD and JOSM editors do not show/auto-select the imagery for some coastal locations in Latvia. For example, if you go to https://www.openstreetmap.org/#map=16/56.9918/23.8896 and edit in iD, it will auto-select "Bing Maps Aerial" rather than "Orthophoto (2016–2018), 1:5000, Latvia", which is indeed available in this location. (Same for JOSM not having "Latvia - LVM GEO orthophoto" in the Imagery menu, but I don't know where they get their data from.)

Expected:
![expected](https://user-images.githubusercontent.com/3857299/207113816-259cbc14-7ca8-42f2-9ac0-0fdaeb406f10.png)

Actual:
![actual](https://user-images.githubusercontent.com/3857299/207113824-9deb18fc-8da1-4162-ae8f-1100b22d3760.png)

iD has a "Report an Imagery Problem" link that points to https://github.com/openstreetmap/iD/blob/develop/FAQ.md#how-can-i-report-an-issue-with-background-imagery, which says "imagery sources come from the editor-layer-index project". (It didn't exactly say "boundaries", but I assumed it's implied.) And in this repo, I found the `lv_orthophoto_cycle6_2016-2018.geojson`, which appears to be the culprit, at least on a quick inspection?

But this is already several steps past the editor, so I'm in completely unfamiliar territory. I don't know where this boundary originally came from, how it is processed and imported and whether this is even the boundary that iD/JOSM uses. So I asked what would be the steps to fixing it, since I wasn't sure where fixing is needed. It seemed to me that this boundary was taken from the source that provided the imagery (it has various attribution properties), but the replies since then have suggested that it isn't? I guess I'm still confused what needs to be done and where.

I briefly tried the above-mentioned https://geojson.io, but it didn't make a .geojson file and I'm not sure what to do with a .poly file it made even if I follow your previous description for adjustment. And it also implies moving points manually, which feels a bit wrong for country borders, which brings me back to whether one could just arbitrarily modify the boundary like that without breaking something?

**Comment by RudyTheDev** [comment]
Thank you!

**Comment by soshial** [comment]
Thanks @RudyTheDev for proposing this improvement.
