### ISSUE TITLE
Migrate IndianaMap layers to Geographic Information Office server

### ISSUE THREAD

**Issue by 1ec5** [osmlab/editor-layer-index#1664]
We had another close call with the IndianaMap imagery briefly going offline in #1659 #1660 #1661. It’s back up now, but this exercise revealed that the newer replacement server run by the Indiana Geographic Information Office offers a much more usable version of this same imagery that isn’t washed out with an extra color channel: https://github.com/osmlab/editor-layer-index/issues/1660#issuecomment-1301743485. I think we should try to switch over to it even if the older server remains available. Most likely only the newer server is being updated with imagery captured since 2019.

/cc @rbuffat

**Comment by arch0345** [comment]
Resolved in #1863
