### ISSUE TITLE
Imagery broken: "Monongalia County 2022" in West Virginia>United States

### ISSUE THREAD

**Issue by Jdgat** [osmlab/editor-layer-index#1683]
Had to republish the layer with a new service URL and re-enable WMS. Nothing else about the service has changed. Can you all please update in iD? Thank you for your help!

New URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022_Aerial_Imagery/ImageServer/WMSServer?request=GetCapabilities&service=WMS

https://gis.morgantownwv.gov/portal/home/item.html?id=42c92b8bccab446ca051d48da707591f

**Comment by cicku** [comment]
Is this a temporary change or not?

**Comment by Jdgat** [comment]
This should be a permanent change.
