### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jfirebaugh** [osmlab/editor-layer-index#17]
We should use Transifex for translating imagery names and descriptions. Follow what iD does for presets:
- Assign each source an id
- `make` builds an imagery.yml source for Transifex
- `make translations` pulls down translations into locale directory, split into separate files
- Downstream consumers merge translations into their own

**Comment by tyrasd** [comment]
Is this approach really practical for this use case? There's quite a large (and ever growing) amount of layers by now and most of them only have local or regional importance. While it certainly makes sense to translate the description of the aerial imagery layer a city like Brussels into the locally used languages (here: at least French and Dutch), it may not be necessary to translate it into every other language as well.

What if we'd just let the contributors of imagery add multiple descriptions in the locally relevant languages? Idk, but why not just use OSM's *multilingual tags* pattern here as well, e.g. `"description:fr"`, etc.?

**Comment by bhousel** [comment]
I almost closed this as stale, but I think that:

- Each source should have a unique id 
- It would be useful to localize the globally relevant source names and attribution text
- It's totally ok to not translate something in Transifex that is not relevant

**Comment by tyrasd** [comment]
>  It's totally ok to not translate something in Transifex that is not relevant

yeah, but that's a bit hard to convey that in transifex's UI (with all it's 0-100% progress bars and rankings that suggest one should translate each and every string).

**Comment by manfredbrandl** [comment]
I would like to translate the interface strings and not the layer names. Is it possible to separate these into extra transifex resources? Then the interface part could be added as an extra resource to the iD-editor-team.

**Comment by manfredbrandl** [comment]
There are untranslatable parts in the iD-Editor which are not layer-names:
![image](https://user-images.githubusercontent.com/5360273/26874162-daa34734-4b7c-11e7-8832-27001f4908c8.png)

**Comment by bhousel** [comment]
This has been done for a while
