### ISSUE TITLE
[Watchdog] Imagery "Geoportal 2: High Resolution Orthophotomap (aerial image) (WMS)": sources/europe/pl/Geoportal2OrthophotomapHighQuality(aerialimage)_WMS.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1704]
Watchdog failed for 5 consecutive days for:
"Geoportal 2: High Resolution Orthophotomap (aerial image) (WMS)" -> [sources/europe/pl/Geoportal2OrthophotomapHighQuality(aerialimage)_WMS.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/pl/Geoportal2OrthophotomapHighQuality(aerialimage)_WMS.geojson)

Reason:
Error: WMS None: Exception Cannot connect to host mapy.geoportal.gov.pl:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&REQUEST=GetCapabilities
Error: WMS 1.3.0: Exception Cannot connect to host mapy.geoportal.gov.pl:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
Error: WMS 1.1.1: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1
Error: WMS 1.1.0: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0
Error: WMS 1.0.0: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0
Error: WMS None: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?service=WMS&request=GetCapabilities
Error: WMS 1.3.0: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?service=WMS&request=GetCapabilities&version=1.3.0
Error: WMS 1.1.1: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?service=WMS&request=GetCapabilities&version=1.1.1
Error: WMS 1.1.0: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?service=WMS&request=GetCapabilities&version=1.1.0
Error: WMS 1.0.0: Timeout for: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?service=WMS&request=GetCapabilities&version=1.0.0

CC contributors to this imagery:
@rbuffat, @starsep, @tyrasd

**Comment by starsep** [comment]
This comment applies here as well
https://github.com/osmlab/editor-layer-index/issues/1707#issuecomment-1345523221

**Comment by rbuffat** [comment]
Imagery seems to work again.
