### ISSUE TITLE
[Watchdog] Imagery "Geoportal 2: Orthophotomap (latest aerial imagery) (WMTS)": sources/europe/pl/Geoportal2Orthophotomap(aerialimage)_WMTS.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1705]
Watchdog failed for 5 consecutive days for:
"Geoportal 2: Orthophotomap (latest aerial imagery) (WMTS)" -> [sources/europe/pl/Geoportal2Orthophotomap(aerialimage)_WMTS.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/pl/Geoportal2Orthophotomap(aerialimage)_WMTS.geojson)

Reason:
Error: No zoom level reachable. (Tested: 0,1,2,3,20,21,22,23) Tiles might not be present at tested location: 19.148968656620372,51.92288695

CC contributors to this imagery:
@rbuffat, @starsep, @tyrasd

**Comment by starsep** [comment]
Imagery is available at this location.
Zoom levels should be limited to 4-19 if I am reading the error correctly

**Comment by rbuffat** [comment]
Imagery seems to work again.
