### ISSUE TITLE
[Watchdog] Imagery "IBGE BC250 - Trecho Rodoviário": sources/south-america/br/IBGE-BC250_rodoviaria.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1719]
Watchdog failed for 5 consecutive days for:
"IBGE BC250 - Trecho Rodoviário" -> [sources/south-america/br/IBGE-BC250_rodoviaria.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/br/IBGE-BC250_rodoviaria.geojson)

Reason:
Error: WMS None: Exception Cannot connect to host geoservicos.ibge.gov.br:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://geoservicos.ibge.gov.br/geoserver/ows?SERVICE=WMS&REQUEST=GetCapabilities
Error: WMS 1.3.0: Exception Cannot connect to host geoservicos.ibge.gov.br:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://geoservicos.ibge.gov.br/geoserver/ows?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
Error: WMS 1.1.1: Exception Cannot connect to host geoservicos.ibge.gov.br:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://geoservicos.ibge.gov.br/geoserver/ows?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1
Error: WMS 1.1.0: Exception Cannot connect to host geoservicos.ibge.gov.br:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://geoservicos.ibge.gov.br/geoserver/ows?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0
Error: WMS 1.0.0: Exception Cannot connect to host geoservicos.ibge.gov.br:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://geoservicos.ibge.gov.br/geoserver/ows?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0
Error: WMS None: Exception Cannot connect to host geoservicos.ibge.gov.br:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://geoservicos.ibge.gov.br/geoserver/ows?service=WMS&request=GetCapabilities
Error: WMS 1.3.0: Exception Cannot connect to host geoservicos.ibge.gov.br:443 ssl:<ssl.SSLContext object at 0x7f4b0fa058c0> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)] for: https://geoservicos.ibge.gov.br/geoserver/ows?service=WMS&request=GetCapabilities&version=1.3.0
Error: WMS 1.1.1: Timeout for: https://geoservicos.ibge.gov.br/geoserver/ows?service=WMS&request=GetCapabilities&version=1.1.1
Error: WMS 1.1.0: Timeout for: https://geoservicos.ibge.gov.br/geoserver/ows?service=WMS&request=GetCapabilities&version=1.1.0
Error: WMS 1.0.0: Timeout for: https://geoservicos.ibge.gov.br/geoserver/ows?service=WMS&request=GetCapabilities&version=1.0.0

CC contributors to this imagery:
@grischard, @Skippern, @Klumbumbus, @tyrasd, @bhousel, @matheusgomesms, @rbuffat

**Comment by matheusgomesms** [comment]
René, all IBGE layers are working to me right now on iD. Probably some problem with IBGE links and Watchdog?

One example:

https://metadadosgeo.ibge.gov.br/geonetwork_ibge/srv/por/catalog.search#/metadata/a183642f-c3ec-4fca-91dd-7393d12a0094

**Comment by matheusgomesms** [comment]
Related: #1716, #1717, #1718, #1719, #1720, #1721, #1722.

**Comment by rbuffat** [comment]
@matheusgomesms  Good catch! The watchdog script uses aiohttp which seems to be picky about SSL issues (respectively it is not that easy to disable all SSL checks). 

It looks like there is a solution to fix this issue:  https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled

**Comment by rbuffat** [comment]
Imagery seems to work again.
