### ISSUE TITLE
[Watchdog] Imagery "Rio Mosaico 2019": sources/south-america/br/Rio_2019.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1729]
Watchdog failed for 5 consecutive days for:
"Rio Mosaico 2019" -> [sources/south-america/br/Rio_2019.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/br/Rio_2019.geojson)

Reason:
Error: WMS -: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0 Error: Could not parse XML.
Error: WMS -: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?service=WMS&request=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://pgeo3.rio.rj.gov.br/arcgis/services/Imagens/Mosaico_2019/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.0.0 Error: Could not parse XML.

CC contributors to this imagery:
@matheusgomesms, @rbuffat

**Comment by matheusgomesms** [comment]
A couple of months ago, all Rio servers suffered a hacker attack, so they disabled most of their online servers at that time. It seems they updated the location, and we also have a 2022 imagery. Could we use them, instead of 2019?

https://pgeo3.rio.rj.gov.br/arcgis/rest/services/Imagens/Mosaico_2022/ImageServer

**Comment by rbuffat** [comment]
Imagery seems to work again.
