### ISSUE TITLE
[Watchdog] Imagery "U.S. Forest Service roads": sources/north-america/us/USForestService.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1735]
Watchdog failed for 5 consecutive days for:
"U.S. Forest Service roads" -> [sources/north-america/us/USForestService.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/USForestService.geojson)

Reason:
Error: No zoom level reachable. (Tested: 0,1,2,3,16,17,18,19) Tiles might not be present at tested location: -98.53713285826328,35.954899

CC contributors to this imagery:
@LivInTheLookingGlass, @1ec5, @iandees, @rbuffat, @simon04

**Comment by 1ec5** [comment]
This is working for me at the moment.

![USFS](https://user-images.githubusercontent.com/1231218/211172189-283b455a-7bef-4b42-93d1-ea02663d0e75.png)

**Comment by rbuffat** [comment]
Imagery seems to work again.
