### ISSUE TITLE
Add best=true to layers

### ISSUE THREAD

**Issue by G4rdener** [osmlab/editor-layer-index#1764]
Hi,
i would like to add the property "best=true" to the layers "Hamburg-20cm.geojson" and "Hamburg-DK5.geojson" (found in /europe/de). Since i haven't any clue how to do it by myself.
Would someone be so kind to do this for me?

**Comment by cicku** [comment]
I'm not from that region but can you let me know if these layers are constantly updated or not?

**Comment by G4rdener** [comment]
> I'm not from that region but can you let me know if these layers are constantly updated or not?

Yes they are updated between every 1 to 2 years and are the most up to date aerial imagery of Hamburg.

**Comment by cicku** [comment]
We can only have 1 imagery as the best in the same area, these two appear to be identical, can you clarify which exact one?

**Comment by cicku** [comment]
I can only set the photo one as the best, I have no idea about the map one. If this is ok, let me know.

**Comment by G4rdener** [comment]
This is totally fine for me. Better than nothing . ☺️
