### ISSUE TITLE
Maxar Premium Imagery  supplier not mentioned in the FAQ.md#how-can-i-report-an-issue-with-background-imagery

### ISSUE THREAD

**Issue by WillemGC** [osmlab/editor-layer-index#1766]
in the hotosm.org project 14234 in the RapiD mode there is the layer named Maxar Premium Imagery.
This layer has in the Hatay area for example square 90 some position issues. 

in the FAQ.md  how-can-i-report-an-issue-with-background-imagery   this supplier is not mentioned to report these issues. 

Query 1. Can this source or supplier be added to the FAQ.md?
or
Query 2. How should I report issues with mapposition related to Maxar Premium Imagery?
thanks!

https://github.com/openstreetmap/iD/blob/develop/FAQ.md#how-can-i-report-an-issue-with-background-imagery
https://tasks.hotosm.org/projects/14234/map/?editor=RAPID#background=Maxar-Premium&datasets=fbRoads,msBuildings&map=16.40/35.88775/36.10200
 
Compare  Bing Maps / Mapbox  versus Maxar and you'll find the proposed buildings 10 meters off map

**Comment by cicku** [comment]
Nothing we can do here, you can ask Kevin directly. https://twitter.com/kevin_bullock
