### ISSUE TITLE
Please add support for Bavaria (WMS) DOP80 Germany

### ISSUE THREAD

**Issue by geowOSM** [osmlab/editor-layer-index#178]
@bhousel, please consider adding support for Bavaria DOP80 in iD: http://www.geodaten.bayern.de/ogc/ogc_dop80_oa.cgi?
It’s the best imagery (Bavarian State Survey, orthorectified, update cycle 2 years) for Bavaria/Germany available for use in OSM, see http://wiki.openstreetmap.org/wiki/Contributors#Bayern
But it’s available only as wms. I asked as you mentioned in #152 you might consider including some limited wms support in iD soon.
Thanks

**Comment by simonpoole** [comment]
You are confusing two things here:

- adding an entry to this index (there are lots of WMS entries)
- support for WMS servers in iD (and other editors)

The easy solution for the later is to run a mapproxy service as an intermediary, if you don't have the (small) resources needed to do so, you could ask SOSM or FOSSGIS.

**Comment by geowOSM** [comment]
Thanks Simon, my fault, I meant wms support in iD and should have addressed bhousel directly. Corrected.

**Comment by simonpoole** [comment]
@geowOSM still if nobody wants to do it in DE, we (SOSM) can add it to our mapproxy instance.

**Comment by tyrasd** [comment]
WMS support in iD should be discussed in iD's repository. There's an old ticket (https://github.com/openstreetmap/iD/issues/1141) which could be re-opened if needed.

**Comment by geowOSM** [comment]
@tyrasd Thanks for re-opening openstreetmap/iD#1141.

@simonpoole Thanks, I appreciate your kind offer. I will check back tomorrow with the State Survey, if they might be able to provide a tms-url. If not, I would be happy with MapProxy. Do I understand correctly, that by adding it there, it can also be used in other editors, which rely on the editor-layer-index?

**Comment by simonpoole** [comment]
@geowOSM yes it then can be used as like a completely normal tileserver and if configured here will eventually turn up in iD and the other editors that use this index.

PS: a reasonably simple boundary polygon for Bayern in geo JSON would be helpful for adding the configuration.

**Comment by bhousel** [comment]
> WMS support in iD should be discussed in iD's repository. There's an old ticket (openstreetmap/iD#1141) which could be re-opened if needed.

Yes, lets reopen that ticket.. I've ported the [whoots code over to javascript](https://github.com/mapbox/whoots-js), so it would be a small lift to bring that library into iD and support WMSs that can serve EPSG:3857.

**Comment by geowOSM** [comment]
@simonpoole Today the Bavarian Survey Authority has confirmed on request, that there are so far no plans providing a TMS for the DOP80. If your offer is still valid I (and many others) would greatly appreciate if SOSM would add it to their mapproxy.

A boundary polygon for Bavaria should be already available in the editor-imagery-index repository, as the DE / Bavaria (2 m) layer is included. As an appropriate projection EPSG:4326 is available (but not 3857).

**Comment by simonpoole** [comment]
@geowOSM 

   http://mapproxy.osm.ch:8080/tiles/BAYERNDOP80/EPSG900913/{z}/{x}/{y}.png?origin=nw

should already work as custom imagery link in iD. I'll prepare a PR for adding it to the index.

**Comment by simonpoole** [comment]
See https://github.com/osmlab/editor-layer-index/pull/180
