### ISSUE TITLE
What is the purpose of scanex?

### ISSUE THREAD

**Issue by bryceco** [osmlab/editor-layer-index#1806]
This is probably related to #1539

There should be some documentation that explains how consumers should deal with scanex, which doesn't have a URL. With Bing the URL is well documented, and it's possible to contact Microsoft and request an access key. Is the same possible with scanex/IRS?

**Comment by simonpoole** [comment]
Historically it required some hardwiring see https://wiki.openstreetmap.org/wiki/Russia/kosmosnimki I don't believe it still works, @Zverik do you know anything about its status?

**Comment by Zverik** [comment]
I don't think anybody uses it anymore, given we have detailed coverage from Mapbox and Maxar.

**Comment by simonpoole** [comment]
> I don't believe it still works,

The host irs.gis-lab.info doesn't seem to exist any more so likely the whole thing is defunct and should be removed.

**Comment by bryceco** [comment]
As a consumer I've been generating debug warnings about it for years, so it would be great to either drop it or tell us how to use it.

**Comment by simonpoole** [comment]
Just for good measure I quickly checked if JOSM is doing anything different, but it doesn't work there either.
