### ISSUE TITLE
kt_tg_ortho_2017 has empty string as icon field

### ISSUE THREAD

**Issue by bryceco** [osmlab/editor-layer-index#1807]
This is somewhat pedantic but for all the other entries the icon field is either missing (null) or a valid string, but for this entry it's an empty string. Using a strongly typed language (Swift) it makes validation more complicated.

**Comment by grischard** [comment]
I've just removed the empty string there. I'd accept a PR for the validators to check for empty strings like that.

**Comment by rbuffat** [comment]
An empty string is perfectly valid Geojson, thus "standard" geo/json validation will not detect this issue.  Strange that an empty string causes issues for Swift.  As `icon` should be an URL, we could check if it is parsable with `urllib.parse.urlparse`.
