### ISSUE TITLE
OSIP 6 inch imagery does not load when zoomed in.

### ISSUE THREAD

**Issue by Korgi2** [osmlab/editor-layer-index#1809]
## URL of the imagery
wms[8,20]:https://geo1.oit.ohio.gov/arcgis/services/OSIP/OSIP_6in_best_avail/ImageServer/WMSServer?FORMAT=image/jpeg&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

## Two letter country code
US

## layer name
Ohio Statewide Imagery Program 6-Inch

The Ohio Statewide Imagery 6-inch imagery has been broken in all of Ohio since 2020. At low zoom levels the aerial works properly, but once you zoom in to a certain threshold the tiles stop loading properly like they have in the past.

Here is it working at low zoom: 
![image](https://user-images.githubusercontent.com/61196219/228992669-aa7aa4b6-ecac-4454-b3a2-01efc71fa8c4.png)

Here is what happens if one is to zoom in to edit buildings or roads:
![image](https://user-images.githubusercontent.com/61196219/228992772-b70f683f-0870-4125-8386-9916ce8737cc.png)

I am not sure what is causing the issue, if this is on OSM's end or OSIP's end.

This issue is also present on the OSIP II 1-foot imagery and the OSIP III 6-inch imagery.

**Comment by cicku** [comment]
Please provide a link of iD when you see the image above.

**Comment by simonpoole** [comment]
```wms[8,20]:``` looks very much like a JOSM background imagery entry.

**Comment by Korgi2** [comment]
> Please provide a link of iD when you see the image above.

Where would I find this? I apologize, I am not super familiar with using JOSM.

**Comment by cicku** [comment]
I thought you were using iD editor. I'm not sure what you are using here honestly. If you use JOSM, share the coordinates to us:

![image](https://user-images.githubusercontent.com/686438/235334992-19ead2cf-1409-4712-9800-0bb311ad76d3.png)

**Comment by Korgi2** [comment]
The issue can be seen across all of the OSIP 6-inch imagery for example at 41.4726,-84.5468. I think there is either a problem with JOSM loading the url of the tiles or an issue with the OSIP imagery's website for the smaller tiles.

**Comment by snoozingnewt** [comment]
It's statewide, and I also have the same issue (and have been for a while now)

**Comment by cicku** [comment]
It is definitely a sources issue and nothing we can really help here (we may restrict the zoom level but it does not prevent you zooming in at all).

You need to contact OSIP manager and let the team review

**Comment by Korgi2** [comment]
Update from OSIP:

"Please try this service   https://geo1.oit.ohio.gov/arcgis/rest/services/OSIP/OSIPIII_MostCurrent/ImageServer
Or the wms here https://geo1.oit.ohio.gov/arcgis/services/OSIP/OSIPIII_MostCurrent/ImageServer/WMSServer?request=GetCapabilities&service=WMS"

Is this of any use?
