### ISSUE TITLE
[Watchdog] Imagery "Munich latest aerial imagery 60cm": sources/europe/de/Munich-latest-aerialimagery60cm.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1810]
Watchdog failed for 5 consecutive days for:
"Munich latest aerial imagery 60cm" -> [sources/europe/de/Munich-latest-aerialimagery60cm.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/de/Munich-latest-aerialimagery60cm.geojson)

Reason:
Error: WMS None: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?SERVICE=WMS&REQUEST=GetCapabilities
Error: WMS 1.3.0: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
Error: WMS 1.1.1: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1
Error: WMS 1.1.0: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0
Error: WMS 1.0.0: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0
Error: WMS None: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?service=WMS&request=GetCapabilities
Error: WMS 1.3.0: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?service=WMS&request=GetCapabilities&version=1.3.0
Error: WMS 1.1.1: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?service=WMS&request=GetCapabilities&version=1.1.1
Error: WMS 1.1.0: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?service=WMS&request=GetCapabilities&version=1.1.0
Error: WMS 1.0.0: Exception Cannot connect to host ogc.muenchen.de:443 ssl:<ssl.SSLContext object at 0x7f0f18724ac0> [Connect call failed ('194.246.148.57', 443)] for: https://ogc.muenchen.de/wms/opendata_luftbild?service=WMS&request=GetCapabilities&version=1.0.0

CC contributors to this imagery:
@grischard, @DavidMoraisFerreira, @simonpoole

**Comment by OsmMUC** [comment]
Seems the URL for the service has changed, see https://opendata.muenchen.de/de/dataset/luftbild_opendata:

https://geoportal.muenchen.de/geoserver/opendata/luftbild_opendata/ows?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by map-per** [comment]
joto fixed this issue in #2289. So this can be closed.

**Comment by grischard** [comment]
Thanks again @joto !
