### ISSUE TITLE
[Watchdog] Imagery "IBGE Nomes de Ruas": sources/south-america/br/IBGE_Street_Names.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1811]
Watchdog failed for 5 consecutive days for:
"IBGE Nomes de Ruas" -> [sources/south-america/br/IBGE_Street_Names.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/br/IBGE_Street_Names.geojson)

Reason:
Error: No zoom level reachable. (Tested: 12,13,14,15,19,20,21,22) Tiles might not be present at tested location: -49.60756145539132,-14.398

CC contributors to this imagery:
@matheusgomesms, @rbuffat, @naoliv, @willemarcel

**Comment by willemarcel** [comment]
@rbuffat I added some URL restrictions to the Mapbox token used in these layers. Do you have a recommendation on how to make it work for the watchdog and for JOSM?

**Comment by matheusgomesms** [comment]
Closing because this layer does not exist anymore (#2369).
