### ISSUE TITLE
[Watchdog] Imagery "IBGE Endereços Distrito Federal": sources/south-america/br/IBGE_DF_Adresses.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1812]
Watchdog failed for 5 consecutive days for:
"IBGE Endereços Distrito Federal" -> [sources/south-america/br/IBGE_DF_Adresses.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/br/IBGE_DF_Adresses.geojson)

Reason:
Error: No zoom level reachable. (Tested: 0,1,2,3,17,18,19,20) Tiles might not be present at tested location: -47.906949999999995,-15.775649999999999

CC contributors to this imagery:
@simon04, @matheusgomesms, @willemarcel, @iandees, @bhousel, @rbuffat, @Marc-marc-marc, @Klumbumbus

**Comment by willemarcel** [comment]
Same case reported here: https://github.com/osmlab/editor-layer-index/issues/1811#issuecomment-1493109852

**Comment by matheusgomesms** [comment]
Closing because this layer was removed #2369.
