### ISSUE TITLE
Add LIST Basemap - Oceania\AU\TAS

### ISSUE THREAD

**Issue by tastrax** [osmlab/editor-layer-index#1844]
## URL of the imagery
https://services.thelist.tas.gov.au/arcgis/rest/services/Basemaps/Topographic/MapServer/tile/{z}/{y}/{x}

## Two letter country code
AU

## Desired layer name
TAS - LIST - Topographic Base Map

## License
as attached

## Is the license compatible with OSM?
yes - waiver attached
[Land Tasmania Signed Waivers.pdf](https://github.com/osmlab/editor-layer-index/files/11380284/Land.Tasmania.Signed.Waivers.pdf)

## Attribution (text, URL, required?)
<a href='https://creativecommons.org/licenses/by/3.0/au/' target='_blank'><img src='https://licensebuttons.net/l/by/3.0/88x31.png' alt='Creative Commons (BY)' /></a><a href='http://www.thelist.tas.gov.au' target='_blank'>the LIST</a> © State of Tasmania

## Icon
(optional)

## Bounding polygon
AU_TAS_LIST_TOPO.zip
[AU_TAS_LIST_TOPO.zip](https://github.com/osmlab/editor-layer-index/files/11380324/AU_TAS_LIST_TOPO.zip)

**Comment by andrewharvey** [comment]
Thanks for the ticket @tastrax. Added in #1845
