### ISSUE TITLE
[Watchdog] Imagery "IDEIB - Ortofoto 2021 (SITIBSA - scne.es)": sources/europe/es/ideib_balears.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1846]
Watchdog failed for 5 consecutive days for:
"IDEIB - Ortofoto 2021 (SITIBSA - scne.es)" -> [sources/europe/es/ideib_balears.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/es/ideib_balears.geojson)

Reason:
Error: Layers '' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@marcboschmatas

**Comment by Crashillo** [comment]
It looks like the endpoint has changed. Now is https://ideib.caib.es/geoserveis/services/imatges/GOIB_Ortofoto_2021_IB/MapServer/WMSServer?request=getCapabilities&service=wms

**Comment by Crashillo** [comment]
It looks like the url has changed. Now you have to indicate an specific layer. I've created https://github.com/osmlab/editor-layer-index/pull/2004 to solve this
