### ISSUE TITLE
Some OS maps not displaying

### ISSUE THREAD

**Issue by boothym** [osmlab/editor-layer-index#186]
- 7th Series (OS7)
- NLS - OS 6-inch County Series, 1888-1913
- OS 1:25k historic (OSM)
- OS New Popular Edition historic
- OS Scottish Popular historic

Tried to load them as custom URLs but they don't appear  - seems a bit pointless having these background available in iD if they don't show up. Can we either fix or remove them?

Also, how can the bbox be changed to exclude for example, OS OpenData StreetView from displaying in the options while editing in Northern/Republic of Ireland as it doesn't cover that area?

**Comment by tyrasd** [comment]
The following layers are hosted on an openstreetmap.org server `ooc.openstreetmap.org` and return *HTTP/403 forbidden* errors:

* `7th Series (OS7)`
* `OS 1:25k historic (OSM)`
* `OS New Popular Edition historic`
* `OS Scottish Popular historic`

@tomhughes – do you know anything about this server not running properly?

The remaining one `NLS - OS 6-inch County Series, 1888-1913` returns a *404*. Maybe the URLs of NLS' tile server have changed? //cc @RobJN.

**Comment by tomhughes** [comment]
Don't think I know anything about OSM hosted versions of those. I normally use the NLS ones. What server are they on?

**Comment by tomhughes** [comment]
Oh, that's errol! Blimey...

**Comment by tomhughes** [comment]
I think it should be fixed now but I suspect it has been broken ever since errol was upgraded to Ubuntu 14.04 so likely for several years!

**Comment by tomhughes** [comment]
Oh re the NLS ones at least some of the layers are now on tileserver.com and need an API key - not sure if the 6 inch is one that is or not off hand.

**Comment by tomhughes** [comment]
Yes the 6 inch layer is on tileserver.com now and need an API key.

**Comment by RobJN** [comment]
The NLS have given permission to OSM to use the tiles and in most (all)
cases there is a non API version of the URL for this.

On 6 Sep 2016 2:48 p.m., "Tom Hughes" <notifications@github.com> wrote:

Yes the 6 inch layer is on tileserver.com now and need an API key.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/osmlab/editor-layer-index/issues/186#issuecomment-244955486>,
or mute the thread

**Comment by tyrasd** [comment]
Thanks Tom!

@RobJN: Do you know what the non-API-key URL is for the NLS - OS 6-inch County Series, 1888-1913 layer?

**Comment by boothym** [comment]
Nice, thanks Tom. The maps haven't been working since I joined OSM earlier this year, only just found out where to report it!

**Comment by RobJN** [comment]
@tyrasd I checked my emails with NLS:

> Unfortunately we ran out of space on our main map tile servers before Christmas and this was one of the casualties. However, surprising as it may sound, given the commercial encouragement to use the API, it was genuinely and accident as I'd forgotten about the OSM use of this URL.

The aim was to get it back online. I've just sent an email to see what the progress is.
