### ISSUE TITLE
[Watchdog] Imagery "NYSDOP Orthoimagery - Latest": sources/north-america/us/ny/NYSDOP_Latest.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1866]
Watchdog failed for 5 consecutive days for:
"NYSDOP Orthoimagery - Latest" -> [sources/north-america/us/ny/NYSDOP_Latest.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/ny/NYSDOP_Latest.geojson)

Reason:
Error: Layers '4' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@ZLima12, @cicku, @rbuffat

**Comment by ZLima12** [comment]
Each layer for this source represents a different year of imagery. They are currently in the process of removing the oldest one, so I wanted to give them several days so I could be confident in making another update to the URL. I'll make a PR within a day to disable the old layer.

**Comment by ZLima12** [comment]
Sorry for the delay; addressed in #1868 .
