### ISSUE TITLE
[Watchdog] Imagery "Monongalia County 2022 Aerial Imagery": sources/north-america/us/wv/Monongalia_WV_2022.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1869]
Watchdog failed for 5 consecutive days for:
"Monongalia County 2022 Aerial Imagery" -> [sources/north-america/us/wv/Monongalia_WV_2022.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/wv/Monongalia_WV_2022.geojson)

Reason:
Error: WMS -: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0 Error: Could not parse XML.
Error: WMS -: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?service=WMS&request=GetCapabilities Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0 Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.1 Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.1.0 Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://gis.morgantownwv.gov/image/services/Imagery/Monongalia_County_2022/ImageServer/WMSServer?service=WMS&request=GetCapabilities&version=1.0.0 Error: Could not parse XML.

CC contributors to this imagery:
@cicku, @rbuffat

**Comment by Marc-marc-marc** [comment]
cc @Jdgat the author of [the request to add this layer](https://github.com/osmlab/editor-layer-index/issues/1561)

**Comment by Jdgat** [comment]
@Marc-marc-marc and @rbuffat, many apologies and thank you for the tag. We have encountered extensive errors in a recent upgrade of the federated enterprise system. We are currently rebuilding. We might need to republish and replace the URL for the WMS, but we are attempting to avoid that. Should I post results in this thread? Thank you again.

**Comment by cicku** [comment]
Yes you can

**Comment by Jdgat** [comment]
Looks like we are back up. We republished under the wrong layer name, so the current URL doesn't work. We will republish in the morning and should be functional again. Thank you all for your patience.

**Comment by Jdgat** [comment]
We've successfully republished the service under the old URL - so the imagery is now loading properly in iD!

The service item details URL has changed, however, so the credit link shown should be updated to: https://gis.morgantownwv.gov/portal/home/item.html?id=8ca507a5c1c043658eb50e40b1ae815f

Please let me know if I should pull a request to have that change made, or do something otherwise. Thank you! Many apologies from our team for the outage. Just about everything that could have gone wrong in this upgrade did, from what I understand.

**Comment by rbuffat** [comment]
Imagery seems to work again.
