### ISSUE TITLE
[Watchdog] Imagery "PCRS raster": sources/europe/fr/PCRS.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1882]
Watchdog failed for 5 consecutive days for:
"PCRS raster" -> [sources/europe/fr/PCRS.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/fr/PCRS.geojson)

Reason:
Error: Layers 'PCRS LAMB93' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@flacombe

**Comment by rbuffat** [comment]
Imagery seems to work again.

**Comment by nlehuby** [comment]
fixed by #1879
