### ISSUE TITLE
[Watchdog] Imagery "Digitaal Vlaanderen most recent aerial imagery": sources/europe/be/AIV_OrthoPhoto.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1883]
Watchdog failed for 5 consecutive days for:
"Digitaal Vlaanderen most recent aerial imagery" -> [sources/europe/be/AIV_OrthoPhoto.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/be/AIV_OrthoPhoto.geojson)

Reason:
Error: No zoom level reachable. (Tested: 0,1,2,3,18,19,20,21) Tiles might not be present at tested location: 4.20239793792617,51.10191075

CC contributors to this imagery:
@joostschouppe, @jbelien

**Comment by jbelien** [comment]
On it 👍
