### ISSUE TITLE
Maxar Premium imagery seems broken

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/editor-layer-index#1889]
Edit: See https://github.com/openstreetmap/iD/issues/9710#issuecomment-1625302613

For discussion, refer to
https://community.openstreetmap.org/t/maxar-imagery-not-working-was-maxar-is-blurred-in-id-and-other-similar-topics/100524

**Details**
Imagery: Maxar Premium
appearance: green blur, or similar
layer information: date unknown
tile information: tile information labels disappear immediately when loading them
location: Any/World
version: iD 2.25.2 live and 2.26.0-dev via [netlify](https://ideditor.netlify.app/#background=Maxar-Premium&disable_features=boundaries&map=17/52.65127/-7.24882)
Browser: Any
OS: Any

Imagery seems broken, or wasn't updated correctly.

**Comment by Mahabarata** [comment]
Same probleme in North America, Central America, South America, Africa, Europa, Asia, Australia...

But works here (left and bottom/left parts) : https://www.openstreetmap.org/edit#map=14/80.5683/-78.4274

In another area, it looks like imagery at zoom 11 and higher has disappeared (left part) : https://www.openstreetmap.org/edit#map=11/48.7984/0.2422
and imagery at zoom 12 and higher has disappeared  (right part) : https://www.openstreetmap.org/edit#map=12/48.7984/0.2422

**Comment by fnordson** [comment]
Looks like it's not coming back soon: https://community.openstreetmap.org/t/maxar-imagery-not-working-was-maxar-is-blurred-in-id-and-other-similar-topics/100524/15

**Comment by cicku** [comment]
The imagery itself is very low quality in general.

If Maxar won't bring it back then we will remove it.

**Comment by fnordson** [comment]
It may be low quality, but it's the best quality in certain parts of the world.  
Especially 3rd world countries.  
The permanent loss of Maxar would be a heavy blow to mapping there.

**Comment by ErinBaker** [comment]
> It may be low quality, but it's the best quality in certain parts of the world. Especially 3rd world countries. The permanent loss of Maxar would be a heavy blow to mapping there.

Agree. In south east Asia, Maxar has been the best in terms of resolution and recency. 
The other imagery providers are up to 3 years old in urban capitals, for example. It's permanent loss would be detrimental.

**Comment by b-unicycling** [comment]
It was the most recent imagery in Ireland for the last about 5 months, blurry, but at least not 12 years old like Esri Clarity. Thankfully, Bing is catching up slowly.

**Comment by danieldegroot2** [comment]
_Updated links in top post. Please keep discussion here related to iD editor's functionality. Thanks for your patience in advance._

**Comment by simonpoole** [comment]
> Please keep discussion here to iD editor's functionality.

You are joking I hope.

**Comment by danieldegroot2** [comment]
It's just a reminder this repository is dedicated to the iD editor, not general editing. I'm not wishing to backseat-moderate the topic. Also, it drowns out any useful comments where I may not get mentioned (like the above).

I hope this answers your remark.

**Comment by cicku** [comment]
You are still joking.

Closing since it is out of scope.

**Comment by grischard** [comment]
Clarification from one of the maintainers: this repository is not dedicated to the iD editor. Many editors use the editor layer index, and the project aims to support all of them. The appropriate place for further discussion on this topic is https://community.openstreetmap.org/t/maxar-imagery-not-working-was-maxar-is-blurred-in-id-and-other-similar-topics/100524
