### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by blacha** [osmlab/editor-layer-index#1890]
A few years ago we (LINZ) added some imagery from our basemaps service to repo, at that time we discussed the use of WebP as the format for serving the tiles https://github.com/osmlab/editor-layer-index/pull/913

Since then Safari now supports WebP, Would you accept a pull request to convert these from jpg to webp.

Reasoning:
- Webp is much higher use in our system so it has a much higher cache hit ratio 
- Webp generally is much smaller file size and higher quality 
- Webp supports transparency now that some layers are individual datasets this would be shown as a black outline.

![5403](https://github.com/osmlab/editor-layer-index/assets/1082761/2f4b976b-8d36-4ac0-b682-66e6daf372ac)

**Comment by grischard** [comment]
Related JOSM issue for webp support: https://josm.openstreetmap.de/ticket/14361

**Comment by simonpoole** [comment]
webp works just fine as is with Vespucci fwiw.

**Comment by tsmock** [comment]
> Related JOSM issue for webp support: https://josm.openstreetmap.de/ticket/14361

JOSM WebP support currently lives in a plugin. The plugin is not enabled by default. Users currently have two choices: `ImageIO` and `webp`. `webp` is specific to WebP while `ImageIO` is more of a way to add additional image formats in the future, like AVIF.

**Comment by andrewharvey** [comment]
It's still unclear to users of JOSM that they need to enable this plugin, most users will just choose the imagery item and then be lost when it's not working.

Short of JOSM enabling WebP by default I've suggested displaying a user message when this happens https://josm.openstreetmap.de/ticket/24106#ticket.
