### ISSUE TITLE
Catastro Spain 403, rate limitting?

### ISSUE THREAD

**Issue by mote0230** [osmlab/editor-layer-index#1897]
Using the catastro Spain overlay in the Id editor, I got a couple tiles to load, and after that I got nothing. Looking in the request log, I see a lot of 403's (Access Denied).

Suggestions: 

- After getting 403'd, don't keep hammering the server
- Rate limit initial requests so we don't get 403'd? I'm not in Spain, maybe Spanish IP get preferential treatment?

**Comment by cicku** [comment]
Server owner can apply whatever rate limiting rules there, it is out of scope to discuss here.
