### ISSUE TITLE
Remove Freemap Outdoor

### ISSUE THREAD

**Issue by zdila** [osmlab/editor-layer-index#1900]
[Freemap Outdoor](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/FreemapOutdoor.geojson) map should probably be removed because for some countries now it uses hillshading and contours from sources not clearly allowed to be used for mapping to OSM.

PS: I am the author of the map
PPS: You can browse the map at https://www.freemap.sk/#layers=X

**Comment by grischard** [comment]
Fixed in [09e9e92](https://github.com/osmlab/editor-layer-index/commit/09e9e9285a9234925c68162d9a6f08bc8bdb82b7)

**Comment by grischard** [comment]
Thank you @zdila !
