### ISSUE TITLE
US Department of State Humanitarian Information Unit imagery

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#192]
Allan Mustard is the United States Ambassador to Turkmenistan, and edits OSM as [apm-wa](https://openstreetmap.org/user/apm-wa). In his [SOTM keynote talk today](http://2016.stateofthemap.org/program/), he lamented map reversions in Askaban by users who were using outdated imagery. I promised that I would try to include the more recent one in the editors.

The US Department of State currently provides 366 imagery sets at http://hiu-maps.net/hot/1.0.0/ that can be used freely. Most of them are actively used in the HOT tasking manager, but it would be good for mappers to have access to them even if they're not HOT mappers.
- The imagery definition do not contain (useful) bounding boxes. I will try to find out if these are available.
- I am not sure what would be the best way to add these to the index. One big json file in misc would be the easiest to maintain, if that is acceptable. @tyrasd suggested adding the layers to the output at build time, but an explicit definition in the sources seems better to us in the end.
- The xml definitions have to be converted to json. This is most probably doable in a few lines of python.

**Comment by iandees** [comment]
It would be great to see these in the index!

A bounding box would be important to make sure these layers show up for the right editors and an approximate capture date would be helpful to show that the imagery is newer than whatever else is in the area.

As far as organization in the repo, each source should be its own JSON file and I would prefer to maintain the existing hierarchy based on general coverage area/country. Do new layers get added frequently?

**Comment by iandees** [comment]
Also note that we're in the middle of making all source files GeoJSON files (#191), so if you do end up creating the sources, try to get them to match that format so we don't have merge conflicts.

**Comment by tyrasd** [comment]
> 366 imagery sets

It looks more like 165 layers, because most (all?) of the layers are actually twice in the list: once as a OGC-TMS layer and once as a "google/leaflet/etc. compatible" one with a name ending in `-flipped` (that's the format most layers in this repo actually use). For example there are http://hiu-maps.net/hot/1.0.0/ashgabat-2015/ and http://hiu-maps.net/hot/1.0.0/ashgabat-2015-flipped/.

**Comment by tyrasd** [comment]
> The imagery definition do not contain (useful) bounding boxes. I will try to find out if these are available.

@grischard any news on this?

**Comment by grischard** [comment]
I've gotten an email from the state department:

> I think this is a really interesting idea. However, I'm not sure if this is possible yet, because we need to have users click yes on a checkbox agreeing to the NextView license before they can use our imagery services.

Those usage terms say:

> _“This data is licensed for use by the US Government (USG) under the NextView (NV) license and copyrighted by Digital Globe or GeoEye. The NV license allows the USG to share the imagery and Literal Imagery Derived Products (LIDP) with entities outside the USG when that entity is working directly with the USG, for the USG, or in a manner that is directly beneficial to the USG. The party receiving the data can only use the imagery or LIDP for the original purpose or only as otherwise agreed to by the USG. The party receiving the data cannot share the imagery or LIDP with a third party without express permission from the USG. At no time should this imagery or LIDP be used for other than USG-related purposes and must not be used for commercial gain. The copyright information should be maintained at all times. Your acceptance of these license terms is implied by your use.”_
> 
> In other words, you may only use NextView imagery linked from this site for digitizing OpenStreetMap data for humanitarian purposes.

So in other other words, it doesn't sound like we're allowed to.

**Comment by tyrasd** [comment]
That's too bad :cry: (Even though one might argue that the layers in this repository are by definition only for *digitizing OpenStreetMap data*, but of course we're not enforcing that and mapping might not always be  focused on *humanitarian purposes*.)

**Comment by grischard** [comment]
For the first part, the French community solved that problem for their local orthoimagery by setting up a reverse proxy that only allows certain referrers (openstreetmap.org...) and user agents (JOSM...). I could certainly do that if it's required.

For the second part, I've asked Allan Mustard if State could explicitly allow any kind of OSM mapping in its license. We could then link to the background terms of use in the editors.

**Comment by tyrasd** [comment]
see #194 for some discussion about the issues that come with using a referrer-based solution.

> For the second part, I've asked Allan Mustard if State could explicitly allow any kind of OSM mapping in its license. We could then link to the background terms of use in the editors.

:+1: please reopen this ticket once you get (hopefully positive) feedback on this!
