### ISSUE TITLE
"private" api key now required for Mapbox sat and locator layers

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#1943]
This https://github.com/osmlab/editor-layer-index/commit/cc3f64158fac656c9c09fc9e894f1362e29c2ea1 seems to have gone nearly unnoticed. @tyrasd was there any indication from Mapbox if they would be prepared to provider additional keys? Or should we just remove the layers from ELI?

See also https://github.com/MarcusWolschon/osmeditor4android/issues/2323

**Comment by tyrasd** [comment]
Hey. Ohhh, I'm very sorry: I totally forgot about Vespucci when making the round of contacting existing "big" users of the old key (it didn't help that Vespucci didn't show up in the list of referrer domains in the dashboard, but I should definitely have remembered that you'd be using it as well). :bow: 

Mapbox were actually quite nice to give us (i.e. _me_, for now) access to a special account which can create virtually unlimited keys for all kinds of OSM tools. I'll send you a key for Vespucci in a minute.
