### ISSUE TITLE
No (backwards compatible) json output provided

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#195]
Imagery.json is not backwards compatible with the previous format, further in the process of turning the sources into geojson the bbox parameter was dropped, which might or might not have been the same as the enclosing boundingbox of any (multi-)polygons specified.

**Comment by iandees** [comment]
Thanks for pointing this out, and apologies for messing that up. It was definitely not my intention to change the formats of the output. We'll look into fixing the output format now.

**Comment by iandees** [comment]
@simonpoole can you check out [the updated `imagery.json` from my PR](https://raw.githubusercontent.com/osmlab/editor-layer-index/3243bec7198ffe957b44bd6e6f636188c4692e37/imagery.json)? The diff looks pretty good to me.

You're right about the bounding box going away: in my backport here I stuck with using the polygon feature in `extent`. Does Vespucci rely on `bbox`?

**Comment by simonpoole** [comment]
Just got back, I'll have a look at it in the morning. Currently vespucci relies on the bbox for selecting the best imagery, there are multiple ways to work around this I would just rather not do it at runtime.

**Comment by iandees** [comment]
There's [a place in GeoJSON for bounding box](http://geojson.org/geojson-spec.html#bounding-boxes) so we can include the bounding box from the original source if it has one (and then include it in the output `imagery.json`).

**Comment by simonpoole** [comment]
Well that would require redoing all the json to geojson conversions, not sure if you really want to do that. Simply generating the bbox from the, if present, polygon(s) would seem to make more sense in the legacy conversion script for now.
