### ISSUE TITLE
Maryland Latest Imagery ⚠️ Currently Down 🚨

### ISSUE THREAD

**Issue by talllguy** [osmlab/editor-layer-index#1954]
The Maryland Latest Imagery Layer (#148 #171 #285 #1231) is currently down, due to a service update that bumped the imagery to the latest collection.

>The MD [iMAP Six Inch Imagery map service](https://geodata.md.gov/imap/rest/services/Imagery/MD_SixInchImagery/MapServer) has been updated. It now contains the 2020 Western Shore imagery and the 2022 Eastern Shore imagery.

This update dropped WMS support. I've got a service ticket in with the DoIT organization that manages it, asking if WMS can be turned back on.

**Comment by talllguy** [comment]
@cicku it looks like the imagery service is not working. However, they [did enable WMS again](https://geodata.md.gov/imap/services/Imagery/MD_SixInchImagery/MapServer/WMSServer?request=GetCapabilities&service=WMS) on the cached map service. 

Here's a sample tile from the change in https://github.com/osmlab/editor-layer-index/commit/7d76e8b730e09faf6db388517696096659181d10: https://geodata.md.gov/imap/services/Imagery/MD_SixInchImagery/MapServer/WmsServer?LAYERS=MD_SixInchImagery&STYLES=&FORMAT=image/jpeg&CRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=-8530372.355438232,4779454.503950192,-8529760.859212035,4780066.0001763925&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap

Let's reopen and either use the WMS again or fix the image server one. The image server at DoIT is markedly slower in my experience and I always recommend the map service.

**Comment by cicku** [comment]
ImageServer is working, perhaps it was slow on your side.

I will check the WMS before the second commit.

**Comment by talllguy** [comment]
Thanks! DoIT is having trouble getting the WMS working again and I've also been having trouble getting the WMS working via JOSM directly. Do you have a way to figure out what the WMS parameters would have been in the past, when it used to work?

**Comment by talllguy** [comment]
I noticed that the WMTS layer works great. Is that usable in the OSM imagery index?

**Comment by cicku** [comment]
WMTS of 512*512 is not supported by iD. It loads in JOSM.

WMS is enabled at ImageServer, so I will switch back soon.

**Comment by talllguy** [comment]
Thank you! I did also notice the WMS on image server does work. It is a bit slow because of how each tile is rendered on demand, but it does offer one additional zoom level that the cached map server does not offer. I'd vote to keep the Image Server option as the default since most OSM editors concentrate on the highest zoom. What do you think?

**Comment by cicku** [comment]
If the WMS on ImageServer is not cached, then I do not see any reason moving to it at the moment because we are loading from exportImage which is the same.

Once there is a cached service ready, you can let me know.

**Comment by cicku** [comment]
It appears the imagery is back, can you confirm?

**Comment by talllguy** [comment]
Sure, let me try it out
