### ISSUE TITLE
[Watchdog] Imagery "OpenStreetMap (Basque Style)": sources/world/OpenStreetMap-BasqueStyle.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#1973]
Watchdog failed for 5 consecutive days for:
"OpenStreetMap (Basque Style)" -> [sources/world/OpenStreetMap-BasqueStyle.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/world/OpenStreetMap-BasqueStyle.geojson)

Reason:
Error: No zoom level reachable. (Tested: 0,1,2,3,17,18,19,20) Tiles might not be present at tested location: 0.0,0.0

CC contributors to this imagery:
@Marc-marc-marc

**Comment by Marc-marc-marc** [comment]
hardware failure https://github.com/osm-fr/infrastructure/issues/465

**Comment by rbuffat** [comment]
Imagery seems to work again.
