### ISSUE TITLE
Sources using undocumented {wkid} placeholder

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#1975]
There are a number of US sources with type "WMS" that are using an undocumented {wkid} placeholder. Lets say that I'm slightly surprised that these were merged to start with. They clearly need a different type than WMS (I would suggest an expletive given the nature of these sources) and that and the placeholder needs to be documented.

See https://github.com/search?q=repo%3Aosmlab%2Feditor-layer-index%20wkid&type=code and https://github.com/MarcusWolschon/osmeditor4android/issues/2343

**Comment by arch0345** [comment]
I agree that these sources need a different type.

It looks like this was first added in #1241.

See also:
* #442
* https://github.com/osmlab/editor-layer-index/pull/657#discussion_r285339295
* https://github.com/openstreetmap/iD/pull/5738

**Comment by tyrasd** [comment]
see also https://github.com/openstreetmap/iD/issues/5738
