### ISSUE TITLE
Imagery dates for Esri Clarity are missing

### ISSUE THREAD

**Issue by Dimitar5555** [osmlab/editor-layer-index#1985]
Currently Esri Clarity shows "unknown" for the date taken field. It would be useful to know when the imagery was taken. If this issue is for the main iD repository, let me know.

![image](https://github.com/osmlab/editor-layer-index/assets/19364673/dbea94cb-997f-4801-a74a-d6138577ad35)

**Comment by danieldegroot2** [comment]
Workaround: Check to see if [World Imagery Wayback](https://livingatlas.arcgis.com/wayback/) has the imagery (zoom out to get more imagery layers!). Usually it is the earliest imagery (ie. Esri 2014-02-20). Click on the background at the location. The source is usually a year or more older (ie. Microsoft -Bing-, or DigitalGlobe -Maxar- 2011 or 2012). Includes month and day.

**Comment by cicku** [comment]
We are only an imagery layer index, the editor has to be smart to detect the metadata.
