### ISSUE TITLE
Airbus Imagery

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/editor-layer-index#1988]
Hi,

Since the deletion of Maxar imagery, I spend time on Ggle Earth when I see bad imagery on Bing/Esri/Esri beta/Mapbox (or when I want to know the date of an imagery when information is not in the background panel, or when imagery is very old and I want to see if the feature is still there on more recent imagery). 

Imagery in this sofware is not Ggle imagery but images purchased from suppliers : the name of the supplier is visible at the bottom of the view. If you choose to look at historical imagery of an area (you may have imagery from 1985 to today), you can see that the suppliers change.

In this sofware, Maxar was a big supplier of imagery. Maxar is a commercial compagny but, for a while, you were able to convince them to give you access to their imagery (or at least to a part of their imagery).

Now, in Ggle Earth, I can see that Airbus is an increasingly frequent supplier, with very good/precise imagery all over the Earth.

Like Maxar, Airbus is a commercial compagny. But what you got from Maxar, maybe it is possible to get from Airbus.

So I would like to know if you have ever contact them ?

I don't know if I may add a link in this issue, please edit my issue if not :
https://www.airbus.com/en/space/earth-observation/satellite-imagery

Best regards

**Comment by cicku** [comment]
This is out of the scope. We do not contact any commercial provider like this, you need to evaluate on your own.

Likely you won't get any positive answer because Airbus mostly has no interests of doing charity.

https://oneatlas.airbus.com/service/basemap
