### ISSUE TITLE
Freemap background layer no more available 

### ISSUE THREAD

**Issue by dp7x** [osmlab/editor-layer-index#1997]
In the last days I noticed that freemap.sk layer is no more available in ID editor: I can only choose Open Topo Map as topographic background with contours, as you can see in the following image.

![immagine](https://github.com/osmlab/editor-layer-index/assets/103643938/dba4800d-2f89-4abb-98ed-606629eaba30)

I use it a lot and used it for sure no more that 2 weeks ago. 
I am mapping over central Italy.

Can anybody take a look ?
Thank you

**Comment by cicku** [comment]
No.

https://github.com/osmlab/editor-layer-index/issues/1900
