### ISSUE TITLE
US / StratMap CapArea & McLennan Imagery (Natural Color 2020 no longer working

### ISSUE THREAD

**Issue by elevenchars** [osmlab/editor-layer-index#2046]
The "US / StratMap CapArea & McLennan Imagery (Natural Color 2020)" imagery no longer works. Tiles return HTTP 400 error. The 2021 version still works, but has some areas which do not actually load properly at higher zooms. Should the 2020 option be removed?

**Comment by arch0345** [comment]
Thanks for reporting this! This should be fixed with #2048
