### ISSUE TITLE
use GeoJSON linter to test geojson input

### ISSUE THREAD

**Issue by tyrasd** [osmlab/editor-layer-index#211]
Additionally to checking against our custom json schema, we should use a GeoJSON linter (like [geojsonhint](https://github.com/mapbox/geojsonhint), optimally one that supports [RFC 7946 GeoJSON](https://tools.ietf.org/html/rfc7946)) to check for basic GeoJSON compatibility of the source layers (e.g.validity of geometries, winding order of polygon rings, etc.).

Maybe this could be done as part of js-ification #168?

**Comment by iandees** [comment]
For what it's worth, the jsonschema check does a pretty good job of verifying the GeoJSON source files.

**Comment by bhousel** [comment]
> Maybe this could be done as part of js-ification #168?

yes 💯

**Comment by tyrasd** [comment]
> For what it's worth, the jsonschema check does a pretty good job of verifying the GeoJSON source files.

As far as I can see, it can't find stuff like unclosed polygon rings, wrong winding order of rings, self-intersecting geometries or mismatched inner/outer rings, can it?

**Comment by iandees** [comment]
> As far as I can see, it can't find stuff like unclosed polygon rings, wrong winding order of rings, self-intersecting geometries or mismatched inner/outer rings, can it?

That's true. I guess I'm hoping that whoever generates the GeoJSON for their submission would generate valid GeoJSON, but it's no problem to add the geojsonlint check so let's do it.

**Comment by grischard** [comment]
Maybe we can use https://github.com/JasonSanford/geojsonlint.com/blob/master/geojsonlint/utils.py

**Comment by rbuffat** [comment]
We currently do not use a geojson conform encoding of MultiPolygons. There is https://github.com/osmlab/editor-layer-index/pull/857 to fix this, but it is stale for quite a while. With the changes in this PR the validity of geometries are tested with the shapely python library (which uses geos) https://shapely.readthedocs.io/en/stable/manual.html#diagnostics

**Comment by rbuffat** [comment]
With https://github.com/osmlab/editor-layer-index/pull/1450 there is now a validation for geometries. Detected errors include e.g..: 

```
geometry is not valid: Hole lies outside shell[120.8268 15.3658]
```

```
geometry is not valid: Self-intersection[-70.5619471801745 -4.17766449833781]
```

In combination with the jsonschema checks, there is now a nearly complete check for GeoJSON validity. Thus I'm closing this issue.
