### ISSUE TITLE
[Watchdog] Imagery "Hennepin County Orthoimagery (2022)": sources/north-america/us/mn/Hennepin_Ortho_2022.geojson broken

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#2115]
Watchdog failed for 5 consecutive days for:
"Hennepin County Orthoimagery (2022)" -> [sources/north-america/us/mn/Hennepin_Ortho_2022.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/mn/Hennepin_Ortho_2022.geojson)

Reason:
Error: Layers '1' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@gvwaal

**Comment by gvwaal** [comment]
Changed &LAYER=1 to &LAYER=0 in #2117.

**Comment by grischard** [comment]
Fixed in #2117, thank you @gvwaal
