### ISSUE TITLE
Add issue template for requesting new images?

### ISSUE THREAD

**Issue by simon04** [osmlab/editor-layer-index#213]
Since Feb 2016, GitHub supports [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/). This would help getting some information immediately.

Some items that come to my mind:
* URL
* Desired name
* License
* License is compatible with OSM
* Country code
* Optionall: Attribution (text, URL, required?)
* Optionall: Icon

Nice to have, but perhaps too technical:
* Polygon
* WMS/WMTS capabilities URL

What do you think?

**Comment by bhousel** [comment]
I like it 👍
