### ISSUE TITLE
Added Benton County Oregon imagery

### ISSUE THREAD

**Issue by jmarchon1** [osmlab/editor-layer-index#2137]
## URL of the imagery
[https://svc.pictometry.com/Image/4C6D6C12-2E62-AC13-0428-6EF04B195AD4/wmts/PICT-ORBENT23-pWRF0BQ02F/default/GoogleMapsCompatible/{zoom}/{x}/{y}.png](https://svc.pictometry.com/Image/4C6D6C12-2E62-AC13-0428-6EF04B195AD4/wmts/PICT-ORBENT23-pWRF0BQ02F/default/GoogleMapsCompatible/%7Bzoom%7D/%7Bx%7D/%7By%7D.png)

## Two letter country code
US

## Desired layer name
e.g. Benton County Imagery

## License
If I'm not misunderstanding, [this wiki page](https://wiki.openstreetmap.org/wiki/Benton_County,_Oregon) says we can use all GIS data from Benton County. I'm assuming the imagery is part of that. I got the imagery link here: [https://wiki.openstreetmap.org/wiki/Oregon#County](https://wiki.openstreetmap.org/wiki/Oregon#County)
Verification would probably be a good idea.

## Is the license compatible with OSM?
See above

## Attribution (text, URL, required?)
I don't think so, but I'm not sure

## Privacy policy (URL)
Unknown

## Bounding polygon
Here is a rough geojson file of the imagery extent:
[https://gist.github.com/jmarchon1/ee6b246f90cc5a8d23a68fbcf08dcaf6](https://gist.github.com/jmarchon1/ee6b246f90cc5a8d23a68fbcf08dcaf6)
The imagery extent doesn't quite match the county border, so an export of that outline probably shouldn't be used.

**Comment by cicku** [comment]
Any imagery from pictometry.com cannot be submitted due to the copyright.

Closing.

**Comment by danieldegroot2** [comment]
@1ec5 could you look at this, please? I would suggest the wiki page to be updated to reflect copyright status if this is correct.
