### ISSUE TITLE
Start versioning the repo and output

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#214]
I consider the issue that @tyrasd touched on in https://github.com/osmlab/editor-layer-index/pull/206 , that we are not versioning at least the output, the most annoying thing about the current setup. Besides that having the unversioned output files in the repo itself is simply messy, it further makes it difficult to consume the output automatically without having to fear breakage (as we had with the transition to GeoJSON).

Is there any fundamental problem with say generating a (github) release per week if something has changed and uploading the generated files to the release section of github? Or any other versioned repo system that is belief system neutral (and no, I'm not a particular python fan, actually I just compared it to plague and cholera, one of them being another script language).

**Comment by iandees** [comment]
I do like the idea of building releases and putting the output somewhere outside the repo. I think we can convince Travis or Circle to generate the output and automatically post to GitHub Releases for us: https://docs.travis-ci.com/user/deployment/releases/ for example

**Comment by bhousel** [comment]
Yes, I'd like these versioned and published to npm too.   

I know we mentioned this in #179 (multiple types per source), which would be a breaking change.  Is there anything else that we want to change about the schema soonish that would break compatibility?  

`package.json` advertises this project as version `0.0.0`, which means anything can change at anytime.  But I think we should publish `0.0.0`, make whatever breaking changes we want to, then publish `1.0.0` and start following semantic versioning thereafter.

**Comment by tyrasd** [comment]
> anything else that we want to change about the schema soonish that would break compatibility?

Do we want to keep all three output formats? At least having both GeoJSON and JSON seems a bit redundant.

And if we really want to go all-in, we could think about how to support *restricted* imagery (like #192 and #194) where a client must display the user a modal window with the imagery's terms of use??

**Comment by simonpoole** [comment]
vespucci currently consumes the JSON format and that wont change before 0.9.9, but I'm not sure if that is really a criteria given that I remove the WMS entries and minimize the result before including it in the build.

**Comment by grischard** [comment]
Is this still necessary with #385?
