### ISSUE TITLE
Philadelphia 2015 Imagery

### ISSUE THREAD

**Issue by talllguy** [osmlab/editor-layer-index#218]
The city of Philadelphia has their 2015 imagery freely available to the public. It is very high resolution.

http://maps.pasda.psu.edu/arcgis/rest/services/pasda/PhiladelphiaImagery2015/MapServer

![image](https://cloud.githubusercontent.com/assets/1827881/20247276/5388911a-a996-11e6-8516-c62f2c4f6564.png)

**Comment by tyrasd** [comment]
Hi @talllguy 

I found (see #425) that this layer doesn't seem to work anymore. Right now I get a HTTP 400 error from the server when trying to get an image from the service. In fact, even the `GetCapabilities` call returns the same HTTP/400 error: http://maps.pasda.psu.edu/arcgis/services/pasda/PhiladelphiaImagery2015/MapServer/WmsServer?&SERVICE=WMS&REQUEST=GetCapabilities

```
HTTP Status 400 -
description The request sent by the client was syntactically incorrect.
```

Is it just a temporary hiccup or has the service been move to another URL, perhaps?
