### ISSUE TITLE
King County, WA (Seattle, US) Orthoimagery 2019, 2021

### ISSUE THREAD

**Issue by bennettgoble** [osmlab/editor-layer-index#2210]
King County has several high quality orthoimagery datasets which cover the metropolitan area of Seattle. Unfortunately, the details of licensing terms are unknown which means someone may need to reach out to  (giscenter@kingcounty.gov) for more information. Given the quality of the imagery and its coverage of a large metropolitan area, this may be well worth the effort.

## URL of the imagery
Dataset information: https://kingcounty.gov/en/legacy/services/gis/gisdata/metadata/ortho_data#2019KC_NAT
Webapp: https://kingcounty.maps.arcgis.com/apps/webappviewer/index.html?id=ec3bb48a932e4e0b86ec55598726db5b

In addition to the 2019 dataset, the web viewer also has data from 2021 which is not documented on the ortho_data page.

## Two letter country code
US

## Desired layer name
King County Aerial 2019
King County Aerial 2021 (If available)

## License
Unknown, a waiver may be necessary.

## Is the license compatible with OSM?
Unknown, waiver may be necessary.

## Privacy policy (URL)
https://kingcounty.gov/en/legacy/about/website/privacy

## Bounding polygon
[map.json](https://github.com/osmlab/editor-layer-index/files/13814073/map.json) (GeoJSON)

**Comment by arch0345** [comment]
These two sources are already included in ELI:
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/wa/King_WA_2019.geojson
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/wa/King_WA_2021.geojson

**Comment by bennettgoble** [comment]
@arch0345 ah, I must not have done a good job of searching. I had assumed since the sources didn't appear in JOSM's imagery provider list they hadn't been added.

Thanks, I will close this.
