### ISSUE TITLE
Reinstate NRW_Ortho as best for NRW

### ISSUE THREAD

**Issue by KAMiKAZOW** [osmlab/editor-layer-index#2262]
I don't know which area the new "best" sources cover but it's clearly not the whole of NRW:

![image](https://github.com/osmlab/editor-layer-index/assets/3259076/54e8c6d2-0d6a-4b9d-bd56-c8902f0dd19e)

![image](https://github.com/osmlab/editor-layer-index/assets/3259076/005c1378-1c33-4db8-b391-03f62b781c04)

Clearly only NRW_Ortho delivers good results over the whole of NRW:

![image](https://github.com/osmlab/editor-layer-index/assets/3259076/b98337b0-e4aa-4d00-ab68-544f3646aa2f)

**Comment by tordans** [comment]
We discussed this in https://github.com/openstreetmap/iD/issues/10090 and the result was that the `best` flag should only very be used on aerial imagery, never other categories.

We need to fix this here in the source but I think we will also need to update the docs on the `best` key in various places here.

Never got around to following up on it … – anyone who can pick this up?

**Comment by crackwitz** [comment]
Now we're getting "vDOP" as top choice, which is completely blank by now. It was a temporary source, shouldn't have been chosen in the first place.

"NRW Orthophoto" needs to be top choice in NRW.

Unless someone else is working on it, I'll swap the `"best"` properties of NRW vDOP and NRW Orthophoto, then open a PR.

**Comment by KAMiKAZOW** [comment]
How long does this change take to trickle into ID because currently it's still broken:

![image](https://github.com/osmlab/editor-layer-index/assets/3259076/a4ec5cee-6cc5-4f6f-8060-7474f2933cda)

**Comment by tordans** [comment]
I did not follow the discussion in the various thread recently, so I don't really know. However, I am quite certain that there was no PR, yet, that would make the "NRW Orthophoto" the "best" and remove "best" from all other, so I don't expect this to be solved, yet.

**Comment by tordans** [comment]
Here is the current state of availability for the three options:

## vDOP

<img width="1090" alt="image" src="https://github.com/osmlab/editor-layer-index/assets/111561/f6ebbf5b-4a23-49b8-aeb2-456998810b99">

## iDOP

<img width="1116" alt="image" src="https://github.com/osmlab/editor-layer-index/assets/111561/844eec67-8c0d-4dbc-b279-0140a4ada226">

## NRW Orthophoto

<img width="1118" alt="image" src="https://github.com/osmlab/editor-layer-index/assets/111561/109a0153-71b1-4349-bb10-0ff477ed5041">

**Comment by tordans** [comment]
I still think we should do two things:
1. Only mark "NRW Othophoto" the "`best`"
2. Change the wording for vDOP and iDOP to somehow explain what they are so users will test them to get fresher data

**Comment by crackwitz** [comment]
> there was no PR

Please see #2288

**Comment by tordans** [comment]
> Please see #2288

Agreed, that would solve (1), but we should also tackle (2).

**Comment by tordans** [comment]
Another solution would be so create a merged source of the data. Maybe someone can pick https://community.openstreetmap.org/t/nrw-vdop-idop-wms-dienste/107244/13 up.

**Comment by tordans** [comment]
> How long does this change take to trickle into ID because currently it's still broken:

I read up on the process again and [it looks like](https://github.com/openstreetmap/iD/blob/develop/RELEASING.md#update-develop-branch) ELI is bundled with iD when iD is released. So an update will only show with a new iD Release which happens every few month ATM.

Maybe +1 https://github.com/openstreetmap/iD/issues/10238 so get at least some clarity to this process in the UI.
