### ISSUE TITLE
icon for "LINZ-NZ-Bay-of-Plenty-2014" layer is broken

### ISSUE THREAD

**Issue by Manu1400** [osmlab/editor-layer-index#2270]
## Icon
https://koordinates.a.ssl.fastly.net/media/settings/branding/favicon-lds.ico return this error:
```
Fastly error: unknown domain: koordinates.a.ssl.fastly.net. Please check that this domain has been added to a service.

Details: cache-par-lfpg1960058-PAR
```

## source
https://github.com/osmlab/editor-layer-index/blob/c5d89189ea96b48e417dfb030b9ba5f69e08c7fc/sources/oceania/nz/LINZ-NZ-Bay-of-Plenty-2014.geojson#L18

### in raw geoJSON
https://raw.githubusercontent.com/osmlab/editor-layer-index/c5d89189ea96b48e417dfb030b9ba5f69e08c7fc/sources/oceania/nz/LINZ-NZ-Bay-of-Plenty-2014.geojson#L18:~:text=https%3A//koordinates.a.ssl.fastly.net/media/settings/branding/favicon%2Dlds.ico

**Comment by Manu1400** [comment]
## in Internet Archive
exist in https://web.archive.org/web/20240311083837/https://koordinates.a.ssl.fastly.net/media/settings/branding/favicon-lds.ico
### version March 11, 2024 (lasted version available)
https://web.archive.org/web/20240311083837if_/https://koordinates.a.ssl.fastly.net/media/settings/branding/favicon-lds.ico

**Comment by Manu1400** [comment]
## new logo (?)
https://basemaps.linz.govt.nz/favicon-32x32.png

**Comment by andrewharvey** [comment]
> ## new logo (?)
> https://basemaps.linz.govt.nz/favicon-32x32.png

That would be okay, but typically this index uses the logo of the organisation, so https://basemaps.linz.govt.nz/assets/logo-linz.svg might be better.
