### ISSUE TITLE
in some areas vector map, not aerial, is default

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/editor-layer-index#2272]
Is it intended for say https://www.openstreetmap.org/edit?editor=id#map=19/51.18137/7.17874 ?

Or is it iD not using all hints provided by ELI?

Default view:

![screen01](https://github.com/osmlab/editor-layer-index/assets/899988/ada2e2b2-4a3b-486c-bf0e-017bb8c06f10)

**Comment by tordans** [comment]
We discussed this in https://github.com/openstreetmap/iD/issues/10090 and the result was that the `best` flag should only very be used on aerial imagery, never other categories.

We need to fix this here in the source but I think we will also need to update the docs on the `best` key in various places here.

Never got around to following up on it … – anyone who can pick this up?

**Comment by tordans** [comment]
Lets close this as duplicate of https://github.com/osmlab/editor-layer-index/issues/2262

**Comment by matkoniecz** [comment]
Also fixed by #2277 - right?

**Comment by tordans** [comment]
@matkoniecz yes, but I did not check if any other "best" flags are in data the non-aerial imagery categories.
