### ISSUE TITLE
Add QGIS layer list support?

### ISSUE THREAD

**Issue by simon04** [osmlab/editor-layer-index#228]
QGIS allows to import/export WMS/WMTS layers via an XML file, for instance:

```xml
<qgsWMSConnections version="1.0">
    <wms ignoreGetMapURI="false" smoothPixmapTransform="false" dpiMode="7" password="" ignoreGetFeatureInfoURI="false" referer="" username="" url="http://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml" invertAxisOrientation="false" ignoreAxisOrientation="false" name="basemap"/>
</qgsWMSConnections>
```

**Comment by simonpoole** [comment]
At least some of the sources, most notably the bing (which itself is not a problem in that you need an API key in any case), only allow use in OSM for tracing objects and don't allow general use.

**Comment by Skippern** [comment]
I think there is a proper plugin for use of Bing with QGIS, besides as I understand WMS/WTMS is native support while TMS need a plugin, and Bing is a TMS type.

**Comment by andrewharvey** [comment]
I agree with @simonpoole these sources are only intended to be used for OSM contribution, however sometimes people use QGIS to inspect data with their contributor hat on.

Should this be internal to this repo? I wrote https://github.com/andrewharvey/osm-editor-layer-index-qgis but happy to move it here if people see any benefit or into osmlab if I'm granted access. Right now it's XYZ tiles only not WMS.

**Comment by grischard** [comment]
Is it ok for everyone if I add @andrewharvey's cool project to the README and close this ticket?

**Comment by simonpoole** [comment]
@andrewharvey my comment 2 years back was before https://github.com/osmlab/editor-layer-index/pull/344 was merged.  With the extra attributes we can model the allowed usage a lot better now, however we are still quite far from having information for all the layers (most notable the global layers are missing the attributes). 

So from that pov I have nothing against either putting your script in this repo or pointing to it. 

There is however the slight issue that users should be made aware of the restrictions, in particular when API keys have been made available only for OSM editing use (see https://github.com/osmlab/editor-layer-index/pull/548 and https://github.com/MarcusWolschon/osmeditor4android/issues/775 for more information).
