### ISSUE TITLE
special character in XML output

### ISSUE THREAD

**Issue by Klumbumbus** [osmlab/editor-layer-index#230]
at sources/south-america/cl/osmim-imagicode-LC82330892016031LGN00.geojson the name is `Volcán Calbuco`, which is not correctly moved to the XML output. It is `Volc&#225;n Calbuco` there.

**Comment by simon04** [comment]
What's the problem with `&#225;`? This is specified in https://www.w3.org/TR/2008/REC-xml-20081126/#sec-references and corresponds to the Unicode character `U+0225`:
```
U+0225 0x00e1    á  LATIN SMALL LETTER A WITH ACUTE                             
```

**Comment by Klumbumbus** [comment]
Hm I thought when I tried to copy it to the josm wiki it did not accept it. I tried again and it works now and is also displayed correctly within JOSM.
So basically the XML would look a bit nicer, but this is a very minor issue and can be closed as wontfix if you want.

**Comment by iandees** [comment]
I think this could be fixed if we specified UTF-8 encoding and added the required XML encoding header.
