### ISSUE TITLE
wrong <best /> statement in XML output

### ISSUE THREAD

**Issue by Klumbumbus** [osmlab/editor-layer-index#231]
for sources/misc/osmim-imagicode-LC81800982013291LGN00.geojson (and other sources with the best flag) the XML output conains a wrong single `<best />` statement

**Comment by tyrasd** [comment]
sorry, what's actually *wrong* here and how would the *correct* solution look like? I don't get it.

**Comment by Klumbumbus** [comment]
Sorry, I confused the xml syntax. The <best /> statement is ok.

(It is not yet used by JOSM, but will maybe in the future.)
