### ISSUE TITLE
Request: Multiple custom layers

### ISSUE THREAD

**Issue by endolith** [osmlab/editor-layer-index#2335]
Instead of having a single Custom layer that can be edited:

![image](https://github.com/osmlab/editor-layer-index/assets/58611/eb6b73e9-6b5a-4a41-a79b-2149cbe6f346)

I would like to be able to add multiple Custom layers.    I am constantly switching back and forth between [Strava Heatmap](https://github.com/zekefarwell/josm-strava-heatmap) and [the "Hillshade Multidirectional" version of 3DEP](https://wiki.openstreetmap.org/wiki/USGS_3D_Elevation_Program#Using_the_USGS_3DEP_Digital_Elevation_Model) (because the default "Hillshade Gray" 3DEP hides details in shadows when editing climbing cliffs) so I have to paste the URLs each time.

The simplest way to do this would probably just be to add a few more, so it's like "Custom 1" "Custom 2" "Custom 3" instead of just a single Custom slot.

**Comment by simonpoole** [comment]
This is the wrong repo for this request, you should open an issue on the iD issuse tracker https://github.com/openstreetmap/iD

This repo contains the configuration data for layers and is not specific to iD or iDs layer implementation.

**Comment by 1ec5** [comment]
If you want the Hillshade Multidirectional layer, you can request that layer in this repository, so that others will find it without having to fashion a URL template themselves.

**Comment by endolith** [comment]
@1ec5  It was requested but they only added the one layer type: https://github.com/osmlab/editor-layer-index/issues/1490#issuecomment-1616106248
