### ISSUE TITLE
au/act urls will need to be updated due to server shutdown 31 May 2024.

### ISSUE THREAD

**Issue by FrakGart** [osmlab/editor-layer-index#2340]
The ACT Government is shutting down their server on 31 May 2024 and will be moving to an ArcGIS hosted server.

I have updated the JOSM map list to match this: https://josm.openstreetmap.de/wiki/Maps/Australia

https://josm.openstreetmap.de/wiki/Maps/Australia#ACTmapiImagery2024-02 is available in EPSG:3857, so should work in iD. The other three layers are only available in EPSG:7855, so only usable in JOSM I think.

Thanks.

**Comment by davidhicks** [comment]
ArcGIS tileserver: https://tiles.arcgis.com/tiles/E5n4f1VY84i0xSjy/arcgis/rest/services/

It appears that GDA2020 may be used instead of WGS84 in the tile URLs.

**Comment by FrakGart** [comment]
I think you'll find that none of the layers in the ELI use "WGS84". They all use whatever the local realization of the ITRS is.
GDA2020 is the current AU version.
