### ISSUE TITLE
Automatically make and publish to gh-pages

### ISSUE THREAD

**Issue by simon04** [osmlab/editor-layer-index#236]
To get rid of manual building and #33, we could let Travis run `make` and publish the `imagery.*` files to the branch `gh-pages`. To get there:

1. Prepare `master` and `gh-pages` branches
* Branch `master` from `gh-pages` and remove the output files, i.e., `imagery.*` and maybe `site/`+`index.html`
* For `gh-pages`, remove `scripts/` and `source/`
* Make `master` the default branch on GitHub

2. Let Travis do the work (run `make` on every push to `master`) by following one of those tutorials
* https://iamstarkov.com/deploy-gh-pages-from-travis/
* https://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/
* https://iamstarkov.com/deploy-gh-pages-from-travis/

**Comment by iandees** [comment]
I'd rather see us remove the imagery.* files and put them in the Github releases section (as proposed in #214) than to auto-commit stuff to `gh-pages`.

**Comment by simon04** [comment]
This proposal does not contradict/exclude #214. We can have releases, and `gh-pages` containing the current state of the imagery files.

**Comment by iandees** [comment]
One of the goals of 214 was to stop committing compiled artifacts to git, though. Committing them to gh-pages just puts them in a different place.

**Comment by tyrasd** [comment]
> stop committing compiled artifacts to git

The question is then how we can continue to provide the current imagery preview page (see #160) on https://osmlab.github.io/editor-layer-index/. Maybe it would make sense to have the sources without the compiled assets on a `master` branch, and use an automatic deploy script that updates the preview site on the `gh-pages` branch?

**Comment by grischard** [comment]
Now that the generation date is included in imagery.*, merging simultaneous PRs can get complicated, and it might be worth reviving this.

So we have the users commit to master, and from there, using travis, compile the assets to gh-pages?

Should we also add imagery.* to .gitignore?

**Comment by grischard** [comment]
This was more complicated than I expected, but it's done now! PRs shouldn't include imagery.* files anymore; they'll automatically be generated by travis. Everything else stays the same.

**Comment by simonpoole** [comment]
With other words the default branch is continues to be gh-pages?

**Comment by grischard** [comment]
Many thanks to @tomhughes, @derickr and @Marc-marc-marc for your help.

**Comment by grischard** [comment]
@simonpoole yes, the default branch continues to be gh-pages. I'm definitely not against using 'master', but I like how having just one branch is newbie-friendly.
