### ISSUE TITLE
City of Bern (CH) WMS out of service

### ISSUE THREAD

**Issue by das-g** [osmlab/editor-layer-index#2365]
See also https://community.openstreetmap.org/t/update-needed-for-bern-web-map-services-in-osm-editor-layer-index/114852

The WMTS [Bern-AmtlicheVermessung](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/ch/Stadt_Bern-Amtliche-Vermessung-farbig-WMTS.geojson?short_path=cfa80df) still works. All layers of the WMS which used to provide the aerial imagery [Stadt Bern 10cm (2016)](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/ch/Stadt_Bern_10cm-2016-WMS.geojson) and [Stadt Bern 10cm (2020)](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/ch/Stadt_Bern_10cm-2020-WMS.geojson) are now disabled, even though they are still listed [on that website](https://www.bern.ch/open-government-data-ogd/ogd-nach-themen/geodaten-ogd#ftw-simplelayout-textblock-1).

In [Geodatenkatalog](https://map.bern.ch/geoportal/#/geodatenkatalog) only downloads of extracts of small areas (to be delivered by e-mail) can be ordered, it seems.

But working WMS & WMTS URLs can still be obtained: Go to https://map.bern.ch/stadtplan/, click "Karten" at the bottom right, then for the wanted layer, click "Datenbezug". Click on the link "WMS" or "WMTS" in section "Service Schnittstellen". That'll open a modal dialog within the website displaying the WMS or WMTS URL, together with a button to copy it.

**Comment by habi** [comment]
JOSM has a working URL for the newest available images from the city of Bern from 2023: https://josm.openstreetmap.de/wiki/Maps/Switzerland#StadtBern10cm2023

**Comment by grischard** [comment]
#2409 fixed this, thanks!
