### ISSUE TITLE
Specify xmlns for imagery.xml?

### ISSUE THREAD

**Issue by simon04** [osmlab/editor-layer-index#237]
The `imagery.xml` structure has been taken from [JOSM's map file](https://josm.openstreetmap.de/map) without doubt. However, the file does not specify a namespace. Thus, questions like #231 cannot be answered.

Adding a namespace is simple, but it might introduce problems for some consumers of `imagery.xml`.
```patch
diff --git a/scripts/convert_xml.py b/scripts/convert_xml.py
index e1d9491..fa46e89 100644
--- a/scripts/convert_xml.py
+++ b/scripts/convert_xml.py
@@ -2,6 +2,7 @@ import json, sys, string, util, io
 import xml.etree.cElementTree as ET

 root = ET.Element("imagery")
+root.set('xmlns', 'http://josm.openstreetmap.de/maps-1.0')

 sources = []
 for file in sys.argv[1:]:
```

**Comment by iandees** [comment]
What sort of problems do you foresee?

**Comment by simon04** [comment]
For instance when using [XPath](https://docs.oracle.com/javase/7/docs/api/javax/xml/xpath/XPath.html) in Java, "QNames in the expression are resolved against the XPath namespace context set with `setNamespaceContext`".

**Comment by rbuffat** [comment]
It would be certainly good to include the namespace. But as only JOSM uses the XML format (And I assume not many people use the ELI imagery.xml with JOSM and to my knowledge there were no reports of any issues in the last years) I'm inclined to close this issue. Other projects should preferably use the imagery.geojson.
