### ISSUE TITLE
Imagery layers with incompatible license

### ISSUE THREAD

**Issue by Swarkin** [osmlab/editor-layer-index#2456]
_Originally posted by @miche101 in https://github.com/osmlab/editor-layer-index/issues/2438#issuecomment-2304666909_

There is an error in this file:
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/BY_Label.geojson?short_path=b6559cf

From min_zoom=7 to 17 the images are CC-BY 4.0. From 18 to 22 the image changes to a CC BY ND 4.0 image.

From ( CC BY 4.0 )
https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=dok

To  ( CC BY-ND 4.0 )
https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=parzellarkarte

**Comment by iandees** [comment]
Are you concerned with just this source from zooms 18 to 22? Are there other layers with this concern?

**Comment by Swarkin** [comment]
I am not aware of any other layers that have obvious licensing issues.

**Comment by miche101** [comment]
Overview:
https://geodaten.bayern.de/opengeodata/index.html



I looked at all zoom levels and compared them with the ones offered

BY_Label

(errors > z19)

z18-19
https://wmtsod7.bayernwolke.de/wmts/by_amtl_karte/smerc/19/279349/181808
https://wmtsod6.bayernwolke.de/wmts/by_amtl_karte/smerc/18/139674/90902
**CC BY-ND 4.0** https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=parzellarkarte

z15-17
https://wmtsod7.bayernwolke.de/wmts/by_amtl_karte/smerc/17/69834/45453
https://wmtsod7.bayernwolke.de/wmts/by_amtl_karte/smerc/16/34917/22725
https://wmtsod4.bayernwolke.de/wmts/by_amtl_karte/smerc/15/17459/11362
**CC BY 4.0** https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=dok

z14
https://wmtsod3.bayernwolke.de/wmts/by_amtl_karte/smerc/14/8731/5680
**CC BY 4.0** https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=dtk25

z13
https://wmtsod6.bayernwolke.de/wmts/by_amtl_karte/smerc/13/4366/2839
**CC BY 4.0** https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=dtk100

z12
https://wmtsod2.bayernwolke.de/wmts/by_amtl_karte/smerc/12/2183/1418
**CC BY 4.0** https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=dtk500

z11
https://wmtsod8.bayernwolke.de/wmts/by_amtl_karte/smerc/11/1090/708
?

z10
https://wmtsod9.bayernwolke.de/wmts/by_amtl_karte/smerc/10/543/356
?

z9
https://wmtsod6.bayernwolke.de/wmts/by_amtl_karte/smerc/9/270/176
**CC BY 4.0** https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=tk2000

z8
https://wmtsod8.bayernwolke.de/wmts/by_amtl_karte/smerc/8/136/87
?

z7
https://wmtsod3.bayernwolke.de/wmts/by_amtl_karte/smerc/7/68/42
?

**Comment by arch0345** [comment]
Thanks for bringing this to my attention. I've adjusted the max_zoom for `BY_Amtl_Karte` in https://github.com/osmlab/editor-layer-index/commit/8141a2682a8baacbb7f630057cc0b18f7d6f340a and removed `BY_Label` in https://github.com/osmlab/editor-layer-index/commit/e0e1f36ad86e989b13ce41251dfea1ac3e675882 as the parcel layer seems to show up starting at z16
