### ISSUE TITLE
Fresno, California ?

### ISSUE THREAD

**Issue by darkblue-b** [osmlab/editor-layer-index#253]
Hi - with a local copy, I am running just this web page, looking at California. However, I can see a BOX around Fresno area, but clicking inside and then outside of the Fresno BOX shows only the same six layers available.. any clue ?  --Brian

**Comment by darkblue-b** [comment]
Tuscon, Modesto, Stockton, Sacramento also... BOX shown, not matching on click ?

**Comment by darkblue-b** [comment]
thanks simonpoole - solved. It is part of the MSR Maps Urban set, in a non-obvious way.

**Comment by simonpoole** [comment]
would leave this open for now as it points to a website bug MSRMapsUrban should turn up as a source when you click there, but it doesn't.

**Comment by darkblue-b** [comment]
ok - leave as open pending MSRMapsUrban clarification

**Comment by grischard** [comment]
I'm not sure how this can be reproduced, and what needs to happen to fix this. Clicking on Fresno on https://osmlab.github.io/editor-layer-index/ does show MSRMapsUrban for me?

**Comment by grischard** [comment]
If anyone wants to reactivate this, please ping me.
