### ISSUE TITLE
Bug with Custom Background

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/editor-layer-index#2554]
In French Guyana the best imagery (more recent) is Here imagery. Example (building is built):
https://1.aerial.maps.ls.hereapi.com/maptile/2.1/maptile/newest/satellite.day/18/92976/127472/256/png8?app_id=pcXBZARHILwXlCihx8d6&token=dzJKV7oQT-zs-vRT_KqiLA
to compare with the official best imagery BDOrtho IGN (building is under construction):
https://data.geopf.fr/tms/1.0.0/ORTHOIMAGERY.ORTHOPHOTOS/18/92976/127472.jpeg

But when I enter in the custom background settings the tiles url: https://1.aerial.maps.api.here.com/maptile/2.1/maptile/newest/satellite.day/{z}/{x}/{y}/256/png8?app_id=pcXBZARHILwXlCihx8d6&token=dzJKV7oQT-zs-vRT_KqiLA, custom background is blocked, impossible to access to the radio.

Could you fix that ?

**Comment by simonpoole** [comment]
We do not have permission to use imagery provided by Here. Use is blocked by the OSM API.

**Comment by Mahabarata** [comment]
Ok.
