### ISSUE TITLE
Brandenburg DOP with big offset

### ISSUE THREAD

**Issue by vizsim** [osmlab/editor-layer-index#2568]
The Basemap DOP in Brandenburg/Germany is by 1-2km off in the ID Editor:

https://www.openstreetmap.org/edit#map=16/52.19704/14.02336
![grafik](https://github.com/user-attachments/assets/2a08546e-b5c8-4d19-813b-c11c6186d979)

https://www.openstreetmap.org/edit#map=14/52.21360/14.02621
![grafik](https://github.com/user-attachments/assets/6e7329c6-76d6-4073-9a73-5385e750efc7)

@tordans, you know what happend here?

**Comment by tordans** [comment]
@vizsim I can confirm the issue but have no idea why that would happen out of the blue
Testlinks: 
- Correct: [Imagery from Berlin/Berlin Server](https://ideditor.netlify.app/#background=Berlin-2024&disable_features=boundaries&locale=en&map=19.59/52.47323/13.45380)
- Wrong: [Imagery from Brandenburg/Same Location in Berlin but Server from Brandenburg)](https://ideditor.netlify.app/#background=Brandenburg-DOP20c&disable_features=boundaries&locale=en&map=19.59/52.47323/13.45380)

They did [update the data recently](https://geobasis-bb.de/lgb/de/presse/pressemitteilung/~20-11-2024-datenaktualisierung-truedop), but that could only be an indicator that something might have changed by accident at the same time…

I will ask in the Matrix channel if anyone knows more…

~Maybe someone can ask at `kundenservice@geobasis-bb.de` what is going on?~ – See below

---

This is the imagery source https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/Brandenburg-DOP20c.geojson?short_path=d649216

**Comment by vizsim** [comment]
Thanks!
When I load the given WMS Layer ( https://isk.geobasis-bb.de/mapproxy/dop20c/service/wms?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=bebb_dop20c ~~&STYLES=&crs={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}~~ ) in QGIS, it seems to be fine:
![grafik](https://github.com/user-attachments/assets/aefd3d85-3c5c-4794-bd1c-86444a6f8935)

Therefore I would assume that the import is rather/also the problem here. However I do not understand the process completely.

EDIT: Note to my self: I loaded the "default" 4326 into QGIS and viewed it as 3857, which was correct. Probably I should have tested to load the 3857 directly to see the offset.

**Comment by tordans** [comment]
That is good to know. Will write an email to them and ask them to check their Mapproxy settings since that is the URL we use and I am not aware of a way to debug this further from our end.

> `"url": "https://isk.geobasis-bb.de/mapproxy/dop20c/service/wms?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=bebb_dop20c&STYLES=&crs={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}"`

**Comment by tordans** [comment]
FYI
> Siehe auch dieser Thread im Forum (https://community.openstreetmap.org/t/achtung-zur-zeit-lageversatz-bei-echtfarbluftbildern-brandenburg/122309) - scheint nicht in unserer Macht zu liegen, sondern deren WMS-Quelle hat gerade einen fehlerhaften Versatz
> Wer nicht bis zur Korrektur warten mag, kann einen eigenen Versatz im Editor einstellen

**Comment by tordans** [comment]
Someone from geobasis-bb.de  answered just now:

> Liebe Nutzerinnen und Nutzer des DOP20c WMS,
> 
>  
> 
> der Lageversatz in EPSG:3857 ist korrigiert.
> 
>  
> 
> Mit freundlichen Grüßen
> 
> Im Auftrag
> …
> 

I can confirm that …
> Wrong: [Imagery from Brandenburg/Same Location in Berlin but Server from Brandenburg)](https://ideditor.netlify.app/#background=Brandenburg-DOP20c&disable_features=boundaries&locale=en&map=19.59/52.47323/13.45380)

… now works

**Comment by tordans** [comment]
@vizsim kannst du das Ticket wieder schließen? Danke.
