### ISSUE TITLE
Script to support WMTS services

### ISSUE THREAD

**Issue by Skippern** [osmlab/editor-layer-index#272]
PR #271 is failing tests due to lack of support for WMTS services, I tested the settings in JOSM, and it works nicely, see URL in PR comment.

**Comment by tyrasd** [comment]
I think this would only make sense for WMTS services that don't support EPSG:3857, as ones who do can be also expressed as regular TMS sources, which are more easily and commonly implemented in software that's consimung this repository.

**Comment by Skippern** [comment]
Isn't one of the purposes with supporting WMTS to have an enhanced support for a more advanced system than TMS? A single WMTS call could yield access to multiple layers on the same service, i.e. the same imagery with and without NIR, instead of adding them as multiple instances.

**Comment by rbuffat** [comment]
There are now checks for WMTS sources: https://github.com/osmlab/editor-layer-index/blob/gh-pages/scripts/strict_check.py#L563-L616
