### ISSUE TITLE
Add Canberra ACT, Australia imagery

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/editor-layer-index#297]
Thread:
https://lists.openstreetmap.org/pipermail/talk-au/2017-March/011286.html

Will flesh out the other details required in a bit

## URL of the imagery
(required)
WMS - http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/imagery2016mga/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

On the mailing list there is a suggestion:
>  it would be nice if we could find somebody to run a mapproxy instance or similar so
> that it could be used in iD and other editors that don't support WMS
> servers. We (SOSM) would likely offer, but it doesn't really make sense
> to ship the bits around half the globe and back again.

## Two letter country code
AU

## Desired layer name
ACT2016 (28355)

## License
CC-BY-4.0

## Is the license compatible with OSM?
We have been given explicit permission from ACTMapi to incorporate their CC-BY licensed datasets into OpenStreetMap provided that this attribution is made on contributions page

## Attribution (text, URL, required?)
https://wiki.openstreetmap.org/wiki/Contributors#Australian_Capital_Territory_Government_data

## Icon
(optional)

## Boundary polygon
(if possible, provide a boundary polygon, e.g. as a GeoJSON or OSM file.)
http://actmapi-actgov.opendata.arcgis.com/datasets/5739476ddd854f3b9f47bef679378f30_1 ? (Might have to investigate that a bit more/convert format)

**Comment by mbainrot** [comment]
An extension to mapproxy idea would be to reproject the imagery from EPSG:28355 to EPSG:3857, going to see how hard it is to setup MapProxy and if I can get it working in a VM I'll see if I can't whip up a docker thingo to allow people to reproject locally

**Comment by andrewharvey** [comment]
I've sent off an email to see if the source can provide this in EPSG:3857. Will report back on how that goes.

**Comment by andrewharvey** [comment]
I've been in contact with ACTmapi about completing the waiver as supplied by OSMF https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/, however they've come back that they can't waive the terms of their CC BY licensing, which goes in directly conflict with the explicit permission @CloCkWeRX linked too. I'm following up to try to resolve this, but I suggest we don't use the ACTmapi imagery or data until we have a completed waiver form.

On the imagery reprojection front they've indicated that they can provide the imagery on a hard drive and we can reproject so unlikely they'll be able to offer it as a service in web mercator.

**Comment by andrewharvey** [comment]
Just an update ACT are planning on getting NSW to include the latest ACT imagery in the NSW Imagery layer, which would make this unnecessary (at least until ACT update their imagery again).

**Comment by andrewharvey** [comment]
NSW haven't updated to the latest ACT Imagery, however we just got the CC BY waiver completed so I've opened #446 to bring in the ACT Imagery.

It's only in EPSG:4326 and EPSG:28355, but that works fine in JOSM and iD should support it via https://github.com/openstreetmap/iD/issues/4843
