### ISSUE TITLE
updating imagery.json

### ISSUE THREAD

**Issue by joostschouppe** [osmlab/editor-layer-index#305]
[It looks like](http://www.openstreetmap.org/user/Richard/diary/40740) Potlatch is powered by this [imagery.json](http://osmlab.github.io/editor-imagery-index/imagery.json): `http://osmlab.github.io/editor-imagery-index/imagery.json`. But I can't seem to find any of [the Belgian layers](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/be) there,  even though the oldest of them was added back in september 2016.

Is this file still updated? Is there a better way to feed Potlatch? Am I completely missing the point? (that happens)

**Comment by Klumbumbus** [comment]
According to http://www.openstreetmap.org/user/Richard/diary/40740#comment38193 it seems P2 uses an outdated URL.

The latest json file is here: https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/imagery.json

**Comment by systemed** [comment]
I'm not convinced that's going to work. Flash Player (in a CORS-like manner) needs a crossdomain.xml at root level to access content on a remote domain. osmlab.github.io has one:

http://osmlab.github.io/crossdomain.xml

but (unsurprisingly) raw.githubusercontent.com doesn't:

https://raw.githubusercontent.com/crossdomain.xml

So redirecting P2 to the raw.githubusercontent.com copy will likely break it.

Given that http://osmlab.github.io/editor-imagery-index/ still appears to be a live site it would be good to resuscitate the earlier URL, I think.

**Comment by tyrasd** [comment]
@systemed: you can also use https://osmlab.github.io/editor-layer-index/imagery.json, which should work exactly the same as the old `…editor-imagery-index/imagery.json` url.

**Comment by tyrasd** [comment]
> Given that http://osmlab.github.io/editor-imagery-index/ still appears to be a live site it would be good to resuscitate the earlier URL, I think.

I'm not sure why this url still exists / doesn't redirect to the new repo name, like https://github.com/osmlab/editor-imagery-index does. Hmm…

**Comment by systemed** [comment]
Cool, thank you. I've updated the P2 source and it'll be reflected on osm.org next time there's a rebuild there.
