### ISSUE TITLE
More tms backgrounds (Saxony, Berlin)

### ISSUE THREAD

**Issue by hakuchi** [osmlab/editor-layer-index#317]
is there a way to add more backgrounds in tms format to the list?

In Josm a lot more backgrounds(Saxony, Berlin) as in iD or Potlatch2 and if they get implemented into this list in tms format, all three editors can use the backgrounds.

**Comment by Klumbumbus** [comment]
You can't add a source as TMS if there is only WMS available.

**Comment by hakuchi** [comment]
I have no idea how to use mapproxy or make a server with this.

some background in the index list just using mapproxy or other tms server:
**Bavaria DOP 80cm:**
wms: http://www.geodaten.bayern.de/ogc/ogc_dop80_oa.cgi?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=by_dop80c&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
tms: http://mapproxy.osm.ch:8080/tiles/BAYERNDOP80/EPSG900913/{zoom}/{x}/{y}.png?origin=nw
**Geoimage.at MaxRes:**
tms from OSM wiki: http://geoimage.openstreetmap.at/4d80de696cd562a63ce463a58a61488d/$z/$x/$y.jpg
**Delaware 2012 Orthophotography**
**NJ 2015 Aerial Imagery (Natural Color)**

If there can someone make a tms for the wms, i think this is not a disadvantage. I don't know if the terms of use from Saxony or Berlin allow using mapproxy.
I use some time the tms from **geoimage.at**(http://geoimage.openstreetmap.at/4d80de696cd562a63ce463a58a61488d/{z}/{x}/{y}.jpg). Also I used some time the [whoots.mapwarper.net](http://whoots.mapwarper.net/), but it is some times a little slow.

**Comment by grischard** [comment]
It's unclear to me what needs to be done to close this. @hakuchi, what are the URLs of the sources you want to add?

**Comment by grischard** [comment]
If anyone wants to reactivate this, please ping me.
