### ISSUE TITLE
Add "Actueel_ortho25" WMTS layer as "best" imagery for the Netherlands

### ISSUE THREAD

**Issue by AllroadsNL** [osmlab/editor-layer-index#326]
Redirected from
https://forum.openstreetmap.org/viewtopic.php?id=58096

In the Netherlands, we have now the newest Goverment Aerial Ortho Images, 2016 and 2017 is coming in a most recent actual version.
In [JOSM](https://josm.openstreetmap.de/wiki/Maps/Netherlands), it is in default entries.

In all editors:
In a country, when zooming in there must be a warning, that there is a newer/better aerial available and maybe set as default for that country.

Now, retags to older situations, this must be avoided. To get a better map quality.

What do you think?

I think there must be rules for editors to use the best possible layer in a area.
The setup of a editors, largely determine the quality of the mapping.

BING and Digtial Globe is not everywhere the best solution.
In the Netherlands for years BING was the best, thanks, but now all Openstreetmap mappers must be guided to the new ones.

**Comment by simonpoole** [comment]
As I already pointed out to you on the forum: you simply need to provide a coverage polygon and an entry for your imagery source (or at least the information so that somebody else can author such an entry).

**Comment by osmned** [comment]
See attachment for the polygon file (matching the border of the Netherlands). 
[Netherlands.zip](https://github.com/osmlab/editor-layer-index/files/994608/Netherlands.zip)

The imagery source is wms:http://geodata.nationaalgeoregister.nl/luchtfoto/wms?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=2016_ortho25&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

Is this sufficient to change the 2010 BING layer to the 2016 Netherlands aerial photos?

**Comment by tyrasd** [comment]
@osmned: Since you mention that this layer is already present in JOSM, I assume you're most interested in getting it into iD, right? But this layer is a `WMS` source, which isn't supported by iD [yet](https://github.com/openstreetmap/iD/issues/1141). I found a WMTS service running on the same server, which would work in iD: 

    http://geodata.nationaalgeoregister.nl/luchtfoto/wmts?FORMAT=image/jpeg&SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=2016_ortho25&STYLE=&FORMAT=image/jpeg&tileMatrixSet=OGC:1.0:GoogleMapsCompatible&tileMatrix={zoom}&tileRow={y}&tileCol={x}

But I'm not 100% sure if this WMTS service is allowed to be consumed under the same terms as the corresponding WMS service. I would assume it is, but can you please check and confirm if that is really the case?

Can you please also provide all remaining information about this imagery layer, as pointed out in our [issue template](https://github.com/osmlab/editor-layer-index/blob/gh-pages/ISSUE_TEMPLATE.md)? I guess we can copy-paste most stuff from the JOSM entry you linked above, but as far as I can see that one is a slightly different layer (`Actueel_ortho25` instead of `2016_ortho25`), so some metadata might differ.

Thanks!

**Comment by AllroadsNL** [comment]
PDOK Luchtfoto Beeldmateriaal 25cm Actueel ortho25 (WMS)
PDOK Luchtfoto Beeldmateriaal 25cm Actueel ortho25 (WMTS)

Licence:
CC-BY-4.0 , with explicit permission

Announcement:
https://forum.openstreetmap.org/viewtopic.php?id=57298

Attribution:
NO, is generally regulated.
https://wiki.openstreetmap.org/wiki/Contributors#Kadaster.2FBeeldmateriaal

Official metadata:
Luchtfoto Beeldmateriaal / PDOK 25 cm RGB WMS
http://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/a301ddc7-c26f-42d8-b367-509ae5ae47d0
Luchtfoto Beeldmateriaal / PDOK 25 cm RGB WMTS
http://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/c82a783a-9a58-4761-a809-b4c5d90dcd35


(Actueel_ortho25 instead of 2016_ortho25),
The metadata does not differ.
Actueel are the newest tiles, The best for OSM to map.
The years layers are not advised to use.

Intrested use:
Of course, in ID but for all editors.

Second part of this issue, the problem:
HOW to avoid the use of less quality layers.
MORE important is that the editors software is made so, that the best layer is used for mapping, to get better OSM data quality.
Should be basic rule for development a editor.
The mappers must be pointed to that, a warning!

Now, I see mappers in the Netherlands use BING which is outdated.
The map should be switched, before somebody draw new elements, modified elements.
A task of the editor!

WM(T)S and ID
There is this [workaround](https://forum.openstreetmap.org/viewtopic.php?pid=631139#p631139)
Is there a better solution?

**Comment by simonpoole** [comment]
@AllroadsNL once the imagery has the best flag set in the index it will be the default/highest listed imagery for the coverage polygon in iD and other editors.

**Comment by tyrasd** [comment]
> WM(T)S and ID
> There is this workaround
> Is there a better solution?

What do you mean? WMTS sources work fine in iD (try the URL I posted [above](https://github.com/osmlab/editor-layer-index/issues/326#issuecomment-301014103)). No worries ;-)
