### ISSUE TITLE
NC Latest Orthoimagery link is incorrect

### ISSUE THREAD

**Issue by jumbanho** [osmlab/editor-layer-index#336]
The new url is: 

https://services.nconemap.gov/secure/services/Imagery/Orthoimagery_Latest/ImageServer/WMSServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

**Comment by Klumbumbus** [comment]
Thanks.

**Comment by jumbanho** [comment]
They just changed it again to: 

https://services.nconemap.gov/secure/services/Imagery/Orthoimagery_All/ImageServer/WMSServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
