### ISSUE TITLE
Add National Land Survey of Finland orthophotos

### ISSUE THREAD

**Issue by theel0ja** [osmlab/editor-layer-index#337]
When **requesting the addition of an imagery layer**, please provide the following information. Otherwise, delete the text and type your issue.

## URL of the imagery

http://www.maanmittauslaitos.fi/en/maps-and-spatial-data/expert-users/product-descriptions/orthophotos

Unofficial TMS server (The official WMS server needs contract): http://tiles.kartat.kapsi.fi/ortokuva/{zoom}/{x}/{y}.jpg

## Two letter country code
FI

## Desired layer name
Some suggestions:

* Maanmittauslaitoksen ortokuva
* National Land Survey of Finland Ortophotos

## License
CC-BY-4.0

http://www.maanmittauslaitos.fi/en/maps-and-spatial-data/expert-users/en-maastotiedot-ja-niiden-hankinta/open-data-cc-40-licence

## Is the license compatible with OSM?
Yes.

https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/

## Attribution (text, URL, required?)
"Mention the name of the Licensor, the name of the dataset(s) and the time when the National Land Survey has delivered the dataset(s) (e.g.: contains data from the National Land Survey of Finland Topographic Database 06/2014)"

Some mappers have this in their changesets:
```source=MML Ortokuva```

## Boundary polygon
(if possible, provide a boundary polygon, e.g. as a GeoJSON or OSM file.)

**Comment by bhousel** [comment]
Hey @theel0ja, I just tried this tile url in iD but it did not work - it just returns various 5xx errors.
Is there an updated tile server that is hosting the imagery?  Thanks!

**Comment by theel0ja** [comment]
It seems to be working nicely on my machine..

![image](https://user-images.githubusercontent.com/5832930/28748181-a5b77f52-74b9-11e7-9036-d25bbe47f86a.png)

**Comment by theel0ja** [comment]
Fixed by #477.
