### ISSUE TITLE
Add Orthophotograph of Vantaa

### ISSUE THREAD

**Issue by theel0ja** [osmlab/editor-layer-index#338]
City of Vantaa's orthophotograph.
NOTE: Not only Vantaa area, has also parts of City of Helsinki and other municipalities.

## URL of the imagery
http://www.hri.fi/en/dataset/vantaan-ortokuva-2015

WMS server: http://gis.vantaa.fi/geoserver/wms

## Two letter country code
FI

## Desired layer name
Orthophotograph of Vantaa

## License
CC BY 4.0

## Is the license compatible with OSM?
Yes.

https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/

## Attribution (text, URL, required?)
"Source: Orthophotograph of Vantaa 2015. The administrator of this data is Vantaan kaupungin kuntatekniikan keskus. The data has been downloaded from the Helsinki Region Infoshare service 29.05.2017 using the license Creative Commons Nimeä 4.0 Kansainvälinen (CC BY 4.0)."

## Icon
(optional)

## Boundary polygon
(if possible, provide a boundary polygon, e.g. as a GeoJSON or OSM file.)

**Comment by tyrasd** [comment]
Hi. Thanks for the suggestion(s)!

But how is the [*use of cc by data*](https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/) blog article relevant in this case? Isn't that one only talking about cc-by databases, while here we talk about deriving information from cc-by licensed raster data? Afaik, we still need a special permission to use such cc by 4.0 licensed imagery in OSM.

This applies to #339 as well.

**Comment by theel0ja** [comment]
Ok, what about #337?

**Comment by tyrasd** [comment]
> Ok, what about #337?

Oh, totally overlooked that one. Yes, #337 has the same issue.

> https://www.openstreetmap.org/copyright […] NLSFI License.

OK, so special permission might already be given for using these layers in OSM? Not sure why it says *NLSFI License*, though. It might be about a different data set?

**Comment by theel0ja** [comment]
@tyrasd NSLFI License is the old license (datasets before 15.1.2015)

**Comment by theel0ja** [comment]
`waitfor - license permission` should be added, too.

**Comment by NKAmapper** [comment]
#532

**Comment by grischard** [comment]
Added in #532.
