### ISSUE TITLE
Add Orthophotograph of Espoo

### ISSUE THREAD

**Issue by theel0ja** [osmlab/editor-layer-index#340]
City of Espoo's orthophotograph.

## URL of the imagery
https://www.avoindata.fi/data/en/dataset/espoon-ortokuva-vuodelta-2015

WMS server: https://kartat.espoo.fi/teklaogcweb/wms.ashx

## Two letter country code
FI

## Desired layer name
Orthophotograph of Helsinki

## License
CC BY 4.0

## Is the license compatible with OSM?
Yes.
https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/

## Attribution (text, URL, required?)
"Espoon ortokuva vuodelta 2015 by Espoon kaupungin tekninen ja ympäristötoimi / kaupunkitekniikan keskus is licensed under a Creative Commons Attribution 4.0 International License."

## Icon
(optional)

## Boundary polygon
(if possible, provide a boundary polygon, e.g. as a GeoJSON or OSM file.)

**Comment by theel0ja** [comment]
`waitfor - license permission` should be added, too.

**Comment by NKAmapper** [comment]
#339

**Comment by NKAmapper** [comment]
#532

**Comment by grischard** [comment]
Added in #532.
