### ISSUE TITLE
Add Hydda [global OSM basemap layer]

### ISSUE THREAD

**Issue by magol** [osmlab/editor-layer-index#347]
## URL of the imagery

1. {switch:a,b,c,d,e,f}.tile.openstreetmap.se/hydda/full/{zoom}/{x}/{y}.png
2. {switch:a,b,c,d,e,f}.tile.openstreetmap.se/hydda/base/{zoom}/{x}/{y}.png
3. {switch:a,b,c,d,e,f}.tile.openstreetmap.se/hydda/roads_and_labels/{zoom}/{x}/{y}.png

## Two letter country code
sv or global

## Desired layer name

1. Hydda - Full
2. Hydda - Base
3. Hydda - Roads and Labels

## License
Apache License 2.0

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
I don't know, maybe a reference to http://hydda.se or https://github.com/karlwettin/tilemill-style-hydda?

I have to ask @joakimfors and @kodapan what they think.

On [leaflet-providers](https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js#L212), they use following (see issue [#96](https://github.com/leaflet-extras/leaflet-providers/issues/96)):

> Tiles courtesy of <a href="http://openstreetmap.se/" target="_blank">OpenStreetMap Sweden</a> &mdash; Map data OpenStreetMap

## Icon
(optional)

## Boundary polygon
global

**Comment by tyrasd** [comment]
Do you know which area is covered by this imagery? At least having a bounding box of the covered area would be great.

**Comment by Abbe98** [comment]
Hydda is just a OSM style (and therefor licensed under ODBL).

Page about the service (in Swedish):
http://openstreetmap.se/tjanster

**Comment by tyrasd** [comment]
Ah, I see, it's available globally. (I was a bit mislead by the *"… for Sweden"* in the ticket title :wink: )

**Comment by tyrasd** [comment]
Btw, the `{z}` parameter should instead read `{zoom}` to be fully compatible with the schema in this repository and we use `{switch:a,b,c}` to indicate the subdomains.

**Comment by magol** [comment]
@tyrasd It is created for Swedish use, but it is absolutely usable in the rest of the world to :-)
I have change the URL to match the schema in the repository

**Comment by c933103** [comment]
http://b.tile.openstreetmap.se/hydda/full/3/6/3.png Please consider improving the language support for the style to display characters in different languages correctly instead of just displaying them as boxes if it's intended to be used for all area...

**Comment by grischard** [comment]
@c933103 this isn't the project that maintains those tiles, we're just a humble imagery index. Try https://github.com/karlwettin/tilemill-style-hydda maybe?

**Comment by don-vip** [comment]
Server is [down for 8 months now](https://github.com/leaflet-extras/leaflet-providers/issues/351), I guess this issue should be closed.

**Comment by magol** [comment]
@don-vip Unfortunately, the server crashed, and I do not know when they fixed it. It's ok to close this now, I can open it gain when/if the server get online again
