### ISSUE TITLE
Add "Ekonomiska kartan" for Sweden

### ISSUE THREAD

**Issue by magol** [osmlab/editor-layer-index#348]
## URL of the imagery
https://mapproxy.openstreetmap.se/{service}/1.0.0/ek_EPSG3857/{zoom}/{x}/{y}.jpeg

## Two letter country code
sv

## Desired layer name
Ekonomiska kartan

## License
Free

## Is the license compatible with OSM?
yes

## Attribution (text, URL, required?)
[Map from the historical map archive of Lantmäteriet.](https://www.lantmateriet.se/sv/Om-Lantmateriet/Rattsinformation/upphovsratt-till-kartor-och-bilder/#faq:historiska-kartor)
Maybe some attribution to openstreetmap.se? What do you think @joakimfors?

## Icon
<img src="https://www.lantmateriet.se/Images/LM_logo_webb.jpg" title="Lantmäteriet"/>

## Boundary polygon
See https://github.com/magol/osm/blob/master/Ekonomisk%20karta
or
http://bl.ocks.org/d/f9c305c2a112569880c017f3a204c9a6

**Comment by tyrasd** [comment]
* What's the coverage area of this layer?
* What does the `{service}` parameter in the URL represent?
* The `{z}` parameter should instead read `{zoom}` to be fully compatible with the schema in this repository.

**Comment by magol** [comment]
@tyrasd 
The coverage is all over Sweden
`{service}` is `tms` or `tiles`.

**Comment by tyrasd** [comment]
Regarding coverage, please see https://github.com/osmlab/editor-layer-index/issues/352#issuecomment-312422173

**Comment by magol** [comment]
I did create the bounders with http://geojson.io. See the update of the issue, I hope it is correct.

**Comment by grischard** [comment]
@magol Thank you for your reply to #349. Same question here - is it relevant for mappers? [It doesn't look that great](https://mapproxy.openstreetmap.se/demo/?srs=EPSG%3A3857&format=image%2Fjpeg&wms_layer=ek).

**Comment by grischard** [comment]
[ek_ms](https://mapproxy.openstreetmap.se/demo/?srs=EPSG%3A3857&format=image%2Fjpeg&wms_layer=ek_ms#) however looks good. Probably useful for place names?

https://www.lantmateriet.se/en/Maps-and-geographic-information/Historical-Maps/upphovsratt-till-kartor-och-bilder/ seems to be a copyright waiver that applies to this layer. @simonpoole do you reckon this is enough for us?

**Comment by magol** [comment]
@grischard Thank you for looking at this.
I (and many others in Sweden) already use this map layer. When mapping objects in the nature like lakes and streams, this is a gold mine. Here you will find names and shape even on the smallest lakes, and even small dikes are included.

**Comment by simonpoole** [comment]
@grischard if the layer is actually for the historical maps mentioned on the web page, I don't see any issues.

**Comment by magol** [comment]
@simonpoole yes, the layer is a historical map that are coverd by the text on the Web page. So i aggre that it is ok to use it

**Comment by grischard** [comment]
Fixehd in 4f2d324
