### ISSUE TITLE
Add Sverigekartan for Sweden

### ISSUE THREAD

**Issue by magol** [osmlab/editor-layer-index#349]
## URL of the imagery
https://mapproxy.openstreetmap.se/{service}/1.0.0/sverigekartan94_EPSG3857/{zoom}/{x}/{y}.jpeg

## Two letter country code
sv

## Desired layer name
Sverigekartan 1994

## License
Free

## Is the license compatible with OSM?
yes

## Attribution (text, URL, required?)
[Map from the historical map archive of Lantmäteriet.](https://www.lantmateriet.se/sv/Om-Lantmateriet/Rattsinformation/upphovsratt-till-kartor-och-bilder/#faq:historiska-kartor)
Maybe some attribution to openstreetmap.se? What do you think @joakimfors?

## Icon
<img src="https://www.lantmateriet.se/Images/LM_logo_webb.jpg" title="Lantmäteriet"/>

## Boundary polygon
See https://github.com/magol/osm/blob/master/Sverigekartan
or 
http://bl.ocks.org/anonymous/raw/35c06de9473448c6f6f983b8ce32c638/

**Comment by tyrasd** [comment]
* What's the coverage area of this layer?
* What does the `{service}` parameter in the URL represent?
* The `{z}` parameter should instead read `{zoom}` to be fully compatible with the schema in this repository.

**Comment by magol** [comment]
@tyrasd 
The coverage is all over Sweden
`{service}` is `tms` or `tiles`.

**Comment by tyrasd** [comment]
What's the difference between `tms` and `tiles`?

Regarding coverage, please see https://github.com/osmlab/editor-layer-index/issues/352#issuecomment-312422173

**Comment by magol** [comment]
@tyrasd I don't know what the difference is.

@joakimfors, can you tell us what the difference is between `tms` and `tiles`.

**Comment by grischard** [comment]
@magol That polygon looks very rough; [it doesn't look like the maps actually cover Copenhagen or Oslo](http://mapproxy.openstreetmap.se/demo/?srs=EPSG%3A3857&format=image%2Fpng&wms_layer=sverigekartan94).

The scale of Sverigekartan 94 is very high. Does it actually make sense to include this as a layer in OSM editors?

**Comment by magol** [comment]
@grischard You are right. We may not have much use of this map because of the high scale.
