### ISSUE TITLE
Add Orthophotograph of Helsingborg

### ISSUE THREAD

**Issue by magol** [osmlab/editor-layer-index#350]
## URL of the imagery

1. https://mapproxy.openstreetmap.se/tiles/1.0.0/hborg2014_EPSG3857/{zoom}/{x}/{y}.jpeg
2. https://mapproxy.openstreetmap.se/tiles/1.0.0/hborg2016_EPSG3857/{zoom}/{x}/{y}.jpeg

## Two letter country code
sv

## Desired layer name

1. Helsingborg - 2014
2. Helsingborg - 2016

## License
CC0

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
Text: Helsingborgs stad
Url: [helsingborg.se](http://helsingborg.se)
Required: yes

## Icon
<img src="https://upload.wikimedia.org/wikipedia/commons/f/f2/Coat_of_arms_of_Helsingborg%2C_Sweden.svg" width="64" title="Coat of arms">

## Boundary polygon
See https://github.com/magol/osm/blob/master/Helsingborg
or 
http://bl.ocks.org/d/aa6cb900abc68ad26c2d9a7a3eb6e26a

**Comment by tyrasd** [comment]
* What's the coverage area of this layer?
* The `{z}` parameter should instead read `{zoom}` to be fully compatible with the schema in this repository.

**Comment by magol** [comment]
The coverage is over [Helsingborg municipality](http://www.openstreetmap.org/relation/935560)

**Comment by simonpoole** [comment]
@magol please generate a coverage polygon, it makes using a specific source automatically (if the best flag is set) possible and more consistent. A bounding box or none  will overlap with other areas and screw things up.

**Comment by magol** [comment]
@tyrasd  Unfortunately, I do not have the technical knowledge of how I do that. Please, point me in the right direction and I'll see what I can do. :-)

**Comment by tyrasd** [comment]
Regarding coverage, please see https://github.com/osmlab/editor-layer-index/issues/352#issuecomment-312422173

**Comment by magol** [comment]
I have now added the coverage

**Comment by grischard** [comment]
Can you also please provide a link to the license?

**Comment by grischard** [comment]
@magol just wondering if you had any idea where we could find the license for this. Thanks, and sorry for the ping!

**Comment by magol** [comment]
Fixed by #567
