### ISSUE TITLE
Add Orthophotograph of Kalmar

### ISSUE THREAD

**Issue by magol** [osmlab/editor-layer-index#351]
## URL of the imagery
https://mapproxy.openstreetmap.se/tiles/1.0.0/kalmar2012_EPSG3857/{zoom}/{x}/{y}.jpeg

## Two letter country code
sv

## Desired layer name
Kalmar - 2012

## License
Free? 
None is given in http://data-kalmar.opendata.arcgis.com/datasets/ca6c233810f74b44bd541ba6eb71eab6
In http://data-kalmar.opendata.arcgis.com/ thay say that you have to say that it come from Kalmar.
Do you know @joakimfors?

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
Text: Kalmar kommun
Url: [kalmar.se](http://kalmar.se)
Required: yes

## Icon
<img src="https://upload.wikimedia.org/wikipedia/commons/c/c8/Kalmar_vapen.svg" width="64" title="Coat of arms">

## Boundary polygon
See https://github.com/magol/osm/blob/master/Kalmar%202012
or
http://bl.ocks.org/anonymous/raw/8b3e133cbf6f641976b6d4047e75ecbc/

**Comment by tyrasd** [comment]
* What's the coverage area of this layer?
* The `{z}` parameter should instead read `{zoom}` to be fully compatible with the schema in this repository.

**Comment by magol** [comment]
@tyrasd The coverage is the cities of [Kalmar Municipality](http://www.openstreetmap.org/relation/935466). 

See http://data-kalmar.opendata.arcgis.com/datasets/ca6c233810f74b44bd541ba6eb71eab6/data for exact coverage.

**Comment by tyrasd** [comment]
Regarding coverage, please see https://github.com/osmlab/editor-layer-index/issues/352#issuecomment-312422173

**Comment by Klumbumbus** [comment]
>In http://data-kalmar.opendata.arcgis.com/ thay say that you have to say that it come from Kalmar.
Then this is not compatible with OSM without explizit permission.

**Comment by grischard** [comment]
See https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/ for example. Feel free to ping me to reopen this if you get explicit permission, but I'll close it for now.
