### ISSUE TITLE
Ensure that only url safe characters appear in ids

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#353]
re: https://github.com/osmlab/editor-layer-index/commit/40511edac5c3955525b18d5fc3ccbbce36afd018

We use this `id` as a url parameter in iD, so we should make sure only [url safe characters](https://stackoverflow.com/a/695467/7620) appear in the id field.

**Comment by tyrasd** [comment]
As far as I can see, it should already validated via the json schema here: https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json#L60

**Comment by bhousel** [comment]
This is fine
