### ISSUE TITLE
OS7 layer: inaccurate outline

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#354]
Effects at least iD and vespucci

See https://github.com/MarcusWolschon/osmeditor4android/issues/589

As I'm currently on vacation I haven't been able to investigate yet.

**Comment by Klumbumbus** [comment]
The source is not available for whole UK. See https://josm.openstreetmap.de/mapsview?entry=7th%20Series%20%28OS7%29
Maybe an area, where the source is not available was choosen? (The ELI shape is outdated.)

**Comment by SomeoneElseOSM** [comment]
My recollection is that the OSM-hosted OS 7th Series hasn't been available for some time (years).  The NLS-hosted OS 7th series is, though.

**Comment by MikeParfitt** [comment]
So that users understand the coverage, it would be simplest if the Map Background entry which currently says "7th Series (OS7)" was qualified with "only xx sheets out of xxx"

The hyperlink provided by Klumbumbus would be a useful addition.

**Comment by Klumbumbus** [comment]
I updated the shape. The source should now (i.e. after next iD update) only be suggest in the area where it is actually available in iD.
