### ISSUE TITLE
Add ESRI World Imagery

### ISSUE THREAD

**Issue by tyrasd** [osmlab/editor-layer-index#357]
It looks like we can now use ESRI's "World Imagery" Layer for deriving public vector data from it. :tada: For details, see https://github.com/Esri/arcgis-osm-editor/issues/104#issuecomment-323879799.

~~Related ticket on iD's issue tracker: https://github.com/openstreetmap/iD/issues/4164~~

**Comment by mboeringa** [comment]
@tyrasd , I don't see how the linked iD issue is really related: that issue talks about using Feature Services with vector data directly in iD, and even getting vector data from them for transfer to OSM, which is a whole different subject than tracing new vector data over the ESRI World Imagery layer?...

I think these issues can be kept separate...[](url)

**Comment by tyrasd** [comment]
Oops, sorry. You're right, these are separate issues.
