### ISSUE TITLE
Mapbox Logo (Mapbox satellite layer)

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#383]
I'm in the process of migrating to the geojosn format for Vespucci and am working through numerous oddities while I'm at it. One of them is that Mapbox uses as the only provider in the whole index a SVG logo, which is a "problem" on systems that do not support SVG, for example Android.

Would if be possible to replace the SVG icon with a PNG or other bitmap format image?

**Comment by bhousel** [comment]
Sure, @simonpoole - I will replace the logo with a bitmap format
