### ISSUE TITLE
imagico.de names are (too) long

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#386]
@imagico the names of your imagery layers are so long that now and then the actually interesting part gets truncated.

Would it be possible to shorten the name and move any relevant information to the description field?

Random example: 

> imagico.de OSM images for mapping: Bouvet Island

could easily be

> imagico.de: Bouvet Island

without any loss of information.

**Comment by imagico** [comment]
Fine by me - it might be a good idea to add something about this (i.e. a desirable maximum name length) to the documentation.

I can change that in my scripts to generate these files but if you want to have this fast you can also run a simple search and replace yourself.

**Comment by simonpoole** [comment]
@imagico there is no big hurry,  IMHO 40 characters would be a good guideline, but doesn't have to hard. With the current names for your layers the problem is further compounded because you end up with a lot of
"imagico.de OSM images for mapping: " layers :-).
