### ISSUE TITLE
Change Estonian Aerials URL

### ISSUE THREAD

**Issue by sookoll** [osmlab/editor-layer-index#392]
Was created with this ticket: https://github.com/osmlab/editor-layer-index/issues/37

kaart.maakaart.ee service is down and probably never will come up again.
Estonian Land board just released TMS service with 3857.
Correct URL is:

http://tiles.maaamet.ee/tm/tms/1.0.0/foto@GMC/{z}/{x}/{-y}.png

License and rest should be unchanged.

**Comment by bhousel** [comment]
@sookoll , does this affect all the sources under `sources/europe/ee` that use `kaart.maaamet.ee`?  There are several there.. Only one of them is a `tms` source, the rest are `wms`.

**Comment by simonpoole** [comment]
Hmmm maybe operator error on my behalf, will recheck.

**Comment by sookoll** [comment]
No, kaart.maakaart.ee and kaart.maaamet.ee are different things. maakaart.ee was local Estonian OSM community server and we serve ortho tiles, because national land survey didn't offer tiles in web mercator. We didn't have funds to host our services anymore and now land survey start offer ortho map also in web mercator. So no, this is not affect any of kaart.maaamet.ee services.

**Comment by bhousel** [comment]
Ah gotcha, thanks for the clarification @sookoll
