### ISSUE TITLE
Missing "interesting" layers from WMS with EPSG:3857

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#395]
I did a quick scan of the JOSM config to see if there is a larger number of interesting (not very out of data or very special interest) WMS servers that we could support that are missing from ELI and the issue seems to be very limited. Argentina does have a large number of WMTS end points that support EPSG:3857 that likely could be supported without too much work, but that is about it. Note: I skipped going through all of the US on the premises that it all is likely included.

No guarantees that this is correct, it was jsut really a quick superficial scan.

- [ ] Metropole Ruhr: Luftbilder (10 cm)
- [ ] S\u00f3sk\u00fat, Pusztaz\u00e1mor, T\u00e1rnok, Di\u00f3sd orthophoto 2017 WMS
- [ ] Pozna\u0144: Orthophotomap 2016 (aerial image)
- [ ] Wroc\u0142aw: Orthophotomap 2015 (aerial image)
- [ ] Ortofotos Litoral DGT 2014-2015 (WMS)
- [ ] Orthophoto IGN-NGI
- [ ] SPW(allonie) most recent aerial imagery
- [x] NLSC Open Data WMTS _not imagery_
- [ ] Maps4BW (LGL-BW, www.lgl-bw.de) _not imagery?_
- [ ] Saxony WebAtlasSN _not imagery_
- [ ] Saxony topographic map _not imagery_
- [ ] polska.e-mapa.net: Buildings _no imagery_
- [ ] Pozna\u0144: Buildings _not imagery_
- [ ] IGN topographical map (WMS) _not imagery_
- [x] LPI NSW Administrative Boundaries Suburb _not imagery_
- [x] LPI_NSW_Administrative_Boundaries_LGA _not imagery_
- [x] LPI NSW Administrative Boundaries County _not imagery_
- [x] LPI NSW Administrative Boundaries Parish _not imagery_
- [x] LPI NSW Administrative Boundaries State Forest _not imagery_
- [x] LPI NSW Administrative Boundaries NPWS Reserve _not imagery_

**Comment by grischard** [comment]
I've added the ones that advertise 3857 or something compatible in #405. 

See https://github.com/osmlab/editor-layer-index/commit/c2de955bdcf06f308dd37d4bd5938e5dde744a75#commitcomment-27643943 for the ones that might support it but don't advertise it in their getCapacities.

**Comment by simonpoole** [comment]
I believe this is moot now.

**Comment by Marc-marc-marc** [comment]
@simonpoole may I add 46 missing Argentina layers found at josm ? and other ? or closing the ticket means that the related layers should not be added ?

**Comment by simonpoole** [comment]
I believe those are all WMTS servers which I didn't consider at the time.
