### ISSUE TITLE
Imagery ID key for some entries

### ISSUE THREAD

**Issue by Zverik** [osmlab/editor-layer-index#4]
For a planned imagery offset database each imagery source should have a unique identifier. While it usually can be [deduced from TMS/WMS URL](http://wiki.openstreetmap.org/wiki/Imagery_Offset_Database/API#Imagery_Identifier), for some sources (e.g. Bing) the [dictionary entry](http://wiki.openstreetmap.org/wiki/Imagery_Offset_Database/Imagery) is used instead. In such cases it would be nice to have a key for that in lists.

**Comment by bhousel** [comment]
Closing as stale.  The [id property](https://github.com/osmlab/editor-layer-index/blob/61fac7c81eec1cec3efad17b6bf5b28322d00b27/schema.json#L23) has existed for a while.
