### ISSUE TITLE
missing description and license_url in convert_individual.py

### ISSUE THREAD

**Issue by Marc-marc-marc** [osmlab/editor-layer-index#411]
for ex FR/BANO.geojson

input have : 
```
<description lang="en">French address registry or Base Adresses Nationale Ouverte</description>
<terms-of-use-url>http://www.opendatacommons.org/licenses/odbl/1.0/</terms-of-use-url>
```

FR/BANO.geojson produce by convert_individual.py should have : 
```
"description": "French address registry or Base Adresses Nationale Ouverte"
"license_url": "http://www.opendatacommons.org/licenses/odbl/1.0/"
```
but those fileds are missing after running convert_individual.py

**Comment by tyrasd** [comment]
Thanks for spotting these, but I believe that the `BANO` layer in [JOSM's imagery repository](https://josm.openstreetmap.de/wiki/Maps/France#BANO) is using the wrong field to supply the given license url. According to JOSM's imagery [documentation](https://josm.openstreetmap.de/wiki/Maps#Documentation), the correct field should be `permission-ref`, I believe:

> permission-ref | Provide a source that this background can be used for OSM. A page on the OSM-wiki with additional explanation and further references is preferred, but other sources (for example the license text) can also be linked. The document does not have to be in English. Please always use this property when adding new entries so it is easier for others to review.
> […]
> terms-of-use-url | A link that is opened, when the user clicks on the terms-of-use text
> terms-of-use-text | Customized text for the terms of use link (default is "Background Terms of Use")

where ELI defines [`license_url`](https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json#L55-L56) as:

> A URL for the license or permissions for the imagery

**Comment by Marc-marc-marc** [comment]
thanks for the update but it fail 
```
Traceback (most recent call last):
  File "scripts/convert_individual.py", line 83, in <module>
    properties['license_url'] = imagery.getElementsByTagName('permission-ref')[0].childNodes[0].nodeValue
IndexError: list index out of range
```
for permission-ref <> terms-of-use-url maybe it should be a fallback : primary get permission-ref but if not exist, display a warning and get terms-of-use-url if exist.
it would allow to correct the info on the josm side if it is justified and avoid having to do a second manual correction to add the missing info in eli.

**Comment by tyrasd** [comment]
oops, I forgot to put in the check if the fields are actually present in the input. :see_no_evil: that should be fixed now

regarding treating terms-of-use-url as fallback – I don't know, to me it sounds better to just fix the data in JOSM's layer-index.

**Comment by Marc-marc-marc** [comment]
I agree that <terms-of-use-url>http://www.opendatacommons.org/licenses/odbl/1.0/</terms-of-use-url>
should be changed on josm side.
but it's not a josm permission-ref (it's not the ref that show that it can be used for osm)
and it's still a eli valid license_url (data and tiles are put in this licence). so it seems a key is missing to match with eli license_url

maybe it should still be usefull to display a warning if not licence_url is filled after conversion.
if not, the commit 'll be done without it because no check complain about it.
