### ISSUE TITLE
non-ascii characters are unnecessarily escaped in convert_individual.py output

### ISSUE THREAD

**Issue by Marc-marc-marc** [osmlab/editor-layer-index#412]
for ex FR/BANO.geojson

FR/BANO.geojson produce by convert_individual.py have :
`"text": "Tiles \u00a9 cquest@Openstreetmap France, data \u00a9 OpenStreetMap contributors, ODBL"`
check.py does not report it as an error but the current (also valid for check.py) commited encoding is : 
`"text": "Tiles © cquest@Openstreetmap France, data © OpenStreetMap contributors, ODBL"`
it would be useful to have the same encoding.

I found only 2 "\u00a9" in all commited layers, so it'll be easy to change "\u00a9" into "©" if it is the selected solution.

**Comment by tyrasd** [comment]
In JSON strings, `\u00a9` and `©` are representations of the same character (similarly to how `&auml;` and `ä` are equivalent in XML documents):

```javascript
"\u00a9" === "©" // -> true
```

That's also the reason why check.py doesn't complain about it. In my opinion, it's totally fine to use both variants in the layer index. The creator of the respective source files are free to choose whatever variant they like best.

**Comment by grischard** [comment]
It makes it more difficult to use diff tools, and makes files less readable. I'll look into urldecoding the output of convert_individual.py.

**Comment by tyrasd** [comment]
> urldecoding

Small nit-pick here: This kind of encoding has actually nothing to do with [url-encoding](https://tools.ietf.org/html/rfc3986#section-2.1), but are part of the [json format](https://tools.ietf.org/html/rfc8259#section-7). This SO answer might help: https://stackoverflow.com/a/10865213/1627467

**Comment by grischard** [comment]
See #415 too
