### ISSUE TITLE
missing start_date+end_date in convert_individual.py

### ISSUE THREAD

**Issue by Marc-marc-marc** [osmlab/editor-layer-index#415]
for ex FR/Tours-Orthophotos2013.geojson

input have :
`<date>2013</date>`
output should have :
```
"end_date": "2013"
"start_date": "2013"
```

I have grep all date and found the following use-cases : 
- one date -> should be put in both `start_date and end_date
- date1;date2 -> first for start_date, second for end_date
- 1 date;- (TexasOrthophoto.geojson) -> only start_date (not sure if it is valid for josm schema).

for date format I have found : YYYY YYYY-MM and YYYY-MM-DD

**Comment by grischard** [comment]
See #412 too
