### ISSUE TITLE
Use of FORMAT image/bmp for WMS servers

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#435]
Just noticed

https://github.com/osmlab/editor-layer-index/search?utf8=%E2%9C%93&q=image%2Fbmp&type=

this leads to the map tiles being very large and would seem to be rather unnecessary as the server supports PNG output in any case.

Do we want to warn against this? Or do something else?

**Comment by bhousel** [comment]
I agree, it should probably be a warning

**Comment by simonpoole** [comment]
Note on the side, this imagery is missing the best flag (on the 2016 version and min/max zooms). It is not quite clear who added the entry, best guess @simon04 @Klumbumbus :-)

**Comment by grischard** [comment]
If there's a warning, it should be on the editor side, no?

In this particular case, if anyone wants to play with it, https://secure.erlangen.de/arcgiser/rest/services/Luftbild2016/MapServer reports:

Supported Image Format Types: PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP

**Comment by tyrasd** [comment]
interesting: [josm's index](https://josm.openstreetmap.de/wiki/Maps/Germany#Erlangenaerialimagery20165.0cm) includes this comment:

> bmp is the only format which doesn't wrongly convert pure white pixels into black pixels.

I just tested it with `image/jpeg` and it looks fine to me (see example below) – this probably has been fixed upstream.

![](https://secure.erlangen.de/arcgiser/services/Luftbild2016/MapServer/WmsServer?&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&FORMAT=image%2Fbmp&TRANSPARENT=true&VERSION=1.1.1&HEIGHT=256&WIDTH=256&SRS=EPSG%3A3857&BBOX=1224979.8152982346,6374695.284927132,1225132.6893548048,6374848.158983702)

**Comment by Klumbumbus** [comment]
>bmp is the only format which doesn't wrongly convert pure white pixels into black pixels.

I once added this comment.
png still converts white to black. see screenshot. however jpeg works fine for me now too.

![grafik](https://user-images.githubusercontent.com/7115609/37301808-f2a59980-2629-11e8-82a3-1e909dd6a0dc.png)

(position: 49.59351, 11.01147)

**Comment by tyrasd** [comment]
oh, now I see the "black" pixels are actually transparent ones in the png (I guess in JOSM the black background then "shines" through).

> Supported Image Format Types: PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP

no [WebP](https://wikipedia.org/wiki/WebP) :disappointed: :wink:

**Comment by Klumbumbus** [comment]
>oh, now I see, the "black" pixels are actually transparent ones in the png (I guess in JOSM the black background then "shines" through).

Ah, yes, you're right.

**Comment by simonpoole** [comment]
@grischard a warning along the lines of "you just downloaded a number of insanely large tiles!"? :-) Seriously: I was just thinking of a note in the contribution docs, particularly as it seems there is actually a semi-sane reason for the choice in this case.

**Comment by grischard** [comment]
Something like this?

"Make sure you submit the most appropriate format for the images: usually, jpeg for photography and png for maps. See #435 for a case where bmp was better."

**Comment by poempelfox** [comment]
JPEG is not necessarily lossless though, so depending on what the server does there, it might add visible compression artifacts to the imagery. Especially with good quality imagery I'd consider that likely. Therefore PNG probably should be preferred when available?

In the specific case of the Erlangen imagery, instead of the original WMS maybe the proxied TMS-version at https://osm.rrze.fau.de/luftbilderl2016/{Z}/{X}/{Y}.png provides imagery that has the transparency/white-is-black-issue fixed?

**Comment by tyrasd** [comment]
> JPEG is not necessarily lossless

Well, it's always about a trade-off between image quality and file size / network bandwidth. I would argue that for OSM related mapping, one doesn't need pixel-perfect image quality. While at the same time one benefits substantially from faster loading tiles.

In the example [above](https://github.com/osmlab/editor-layer-index/issues/435#issuecomment-372367521) these are the file sizes:

| format  | tile size |
| ------------- | ------------- |
| image/bmp  | 257kB  |
| image/png  | 114kB  |
| image/jpeg  | 28kB  |

**Comment by simonpoole** [comment]
@tyrasd on mobile having large tiles can potentially not just be slow, but expensive too.
