### ISSUE TITLE
Maryland: any other relevant layers?

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#441]
We currently have three manually picked layers from https://geodata.md.gov/imap/rest/services. Are there any others we'd want?

**Comment by tyrasd** [comment]
//cc @talllguy

**Comment by talllguy** [comment]
Hi, I'm late to the party here. The three Maryland layers we had used and should continue to use are:

1. [Six-inch imagery](https://github.com/osmlab/editor-layer-index/issues/148)
2. [Three-inch imagery](https://github.com/osmlab/editor-layer-index/issues/171)
3. [Basemap](https://github.com/osmlab/editor-layer-index/issues/155)

Any additional? Not that I know of. The state is moving to https soon though. What impact will that have?

**Comment by talllguy** [comment]
Actually, now that I think about it (and especially after reading #424, the Maryland wetland inventory would be great for tracing coastlines and coastal wetlands.

- http://geodata.md.gov/imap/rest/services/Hydrology/MD_Wetlands/MapServer

![image](https://user-images.githubusercontent.com/1827881/37381859-ea1ea058-2715-11e8-9754-3c2e403e9b3d.png)

**Comment by grischard** [comment]
The wetlands aren't part of the basemap?

You don't want the forests?

**Comment by grischard** [comment]
If anyone ever wants to reactivate this, please ping me.
