### ISSUE TITLE
mapbox satellite only up to zoom 20?

### ISSUE THREAD

**Issue by tyrasd** [osmlab/editor-layer-index#455]
[https://c.tiles.mapbox.com/styles/v1/openstreetmap/cj8gojt0i1eau2rnn7q4mdgu7/tiles/256/21/1504881/646091](https://c.tiles.mapbox.com/styles/v1/openstreetmap/cj8gojt0i1eau2rnn7q4mdgu7/tiles/256/21/1504881/646091?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJhNVlHd29ZIn0.ti6wATGDWOmCnCYen-Ip7Q) returns the following error message:

    {"message":"Zoom level must be between 0-20."}

where we have set the max zoom it to [22](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/world/MapBoxSatellite.geojson?short_path=1f6e37a#L15).

@bhousel can you check that?

**Comment by Klumbumbus** [comment]
Maybe the max-zoom depends on the region?

**Comment by tyrasd** [comment]
Aah, yes, that could be the case. I checked a few places, but didn't get any tiles > zoom 20 anywhere…

**Comment by bhousel** [comment]
Yes, at least in [some places](https://blog.mapbox.com/ultra-high-res-uav-imagery-on-the-map-a7ea26d1b866) Mapbox Satellite will return imagery that goes up to z22.. It does depend on the region.

**Comment by tyrasd** [comment]
Ok, thanks. But strangely, even in the region linked in the blog post, I don't get any results for zoom levels greater than 20:

[https://d.tiles.mapbox.com/styles/v1/openstreetmap/cj8gojt0i1eau2rnn7q4mdgu7/tiles/256/21/1523985/1003130](https://d.tiles.mapbox.com/styles/v1/openstreetmap/cj8gojt0i1eau2rnn7q4mdgu7/tiles/256/21/1523985/1003130?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJhNVlHd29ZIn0.ti6wATGDWOmCnCYen-Ip7Q)

returns the same error message (HTTP 422 "Unknown", `{"message":"Zoom level must be between 0-20."}`).

**Comment by bhousel** [comment]
This is fixed now - I switched the Mapbox url from the styles api to the maps api a few months ago in 58ff6d2
