### ISSUE TITLE
What happened to the NLS layers?

### ISSUE THREAD

**Issue by lakedistrictOSM** [osmlab/editor-layer-index#456]
Hopefully this is the right place to ask.

What happened to the NLS layers in iD for the United Kingdom? In particular I'd like to see the return of "NLS - OS 1:25k 1st Series 1937-61" which I've been using to trace the Thirlmere Aqueduct. 

"OS 1:25k historic (OSM)" which is still available to select as a layer is useless as it is just a black screen.

**Comment by bhousel** [comment]
We filter out the historic layers from iD..
see https://github.com/openstreetmap/iD/issues/3453 for discussion

**Comment by grischard** [comment]
In this particular case, I think you want `https://ooc.openstreetmap.org/os1/{zoom}/{x}/{y}.jpg` as a custom layer. Happy mapping!

**Comment by lakedistrictOSM** [comment]
> In this particular case, I think you want `https://ooc.openstreetmap.org/os1/{zoom}/{x}/{y}.jpg` as a custom layer. Happy mapping!

I can't get this to work (just a black background), but thanks anyway.

For anyone else looking for the NLS layers, they're available in JOSM.

**Comment by grischard** [comment]
Ah! I'd gotten the wrong first series. Try `https://geo.nls.uk/mapdata2/os/25000/{zoom}/{x}/{-y}.png` then.

**Comment by lakedistrictOSM** [comment]
That works! Thanks :smile:
