### ISSUE TITLE
convert_individual.py : overlay (& eli-best & last-check) missing

### ISSUE THREAD

**Issue by Marc-marc-marc** [osmlab/editor-layer-index#464]
ex FR/BDCarthage
josm have `<entry overlay="true">`
the output by convert_individual.py must have `"overlay": true` but it's missing

**Comment by DavidMoraisFerreira** [comment]
What about other attributes such as "eli-best" and "last-check"?

**Comment by Marc-marc-marc** [comment]
yes eli-best is also missing and should be added.
but last-check doesn't exist in eli schema. so currently the convert can not use it
