### ISSUE TITLE
broken link in prefill of issues

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/editor-layer-index#475]
Excerpts from template follow:

(required)<br/>
See [FAQ.md](FAQ.md#what-imagery-licenses-are-compatible-with-this-index) for information
about which licenses are compatible with this index.

(,,,)

See [FAQ.md](FAQ.md#how-can-i-draw-a-bounding-polygon) for information about how to draw a bounding polygon.

These are unclickable from editing mode, links are impossible to copy paste into browser, using preview tab and clicking link leads to https://github.com/osmlab/editor-layer-index/issues/FAQ.md#what-imagery-licenses-are-compatible-with-this-index that is 404 page.

Maybe it would be preferable to use URLS like https://github.com/osmlab/editor-layer-index/blob/gh-pages/FAQ.md#what-imagery-licenses-are-compatible-with-this-index ?

These are fragile to changes of repository name and repository hosting locations - but it would make them usable. Other solution is to just drop these links and say "see FAQ".

**Comment by grischard** [comment]
Thank you!
