### ISSUE TITLE
Add Berlin aerial photography provided by the city of Berlin

### ISSUE THREAD

**Issue by tordans** [osmlab/editor-layer-index#480]
The city of Berlin has images that are a lot better than what Bing and such provides. It would be aweseome to have them as a layer in iD Editor and such. Ideally as the default layer for that region.

There are two data layers, I think both are interesting. Layer one should have priority and be the default image layer when opening iD Editor in Berlin. Layout two could be an optional layer (like "Esri" vs "Esri (Clarity)").

## URL of the imagery

This is all I know ATM

Layer 1:
- City Website: WMS: https://daten.berlin.de/datensaetze/digitale-farbige-orthophotos-2017-dop20rgb-wms-1 / Atom: https://daten.berlin.de/datensaetze/digitale-farbige-orthophotos-2017-dop20rgb-atom
- City Map Tool: http://fbinter.stadt-berlin.de/fb/index.jsp?loginkey=zoomStart&mapId=k_luftbild2017_rgb@senstadt
- There is a project by [OKFN DE](https://github.com/okfde) that provides easier access to this data
  - https://codefor.de/projekte/2018-04-09-fis-broker.html
  - https://github.com/jochenklar/berlin-aerial
  - https://tiles.codefor.de/ (choose "Geoportal Berlin / Digitale farbige Orthophotos 2017 (DOP20RGB)" from the right)
     ``` https://tiles.codefor.de/berlin-2017/{z}/{x}/{y}.png ```

- This tool shows a comparison of images for Berlin: https://mc.bbbike.org/mc/?lon=13.377792&lat=52.516233&zoom=17&num=4&mt0=mapnik&mt1=berlin-historical-2016&mt2=esri-satellite&mt3=berlin-historical-2016i&marker=

Layer 2 Infrared:
- City Website: https://daten.berlin.de/datensaetze/digitale-color-infrarot-orthophotos-2016-dop20cir-wms
- City Map Tool: http://fbinter.stadt-berlin.de/fb/?loginkey=showMap&mapId=k_luftbild2016_cir@senstadt
- https://tiles.codefor.de/ (same as above)
   ``` https://tiles.codefor.de/berlin-2016i/{z}/{x}/{y}.png ```

## Two letter country code
DE

## Desired layer name and attribution

Layer 1:

```json
    "properties": {
        "attribution": {
            "required": true,
            "text": "Geoportal Berlin / Digitale farbige Orthophotos 2017 (DOP20RGB)",
            "url": "https://daten.berlin.de/datensaetze/digitale-farbige-orthophotos-2017-dop20rgb-wms-1"
        },
        "license_url": "https://wiki.openstreetmap.org/wiki/Geoportal_Berlin",
        "name": "Luftbilder Berlin 2017 (DOP20RGB)",
    },
```

Layer 2 Infrared:

```json
    "properties": {
        "attribution": {
            "required": true,
            "text": "Geoportal Berlin / Digitale Color-Infrarot-Orthophotos 2016 (DOP20CIR) ",
            "url": "https://daten.berlin.de/datensaetze/digitale-color-infrarot-orthophotos-2016-dop20cir-wms"
        },
        "license_url": "https://wiki.openstreetmap.org/wiki/Geoportal_Berlin",
        "name": "Luftbilder Berlin 2016 Infrarot (DOP20CIR)",
    },
```

## License

- See discussion and links below
- Website https://daten.berlin.de/datensaetze/digitale-farbige-orthophotos-2016-dop20rgb-wms-1
- Licence Link from there (PDF) http://www.stadtentwicklung.berlin.de/geoinformation/download/nutzIII.pdf

## Is the license compatible with OSM?

- ~~I don't know~~ Yes, see discussion and links below
- I [asked](https://openknowledgegermany.slack.com/archives/C03MZFUKG/p1525249793000188) the local OSM Community and will update with feedback.
- I [asked](t.me/osmberlin/93) the local OKFN (Open Data) Community and will update with feedback.
- I can say, that JOSM seems to to add the Berlin Images in their macOS Installation package as a default layout(?)

## Icon
(optional)
- TODO

## Bounding polygon

- Lets use the same as JOSM https://josm.openstreetmap.de/mapsview?entry=Berlin%20aerial%20photograph%202017

Sidenote: The full map on the official website: http://fbinter.stadt-berlin.de/fb/index.jsp?loginkey=zoomStart&mapId=k_luftbild2016_rgb@senstadt&bbox=363892,5802743,419400,5837906

**Comment by tyrasd** [comment]
regarding the license: The page on the osm wiki (also linked from JOSM's [background layers page](https://josm.openstreetmap.de/wiki/Maps/Germany#Berlinaerialphotograph2017)) https://wiki.openstreetmap.org/wiki/Geoportal_Berlin claims that the service is OSM-compatible:

> Geodaten unter OSM-kompatiblen [Nutzungsbedingungen](https://wiki.openstreetmap.org/wiki/Contributors#Berlin)

> Die Berliner Senatsverwaltung für Stadtentwicklung und Umwelt (SenStadtUm) stellt seit dem 1. Oktober 2013 Geodaten unter an CC-BY angelehnten Nutzungsbedingungen bereit. Die in § 2 geforderte erkennbare und in optischem Zusammenhang Einbindung der Quellenverweise wird lt. SenStadtUm nur gefordert, wenn die Geodaten einen überwiegenden Anteil im Folgewerk haben. Wenn die veränderten Geodaten nur einen untergeordneten Anteil an dem Folgeprodukt haben, dann kann der Quellenvermerk für abgeleitete Werke auch an einer anderen Stelle (also hier) angebracht werden.

So, I believe it should be ok to be include it in this repository as is. But it would be awesome if you could confirm this with the local community!

**Comment by tyrasd** [comment]
Regarding the boundary polygon: Maybe we can use the one from the entry in JOSM's list (looks like [this](https://josm.openstreetmap.de/mapsview?entry=Berlin%20aerial%20photograph%202017)), or you can try to create a better one (see our [FAQ's](https://github.com/osmlab/editor-layer-index/blob/gh-pages/FAQ.md#how-can-i-draw-a-bounding-polygon)).

**Comment by tordans** [comment]
@tyrasd what next steps would you require to push this forward? The wiki pages seems clear to me. Is it required to get an explizit email from the city? Are there drafts / previous emails that I could use?
Thanks

**Comment by tordans** [comment]
The [general wiki page](https://wiki.openstreetmap.org/wiki/Contributors#Berlin) and also the [detailed wiki page](https://wiki.openstreetmap.org/wiki/Geoportal_Berlin#Nutzung_und_Quellenangabe) go on saying, that [the `source` tag](https://wiki.openstreetmap.org/wiki/Key:source) should be used for attribution like `Geoportal Berlin / [Title Of Dataset]`-

So an example [for DOP20RGB](http://fbinter.stadt-berlin.de/fb/berlin/service.jsp?id=k_luftbild2017_rgb@senstadt&type=WMS) would(?) be

> Geoportal Berlin / Digitale farbige Orthophotos 2017 (DOP20RGB)

So if we adjust this to use [the `imagery_used` tag](https://wiki.openstreetmap.org/wiki/Key:imagery%20used) instead, the attribution should be fine.

The iD Editor ([Example Changeset](https://www.openstreetmap.org/changeset/58800602)) and also the (new) GoMap-App ([Example Changeset](https://www.openstreetmap.org/changeset/58889072)) already set the imagery_used tag automatically based on the name that is provided in this layer index.

IMO all requirements are matched to add the data.

**Comment by grischard** [comment]
https://forum.openstreetmap.org/viewtopic.php?pid=367583#p367583 might be relevant.

**Comment by tordans** [comment]
@grischard thanks – and yes, that is also the basis for the wiki-page which in turn was the basis for my suggestion at https://github.com/osmlab/editor-layer-index/issues/480#issuecomment-388541085and and my update of the issue description.

**Comment by tordans** [comment]
@tyrasd, @grischard what next steps would you require to push this forward? The wiki pages seems clear to me and allow adding the layer. I updated the issue description to reflect what I currently know.

What else is required? In what form?

Thanks

**Comment by grischard** [comment]
I'll integrate the ones JOSM has. It'd be cool to have [all the layes from codefor.de](https://tiles.codefor.de/config.json) - a PR would be best.
