### ISSUE TITLE
Add missing layers from the JOSM index

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#481]
[JOSM's ImageryCompare lists 269 URLs that are in JOSM but not in ELI](https://josm.openstreetmap.de/wiki/ImageryCompare). This is a ticket to find out what stands in the way of copying them, fixing whatever is in the way, and actually doing it :)

**Comment by grischard** [comment]
Continued in commit 380df00dfb00848050037021c9d7c354d473a97e.

More work is needed to integrate WMTS sources.

Sometimes we have both a tms and a wms available, and ELI has the former while JOSM has the latter. We need to decide which one we prefer.

**Comment by joostschouppe** [comment]
It looks like you've added this file during this process: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/be/OrthophotoIGN-NGI.geojson
As far as I know, NGI/IGN data is extremely un-open, and nothing on their copyright page ([nl](http://www.ngi.be/NL/NL6.shtm) - [fr](http://www.ngi.be/FR/FR6.shtm)) seems to indicate otherwise. I couldn't find anything on the wiki nor on talk-be about any permission for NGI imagery use. I'd never noticed it in JOSM, but since you marked it as "best" in ELI (which is wrong IMHO), one can't help but miss it in ID. This has me and @xivk slightly worried.

**Comment by simonpoole** [comment]
Can we revert adding OrthophotoIGN-NGI.geojson till the legal side of things is clear? I have a release coming up and I'll need to remove it manually given the current situation.

**Comment by jbelien** [comment]
Really sorry about that ...
I definitely shouldn't have added those imagery to JOSM imagery. Don't remember why I added it, but license does definitely not authorize the use of imagery for OSM. I guess I wasn't paying much attention to the license 15 months ago (shame on me).
It can be removed from ELI ; I'll remove it from JOSM.

**Comment by Marc-marc-marc** [comment]
OrthophotoIGN-NGI.* deleted in commit f20589a74fd20e78c4222304f9148ce7c79c1a18.

**Comment by jbelien** [comment]
It would maybe be best to skip every layer that misses `permission-ref` tag from JOSM list to avoid what append with IGN/NGI imagery.

---

Another thing, the "OpenStreetMap (Belgian Style - German)" layer doesn't exist anymore, I deleted it from JOSM list.
You can delete the [`europe/be/OpenStreetMap(BelgianStyle-German).geojson`](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/be/OpenStreetMap(BelgianStyle-German).geojson).

---

Could I also change the name of the files (in Belgium) to make them more coherent ? It's a bit messy between former files from ELI and the new ones from JOSM.

**Comment by Marc-marc-marc** [comment]
> the "OpenStreetMap (Belgian Style - German)" layer doesn't exist anymore, I deleted it from JOSM list.
> You can delete the europe/be/OpenStreetMap(BelgianStyle-German).geojson.

done.

> Could I also change the name of the files (in Belgium) to make them more coherent ?

Of course,feel free to list the change or make a PR.
I have a small preference for a name in the form "place - type - maybe the supplier" (for ex Brussels - Orthophoto lasted - Urbis) but as long as it is coherent, It's a good thing to do.

**Comment by joostschouppe** [comment]
I made [a table with proposed file name changes](https://docs.google.com/spreadsheets/d/1ev9mhbn-ZDykWERP66GKTTcEEoCAQDgC2OvqmODdwmY/edit?usp=sharing). It might make sense to also harmonize the names with which it appears within the editors a bit.

I agree with @jbelien about being careful with porting from JOSM like @grischard did. Let's remove those that do not have license info (as a minimum, because it's not because there is a license mentioned that it is compatible with OSM). Apparently in the JOSM repo the licensing has not been as strictly checked as I think happened here until now.

**Comment by jbelien** [comment]
> I made a table with proposed file name changes. It might make sense to also harmonize the names with which it appears within the editors a bit.

Seems good to me ; I would use `BE` (instead of `BEL`) for the layers that covers all of Belgium though :P
I'll try to submit a PR with these changes ASAP :)

I'll check UrbIS 2013 too ; I don't think it's really useful though ...

**Comment by grischard** [comment]
[There are 321 sources without a proper license attribute](https://github.com/osmlab/editor-layer-index/issues/439). I can imagine that some of those layers, whether the license property is documented or not, is incompatible.

On the other hand, the European PSI directive [forces governments to to open the data that they publish, and forbids unnecessarily restrictions in licences](https://ec.europa.eu/digital-single-market/en/european-legislation-reuse-public-sector-information). It seems to me that the IGN/NGI terms of use are outdated and no longer permitted under the new law, but I'm not familiar with how Belgium has transcribed it.

Since the file names are already in the europe/be folder, I don't think it's necessary to name them BEL. You can however create wal/ bru/ and vla/ subfolders for regional sources.

**Comment by bhousel** [comment]
> I agree with @jbelien about being careful with porting from JOSM like @grischard did. Let's remove those that do not have license info (as a minimum, because it's not because there is a license mentioned that it is compatible with OSM). Apparently in the JOSM repo the licensing has not been as strictly checked as I think happened here until now.

I have always been very much against pulling in things that appear on the JOSM wiki without proper review.  Anybody can edit a wiki.  At least here on the GitHub side we have people reviewing the requests.  Can we stop syncing the lists?

**Comment by grischard** [comment]
That layer is [on the belgian open data portal](https://data.gov.be/fr/node/28573) and [the conditions "[grant] the user the right to use the data for his internal use"](https://www.geo.be/#!/catalog/details/434c9672-4fb8-4a99-93bc-cc8b3b988700), whatever that means. 

It's not perfect over here either, @bhousel - only about a third of the layers that we have that are without a license came over from JOSM. We should keep working on #439 and not overreact. Belgian friends, can you please help us find the license for the BE layers there?

**Comment by jbelien** [comment]
> Belgian friends, can you please help us find the license for the BE layers there?

I'll have a look :)
**EDIT:** https://github.com/osmlab/editor-layer-index/issues/439#issuecomment-400671656

> That layer is on the belgian open data portal and the conditions "[grant] the user the right to use the data for his internal use", whatever that means.

IGN orthphotos are part of [cartoweb.be](http://www.ngi.be/topomapviewer/public) services ; here are the terms of use : http://www.ngi.be/FR/FR1-19-1-1.shtm (in French).
I believe it's unfortunately clear we can not use it ...

**Comment by grischard** [comment]
It's mostly the WMTS sources from JOSM that are still missing. A script to convert these would be very welcome.

**Comment by alexanderzatko** [comment]
What stands in the way of using the sources here in JOSM as well? Now we have this list and the JOSM list of sources https://josm.openstreetmap.de/wiki/Maps - so it seems.

**Comment by grischard** [comment]
I'd done a sync in 2018, and most of the ones JOSM had that ELI was missing were `wms_endpoint` or `wmts` entries. I now see that https://josm.openstreetmap.de/wiki/ImageryCompare has several that we could pull over. Thank you!
