### ISSUE TITLE
Default layer for Norway

### ISSUE THREAD

**Issue by FredrikLindseth** [osmlab/editor-layer-index#484]
Is it possible to set the default layer in Norway as Digital Globe Standard instead of Bing? DG has superior imagery and better offset compared to Bing.

Someone mentioned this was possible, but I don't see how it can be done in this repo. 

A polygon for Norway(no) exists already with the  editor-layer-index/sources/europe/no/Kartverket-N50-topo.geojson-file.

**Comment by tyrasd** [comment]
Unfortunately, not really. See #130 for some discussion around this. But we still can only set the full extent of a layer as "best" for it's region.

> Someone mentioned this was possible

Currently, the only way to "hack" this would be to duplicate the DG layer with a Norway polygon with an active best flag. I'm not sure if that be an acceptable solution? //cc @bhousel @simonpoole

**Comment by simonpoole** [comment]
I've actually suggested doing this in some other situations. If there is no special processing needed for token/api keys (as there is with bing) then it should work, even if it is rather ugly,

**Comment by imagico** [comment]
What you could do is introducing an optional 'best_area' footprint polygon indicating the area where an image source is best which will typically be a subset of the coverage footprint.  Alternatively you could also work with the inverse - i.e. add a 'worst_area' footprint polygon to Bing indicating where it is bad.

It would still be mono-dimensional without the possibility to differentiate between different aspects of quality (age, ground resolution or in this case positional accuracy).

@FredrikLindseth - has anyone in Norway tried to get permission to use the images from https://www.norgeibilder.no/ (also featured on http://www.norgeskart.no/) for mapping in OSM?  This would probably be better candidate for the best image for Norway than either Bing or DG.

**Comment by FredrikLindseth** [comment]
We actually recently [got permission](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fforum.openstreetmap.org%2Fviewtopic.php%3Fid%3D62083&edit-text=&act=url) to use those, but its a bit of a logistics problem now. We have access to the data, but no tileserver to serve them from. 

This issue will be the same when we get access to those. To set them as default instead of Bing/DG/anything.

**Comment by imagico** [comment]
Does this mean you have permission to use the images but no permission to use the tile services used in those websites?  Or is it just about getting the images served in Mercator?

> This issue will be the same when we get access to those. To set them as default instead of Bing/DG/anything.

This is simple - add them as a layer here and add the 'best' flag to this layer.

**Comment by FredrikLindseth** [comment]
The first. We have no tile services. It's being worked on and I assume this will change soonish

**Comment by simonpoole** [comment]
@FredrikLindseth in what format do you have the imagery (we ... as in SOSM could likely help out).
