### ISSUE TITLE
ELI issues listed by JOSM developers

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/editor-layer-index#496]
If I understand https://josm.openstreetmap.de/ticket/16294#comment:11 and https://josm.openstreetmap.de/wiki/ImageryCompareIgnores correctly there are numerous issues in ELI that were known to JOSM developers and are not reported here

For list of them see https://josm.openstreetmap.de/wiki/ImageryCompareIgnores and search for ELI (witch match case) to find issues that "should be fixed on ​​ELI side (yellow) "

for example " outdated in ELI (missing shape, only rectangle) ", " Non-Standard EPSG codes or not enough entries ", " outdated in ELI ".

**Comment by Klumbumbus** [comment]
Better look at this page https://josm.openstreetmap.de/wiki/ImageryCompare. For interest of ELI are mainly all red, blue and yellow entries, see the documentation at this page. As every red line lets the JOSM continous integration test fail https://josm.openstreetmap.de/wiki/ImageryCompareIgnores was created to turn red entries either in yellow or green.

**Comment by Marc-marc-marc** [comment]
matkoniecz we are several working on reduce diff in both directions.
I have fixed ~20 of them this we

**Comment by rbuffat** [comment]
In the past 1-2 years the scope of ELI's quality checks increased considerably. I don't see currently a listed issue on https://josm.openstreetmap.de/wiki/ImageryCompare that needs urgent action regarding the check scripts.

Also, an issue is that it includes way too much not relevant noise. Without being familiar with the compare script / JOSM its output is not that useful.

**Comment by grischard** [comment]
The [ImageryCompare script](https://josm.openstreetmap.de/browser/josm/trunk/scripts/SyncEditorLayerIndex.java) is actually open source.
