### ISSUE TITLE
Latest update has broken Potlatch 2

### ISSUE THREAD

**Issue by systemed** [osmlab/editor-layer-index#505]
P2 expects to find, at http://osmlab.github.io/editor-layer-index/imagery.json, a JSON document which is an array of imagery sources.

Each source should contain .name and .url at least, and potentially .extent and other stuff.

The document currently available at that URL does not contain any of this and appears to be entirely differently formatted.

**Please, as a matter of urgency, put back the previously formatted document so that people can use P2 again.**

If you would like P2 to consume the data in a different format, please (a) supply a different URL (hint: breaking changes on the same URL are bad, semver is good), (b) raise a P2 issue (or ping me on #osm so that I do), (c) point to some documentation in that issue.

Thank you :)

**Comment by systemed** [comment]
Fixed in https://github.com/osmlab/editor-layer-index/commit/361f8518b35b781b7efa77f0e0dcdb96fbd2a586

**Comment by iandees** [comment]
@systemed I believe you need to run `make` or use a pull request so that the build system will regenerate the file after you changed the code.

**Comment by iandees** [comment]
... or maybe it does it based on commits too. Nevermind 😁

**Comment by grischard** [comment]
My fault, sorry!

@iandees yeah, files are automatically built with travis.

**Comment by systemed** [comment]
@grischard I think Travis has some sort of "continuous integration" malarkey which allows you to avoid situations like this? ;)

**Comment by grischard** [comment]
@systemed "On two occasions I have been asked, — 'Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?' In one case a member of the Upper, and in the other a member of the Lower, House put this question. I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question."

**Comment by systemed** [comment]
In https://github.com/osmlab/editor-layer-index/commit/d07493437f1c8cadc6509e751587b3261b9fff80, for 10 points, examine this line:

    features.append(convert_json_source(args, json.load(f, parse_float=lambda x: str(round(float(x), 5)))))

and answer:

a) how well you think ECMAScript point-in-polygon calculations cope when given arrays of strings rather than floats
b) what entertaining effect this might have on P2's background menu
c) what entertaining effect this might have on P2's developer on spending half the morning debugging this stuff

**Comment by maxerickson** [comment]
Python's `round` fiddles with the underlying representation so just getting rid of the `str()` call should still retain (at least for the most part) the more compact output. I spotted checked output with that change.

Here's what I mean by fiddling with the underlying representation:
	>>> b=2/3
	>>> b
	0.6666666666666666
	>>> b.as_integer_ratio()
	(6004799503160661, 9007199254740992)
	>>> a=round(b,5)
	>>> a
	0.66667
	>>> a.as_integer_ratio()
	(6004829527158177, 9007199254740992)
	>>>

**Comment by grischard** [comment]
Fixed in cd16530

**Comment by grischard** [comment]
`str` had landed there by mistake, not sure why.
