### ISSUE TITLE
DE - Bavaria (80 cm) Please update URL of WMS service

### ISSUE THREAD

**Issue by geowOSM** [osmlab/editor-layer-index#518]
The URL of the _Bavaria (80 cm)_ DOP has been changed by the survey authority, see
https://geoportal.bayern.de/geodatenonline/seiten/wms_dop80cm

old: https://www.geodaten.bayern.de/ogc/ogc_dop80_oa.cgi

**new: https://geoservices.bayern.de/wms/v1/ogc_dop80_oa.cgi**

**Comment by grischard** [comment]
Thanks for this and #519. Closed in a68288c.

Isn't this redundant with the Swiss mapproxy instance at [Bavaria-DOP80.geojson](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/Bavaria-DOP80.geojson) anyway?

Any layers that we should add?

**Comment by geowOSM** [comment]
Thanks @grischard. The Swiss mapproxy instance is a TMS service. It was kindly provided by @simonpoole.

**Comment by grischard** [comment]
But so they're the same images, no? Now that the major editors support WMS servers, it can maybe be retired unless it's faster. Simon, any thoughts?

**Comment by simonpoole** [comment]
AS we don't know who outside of the usual suspects is using the  information in ELI  it isn't really possible to know what impact adding or removing a layer has (I do assume that not everybody has added WMS support). 

Naturally there are other advantages to  proxying requests, for example privacy that can make it attractive regardless of if it is technically required or not. 

In any case if the general feeling is that the proxy is no longer needed I would suggest removing it from the index and I'll turn it off in a month or two.

**Comment by Klumbumbus** [comment]
The tiles of the new URL are unsharp. compare:
https://www.geodaten.bayern.de/ogc/ogc_dop80_oa.cgi?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=by_dop80c&STYLES=&SRS=EPSG:31468&WIDTH=512&HEIGHT=512&BBOX=4462404.6761750,5361567.9174304,4462710.4242750,5361873.6655304

https://geoservices.bayern.de/wms/v1/ogc_dop80_oa.cgi?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=by_dop80c&STYLES=&SRS=EPSG:31468&WIDTH=512&HEIGHT=512&BBOX=4462404.6761750,5361567.9174304,4462710.4242750,5361873.6655304

(position:  48.392310, 11.493013)

**Comment by geowOSM** [comment]
Wow, that appears to be a failed attempt of anti-aliasing and should be a known issue to the survey authority. Maybe that's the reason why the old URLs are still active, initially they were scheduled for switch off after 2018-06-30.

**Comment by grischard** [comment]
The old service is offline now it seems. Maybe you can let the survey authority know? I'm closing this now, but feel free to reopen if there's a sharper URL.

**Comment by Klumbumbus** [comment]
for reference the old and new tile from my post above, which i saved yesterday:
[ogc_dop80_oa cgi_old](https://user-images.githubusercontent.com/7115609/42336883-5969c8ca-8085-11e8-9210-b0a07f148590.jpg)
[ogc_dop80_oa cgi_new](https://user-images.githubusercontent.com/7115609/42336881-5881ad7e-8085-11e8-96ad-cf5643e2a5c1.jpg)

**Comment by geowOSM** [comment]
> Maybe you can let the survey authority know?

I inquired this morning, whether and, if so, when the issue will likely be solved. Will report back.

**Comment by geowOSM** [comment]
> In any case if the general feeling is that the proxy is no longer needed I would suggest removing it from the index and I'll turn it off in a month or two.

@simonpoole, I would be glad if you will keep the proxy, just as a backup. BTW, currently the official URL is down, maybe they are already working on a fix.

**Comment by geowOSM** [comment]
Just a follow-up: The survey confirmed the lower quality of the current DOP80. An enhanced version will be available not before mid 2019. I was told, their IT has to focus on the Gauß-Krüger -> UTM change pending at the end of the year.

Btw, the same problem also relates to their fee-based DOP40 and DOP20. Maybe some key clients will put pressure on them to fix it earlier...

**Comment by geowOSM** [comment]
Just in time for xmas the Bavarian State Survey has released an enhanced DOP80-layer, which is sharper than before.

old url: https://geoservices.bayern.de/wms/v1/ogc_dop80_oa.cgi

**new url**: https://geoservices.bayern.de/wms/v2/ogc_dop80_oa.cgi

The old services will be switched off on 2019-04-01.

**Comment by grischard** [comment]
Thank you @geowOSM! It would be really nice if they just had a 'latest' service.
