### ISSUE TITLE
Some slovenian imageray is not translateable

### ISSUE THREAD

**Issue by manfredbrandl** [osmlab/editor-layer-index#528]
Is this be chance or supposed to be untranslatable?
![image](https://user-images.githubusercontent.com/5360273/43639059-3b22bd98-971b-11e8-9e0d-285f528844c7.png)
(seen from iD)

**Comment by bhousel** [comment]
@manfredbrandl Most imagery strings are not translatable - it only depends on whether the contributor has set `"i18n": true` in the `editor-layer-index` source file.
see https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md#translations

Users mostly only set this for worldwide sources, or sources for countries that speak multiple languages.
