### ISSUE TITLE
traviscibot failed

### ISSUE THREAD

**Issue by Klumbumbus** [osmlab/editor-layer-index#530]
https://github.com/osmlab/editor-layer-index/commit/efd76c0287b6e494c283796c3a8ed83709db8680 was not pushed to the three combined imagery files in https://github.com/osmlab/editor-layer-index/commit/0bf4918321576de514a96ea46d75d59261c56fa3

**Comment by grischard** [comment]
I think it sometimes gets upset and emotional when a new commit arrives before the previous build is done. Is that maybe what happened?

**Comment by grischard** [comment]
Closing as I'm not sure how we could reproduce this :/. But at least it hasn't happened since, even with simultaneous commits.
