### ISSUE TITLE
Invalid date format in English language file en.yaml

### ISSUE THREAD

**Issue by ricloy** [osmlab/editor-layer-index#534]
Hi there!

Two dates changed with the latest commit seem to be invalid:

https://github.com/osmlab/editor-layer-index/blob/cffe4746862353821e36e102da7a01e8171ef24c/i18n/en.yaml#L159

https://github.com/osmlab/editor-layer-index/blob/cffe4746862353821e36e102da7a01e8171ef24c/i18n/en.yaml#L192

**Comment by magol** [comment]
It was my mistake. I have fixed this in PR #535

**Comment by grischard** [comment]
Fixed in #535. Thanks!
