### ISSUE TITLE
Add Orthophotograph of Turku

### ISSUE THREAD

**Issue by theel0ja** [osmlab/editor-layer-index#537]
## URL of the imagery
https://www.avoindata.fi/data/en_GB/dataset/turun-kaupungin-paikkatietorajapinnat

## Two letter country code
FI

## Desired layer name
Orthophotograph of Turku

## License
CC-BY 4.0

## Is the license compatible with OSM?
Requires permission. TODO

## Attribution (text, URL, required?)
`Turun kaupunki` / `City of Turku`

## Icon
(optional)

## Bounding polygon

TODO

**Comment by ilmaisin** [comment]
Since Feb 4 2019, OSM community has had a special waiver that allows the use of City of Turku data, see http://www.turku.fi/avoindata/jhs189 and  http://dev.turku.fi/openstreetmap-lupa.pdf.

**Comment by ilmaisin** [comment]
Here's the bounding polygon.
[turku-ortophoto-polygon.geojson.txt](https://github.com/osmlab/editor-layer-index/files/4121925/turku-ortophoto-polygon.geojson.txt)

**Comment by andrewharvey** [comment]
Does anyone want to have a go at a PR, I'm happy to help review it.

**Comment by theel0ja** [comment]
It seems to have been added into JOSM: https://josm.openstreetmap.de/wiki/Maps/Finland
