### ISSUE TITLE
Please label CantonFribourg-2016 imagery as the best

### ISSUE THREAD

**Issue by ghost** [osmlab/editor-layer-index#542]
Hello,

Is there a reason that the [CantonFribourg-2016 imagery](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/ch/CantonFribourg-2016.geojson) is labelled `"best": false`? It's both the most up-to-date and the most detailed imagery of the Canton of Fribourg we've got.

**Comment by tyrasd** [comment]
see https://github.com/osmlab/editor-layer-index/pull/487#issuecomment-389023472

//cc @simonpoole @Marc-marc-marc

**Comment by grischard** [comment]
@SelfishSeahorse please let us know if that comment is no longer accurate and this issue should be reopened.

**Comment by ghost** [comment]
@grischard: No, i can confirm @Marc-marc-marc's observations. While i still think that the CantonFribourg-2016 imagery is better in general, i'm fine with that decision. I'm sorry, i didn't see that other discussion, otherwise i wouldn't have opened this issue.

**Comment by grischard** [comment]
Thank you! Hope they get us a better 2018 layer :)
