### ISSUE TITLE
One more for thunderforest

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/editor-layer-index#551]
You have 2 types of maps for thunderforest : landscape and cycle

For me the best one is outdoors. An example with the 3 maps are enable here :
https://mc.bbbike.org/mc/?lon=-75.406002&lat=-8.963726&zoom=14&num=3&mt0=thunderforest-outdoors&mt1=thunderforest-landscape&mt2=thunderforest-cyclemap

On outdoors you have the altitude and you can see clearly the tracks/roads.
On landscape you can see nothing (no altitude, roads very badly)
On cycle roads are very good but the altitude are not visible

I don't want you to delete the 2 thunderforest you have, just to add outdoors

## URL of the imagery
https://{switch:a,b,c}.tile.thunderforest.com/outdoors/{zoom}/{x}/{y}.png

## Two letter country code
Sorry, I don't know waht you want : I think for every country ?

## Desired layer name
Thunderforest outdoors

## License
I think you need one, myself I have a ?apikey= to use it

## Is the license compatible with OSM?
Yes, thunderforest is part of OSM I believe ?

**Comment by bhousel** [comment]
I was actually going to suggest dropping the Thunderforest maps from the index, since OpenTopoMap #550 now exists since June 2018 for mappers who want to see elevation contours.  

I don't have any strong opinion on keeping or removing them, but removing them may save @gravitystorm some money 💸 

#143 / #145 have some background discussion

**Comment by gravitystorm** [comment]
I'm happy to see them continue in the index, for as long as there's a desire to have them here.

**Comment by Mahabarata** [comment]
I agree with bhousel : for a very long time I loved thunderforest-outdoors (I'm using it on my own web site) : that why I open this issue.
But I didn't know osmtopomap.

Here a comparaison of both, in Peru :
https://mc.bbbike.org/mc/?lon=-76.69980&lat=-10.81405&zoom=13&num=2&mt0=opentopomap&mt1=thunderforest-outdoors
the first is clearly the best one

But in France, near where I lived :
https://mc.bbbike.org/mc/?lon=6.197&lat=45.62&zoom=13&num=2&mt0=opentopomap&mt1=thunderforest-outdoors
on the thunderforest, you have trails not visible on osmtopomap. And you have not the same names.

So I think it will be great to have both.

And I definetely don't like thunderforest landscape and cycle, outdoors is better I think. So for me to delete these 2 won't be a pb, if you need to make this choice.

@gravitystorm : you want lanscape and cycle, no pb for me of course. But what about outdoors ? And if it is impossible (even if i don't know why) to have the 3 thunderforest, which 2 (or 1) would you prefer to have ?
Best regards

**Comment by grischard** [comment]
Closed in ddb2695
