### ISSUE TITLE
IBGE layers are erroring with 401 (unauthorized)

### ISSUE THREAD

**Issue by naoliv** [osmlab/editor-layer-index#555]
The layers _IBGE_Setores_Urbanos_ and _IBGE_Setores_Rurais_ aren't working anymore (failing with a 401 error).

The addresses without a key (and with `v3` instead the ones with `v4` in the index) are working as expected:

`https://{switch:a,b,c,d}.tiles.mapbox.com/v3/tmpsantos.hgda0m6h/{zoom}/{x}/{y}.png`
`https://{switch:a,b,c,d}.tiles.mapbox.com/v3/tmpsantos.i00mo1kj/{zoom}/{x}/{y}.png`

I am unsure if we can simply switch to those addresses or if new access tokens are needed for the `v4` addresses.

**Comment by naoliv** [comment]
CC @tmpsantos ;-)

**Comment by tmpsantos** [comment]
Hi @naoliv, there seems to be a problem indeed. I'm trying to find out what happened. Thanks for reporting.

**Comment by bhousel** [comment]
Hey, it looks like these were using the old openstreetmap token which I recently rotated.  I just updated the sources with the updated access token.

**Comment by naoliv** [comment]
Are there any relevant differences between the `v3` and `v4` versions?

**Comment by bhousel** [comment]
> Are there any relevant differences between the `v3` and `v4` versions?

I don't know..
