### ISSUE TITLE
au/act/statewide

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/editor-layer-index#590]
The au/act/statewide Imagery layers are currently broken as the WMS Server resource is no longer available.

The WMTS feeds still work for JOSM `http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/imagery2018mga/ImageServer/WMTS/1.0.0/WMTSCapabilities.xml`.

I'm following up with the provider to see if this was an intentional change, if it was then given the WMTS is in the MGA projection I don't see it being able to work in iD at the moment.

Is there a proper format to document WMTS layers for JOSM?

**Comment by Klumbumbus** [comment]
>Is there a proper format to document WMTS layers for JOSM?

Do you mean here at ELI?

**Comment by andrewharvey** [comment]
Yeah sorry I mean here on the ELI.

**Comment by Klumbumbus** [comment]
I don't think so. https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json doesn't contain WMTS as type. It should be possible to convert the URL into a TMS though.
(However for JOSM users there is no real need to use ELI instead of the JOSM list.)

**Comment by grischard** [comment]
Two separate PRs would be very welcome:

- a script that takes a WMTS capabilities url and spits out nice TMS URLs
- a patch to schema.json to accept WMTS as a type

**Comment by andrewharvey** [comment]
While that would be a nice addition, end of the day these tiles are in MGA projection, so unusable in iD and JOSM doesn't use this index by default, so for this source I'm not sure it would help.

**Comment by grischard** [comment]
If not in this particular one, then for the many in https://josm.openstreetmap.de/wiki/ImageryCompare that ELI doesn't have.
