### ISSUE TITLE
WMS Maps4BW

### ISSUE THREAD

**Issue by bhousel** [osmlab/editor-layer-index#592]
_From @robybully on November 22, 2018 12:23_

The previous background source of Maps4BW (Baden-Württemberg, Germany) from webatlas.de WMS layer doesn't work any more.

Service is now available under https://www.lgl-bw.de/lgl-internet/opencms/de/07_Produkte_und_Dienstleistungen/Open_Data_Initiative/ respectively https://www.geoportal-bw.de

For more infos see https://josm.openstreetmap.de/ticket/16895

_Copied from original issue: openstreetmap/iD#5517_

**Comment by robybully** [comment]
A user sends me this link:
https://github.com/osmlab/editor-layer-index/commit/cce76dc
So it's already commited. Is something missing for using in iD? An update?

**Comment by grischard** [comment]
Closing as invalid then. The output is statically included in iD and only gets updated when a new version of iD gets released.

Can I ask you for your thoughts on #586?

**Comment by bhousel** [comment]
> Can I ask you for your thoughts on #586?

Do you mean me?

**Comment by grischard** [comment]
Yes! Well, if roby has thoughts on it, they're very welcome too.
