### ISSUE TITLE
Ohio Statewide Imagery Program

### ISSUE THREAD

**Issue by 1ec5** [osmlab/editor-layer-index#593]
The [Ohio Statewide Imagery Program](https://ogrip.oit.ohio.gov/ProjectsInitiatives/StatewideImagery.aspx) (OSIP) publishes 3-inch, 6-inch, or 1-foot orthorectified imagery of most counties in the U.S. state of Ohio on a rotating schedule. The current iteration, OSIP III, is currently available in about half the state ([see map](http://gis5.oit.ohio.gov/geodatadownload/)).

## URL of the imagery
* https://geo.oit.ohio.gov/arcgis/rest/services/OSIP/OSIP_6in_best_avail/ImageServer/
* https://geo.oit.ohio.gov/arcgis/rest/services/OSIP/osip_best_avail_1ft/ImageServer/ ([details](http://ogrip-geohio.opendata.arcgis.com/datasets/osip-1-foot-imagery-most-current-available))
   ```
   wms:https://geo.oit.ohio.gov/arcgis/services/OSIP/osip_best_avail_1ft/ImageServer/WMSServer?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
   ```
* https://geo.oit.ohio.gov/arcgis/rest/services/most_current_imagery/ImageServer/

## Two letter country code
US

## Desired layer name
Ohio Statewide Imagery Program

## License
All OSIP orthoimagery is [in the public domain](https://ogrip.oit.ohio.gov/Portals/0/PDFs/OSIP%20Program%20Description.pdf#page=2). (Also [confirmed](https://lists.openstreetmap.org/pipermail/talk-us/2010-January/002632.html) on the talk-us mailing list.)

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
> [Ohio Statewide Imagery Program](https://ogrip.oit.ohio.gov/ProjectsInitiatives/StatewideImagery.aspx)

(not required)

## Privacy policy (URL)
https://ogrip.oit.ohio.gov/privacy.aspx

## Icon
![ogrip](https://ogrip.oit.ohio.gov/portals/0/Images/logo_OGRIP.jpg)

Or, if a public domain icon is needed:

![oit](https://ogrip.oit.ohio.gov/portals/0/Images/OIT_Logo.gif)

## Bounding polygon
OSIP I, II, and III together cover more or less the entirety of [Ohio](https://www.openstreetmap.org/relation/162061), excluding [Lake Erie](https://www.openstreetmap.org/relation/4039900). (Lake Erie islands are included.) The coverage area mostly follows [Ohio county boundaries](http://overpass-turbo.eu/s/E50).

**Comment by don-vip** [comment]
[Added in JOSM](https://josm.openstreetmap.de/wiki/Maps/USA?action=diff&version=144&old_version=142).

**Comment by 1ec5** [comment]
Thanks, @don-vip!

By the way, that’s the 1-foot image service. The 6-inch service covers some of the same counties with higher-resolution imagery, but no WMS server is enabled for it. I was able to view the 6-image orthoimagery in JOSM after using [the 1-foot server’s GetCapabilities URL](https://geo.oit.ohio.gov/arcgis/services/OSIP/osip_best_avail_1ft/ImageServer/WMSServer?request=GetCapabilities&service=WMS) but replacing the resulting entry with an exportImage URL:

```
wms[1,22]:https://geo.oit.ohio.gov/arcgis/rest/services/OSIP/OSIP_6in_best_avail/ImageServer/exportImage?f=image&bbox={bbox}&imageSR=4326&bboxSR=4326&size={width}%2C{height}
```

Here’s a similar entry for the OSIP Most Current Imagery service, which seems to be identical to the 1-foot image service in the places I’ve spot-checked:

```
wms[1,22]:https://geo.oit.ohio.gov/arcgis/rest/services/most_current_imagery/ImageServer/exportImage?f=image&bbox={bbox}&imageSR=102100&bboxSR=102100&size=512%2C512
```

Unfortunately, there isn’t a service for the more recent 3-inch imagery that’s beginning to appear, so far in nine counties. That imagery is only [available for download](http://gis5.oit.ohio.gov/geodatadownload/) county-by-county in MrSID format or as GeoTIFFs at a single, very high zoom level.
