### ISSUE TITLE
LINZ imagery api key

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/editor-layer-index#602]
NZ's LINZ imagery was using a shared API key for access to the web services. That API key has been revoked (by Koordinates) and we can't pre-bundle a key going forward according to the service provider (Koordinates), so these sources are now broken.

OSM contributors can still use the LINZ imagery in iD and JOSM but they need to manually create their own API key and add a custom layer which isn't ideal for the casual mapper, but can work for power mappers.

The alternative is we need to host this imagery elsewhere either on OSMF or local chapter infrastructure, or donated via Mapbox.

**Comment by simonpoole** [comment]
See https://github.com/osmlab/editor-layer-index/pull/548 (if implemented the editors could if they saw fit display a popup and ask for the key).

How much (size wise) imagery are we talking about?

**Comment by andrewharvey** [comment]
> See #548 (if implemented the editors could if they saw fit display a popup and ask for the key).

That would work.

> How much (size wise) imagery are we talking about?

Imagery is 10TB as TIFF, 1.3TB as JPG, 966GB as JPEG2000, which costs $540 to order (it's over the 3.5GB download limit).

Topo is 10GB as JPG or 20GB as TIFF

**Comment by simonpoole** [comment]
@Firefishy any thoughts? At least for us (SOSM) while we have quite a lot of infrastructure available and host a number of sources, we would really need to think about the disk space requirements.

**Comment by Klumbumbus** [comment]
>That API key has been revoked and we can't pre-bundle a key going forward according to the service provider (Koordinates), so these sources are now broken.

For me the two sources seem to work fine in JOSM.

**Comment by Firefishy** [comment]
Would they allow us to have an OSM proxy server which added the key?

**Comment by andrewharvey** [comment]
> For me the two sources seem to work fine in JOSM.

Actually that's the case for me too. They said they revoked the API key so I don't know.

> Would they allow us to have an OSM proxy server which added the key?

I'll ask.

**Comment by grischard** [comment]
> Would they allow us to have an OSM proxy server which added the key?

This is what the French community does for the IGN Orthophotography, actually. The French RP whitelists some user agents and referers, and has an api key for everyone else.

**Comment by grischard** [comment]
@andrewharvey 	I was just talking about API keys, and wondering if you'd been able to ask whether an OSM proxy would be ok. Otherwise, I don't really want to require casual mappers to register for API keys.

**Comment by andrewharvey** [comment]
@grischard The response I got was to ask support@koordinates.com, but due to priorities I never got to doing that. If you can, it would be great if you could ask, and see if that's an acceptable solution.

**Comment by Firefishy** [comment]
@andrewharvey @grischard I am part of the OSM sysadmin team, I am happy to setup a proxy if desired and as required. The proxy can inject keys, header, cache or whatever as required. Let me know more details. How many layers?

**Comment by brivars** [comment]
Stumbled upon this while trying to find out why are the LINZ layers not working in iD editor.
That would be great to have a popup implemented that asks for the own api key and provides a link and short explanation on how to register for LDS. 

Meanwhile, the ESRI Clarity imagery actually uses the same imagery, it's just not as sharp as one on LINZ servers.
The topo layer is really useful though.

**Comment by andrewharvey** [comment]
According to https://www.linz.govt.nz/data/linz-data-service/guides-and-documentation/rate-limiting LINZ's service provider Koordinates may revoke access where customers overuse the API, which is what's happen here.

The document also says that "If you are developing an application, we recommend that you cache data client-side and that you avoid requesting tiles that have not changed.", so if we run a caching proxy server that would alleviate some load, but gven users are likely looking at high zoom tiles less likely to be cache hits, it's hard to say if this would be acceptable without knowing usage patterns and what Koordinates set the limit at.

"Topo50 maps are updated 4-5x per year and the NZ Aerial Imagery set is updated around 2x per year"

It's probably worth trying this caching proxy, and just wait and see if the resultant loads for LINZ/Koordinates are low enough.

Cameron_D has set up a caching proxy on his own infrastructure per https://maptimeoceania.slack.com/archives/C42BW30LB/p1557722166024200 along with the offer from @Firefishy we should be right technically implementing that.

At the moment Daniel Silk from LINZ is trying to confirm internally if this caching proxy approach is okay, so hopefully soon we can get these layers back up and running.

**Comment by Torvin** [comment]
Looks like this issue is taking quite some time. Can we at least make the 'ESRI Clarity' layer the default in the meantime? Right now it's just black background when people try to edit stuff.

**Comment by andrewharvey** [comment]
Yes, please feel free to submit a PR which removes this broken source until it can be fixed.

**Comment by grischard** [comment]
Hmm, it's sad it has to come to this.

There's nothing in the CC license that https://data.linz.govt.nz/data/category/aerial-photos/ are under that prohibits setting up our own server, but of course that means someone has to spend time maintaining it.

There's also nothing that prevents us from running a mapproxy to at least alleviate the issue for now, and adapting the mapproxy config if and when we hear anything back from LINZ.

In the meanwhile, I'll deactivate the NZ layers and close this.
