### ISSUE TITLE
Remove OS125khistoric-OSM as it is a duplicate

### ISSUE THREAD

**Issue by boothym** [osmlab/editor-layer-index#607]
Or at least add an end_date of 1962 so it doesn't show up in iD.

This layer: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OS125khistoric-OSM.geojson

is the same as: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/NLS-OS125k1stSeries1937-61.geojson

but the first one has a fraction of the coverage (see below). Doesn't make sense to keep them both. 
![id](https://user-images.githubusercontent.com/16965772/50237644-5914a580-03b5-11e9-87d5-1945691293aa.JPG)

**Comment by don-vip** [comment]
They are not exactly the same, the one with partial coverage has more details, and has better quality:

![os2](https://user-images.githubusercontent.com/596867/50800397-59330180-12e0-11e9-990a-924902751431.PNG)

![os1](https://user-images.githubusercontent.com/596867/50800374-3f91ba00-12e0-11e9-9d94-dae8a662c56f.PNG)

**Comment by boothym** [comment]
Interesting, thanks for checking that out. In that case, if both are to be kept the first layer should still have an end_date added to be consistent with the rest of them.
