### ISSUE TITLE
Franklin County, Ohio

### ISSUE THREAD

**Issue by 1ec5** [osmlab/editor-layer-index#616]
The [City of Columbus GIS agency](https://www.columbus.gov/Templates/Detail.aspx?id=68426) publishes 3-inch orthoimagery of Franklin County, Ohio, that was collected as part of the Ohio Statewide Imagery Program (#593).

## URL of the imagery
http://maps.columbus.gov/arcgis/rest/services/Imagery/Imagery2017/MapServer

## Two letter country code
US

## Desired layer name
Columbus 2017 Orthophotography

## License
Public domain
(as part of OSIP)

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
Columbus GIS, [Ohio Statewide Imagery Program](https://ogrip.oit.ohio.gov/ProjectsInitiatives/StatewideImagery.aspx)
(not required)

## Privacy policy (URL)
https://www.columbus.gov/Privacy/

## Icon
[<img src="https://www.columbus.gov/favicon.ico" width="16" alt="">](https://www.columbus.gov/favicon.ico)

## Bounding polygon
[GeoJSON](https://gist.github.com/1ec5/83834773000d2949973d34d8fefa18b1)

The coverage area overlaps with OSIP (#593).

**Comment by EarthAdam** [comment]
According to one of the GIS Analysts at the City of Columbus, OSIP imagery for the City of Columbus is public domain.
![image](https://user-images.githubusercontent.com/8453197/51555828-8cc86c80-1e46-11e9-91f8-2d2d84f6fe1f.png)
They couldn't say for anything outside of the city though as that's governed by OGRIP.

**Comment by 1ec5** [comment]
Fixed in #1298.
