### ISSUE TITLE
Verify tms link for Kartverket N50 Topo (Norway)

### ISSUE THREAD

**Issue by simurq** [osmlab/editor-layer-index#618]
Trying to get tile data using `https://opencache{switch:,2,3}.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo4&zoom={zoom}&x={x}&y={y}` doesn't yield any result. Can you pls verify that the link is actually downloading tile data?

Thanks!

**Comment by NKAmapper** [comment]
Yes, that is the correct link, and it is downloading tiles. Perhaps it was temporarily out of service.

**Comment by NKAmapper** [comment]
This issue may be closed now.
