### ISSUE TITLE
Labels for vector layers

### ISSUE THREAD

**Issue by astoff** [osmlab/editor-layer-index#623]
Is it possible to add a label field to vector layers?

[This source](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/south-america/br/IBGE-BC250_unidade_de_uso_sustentavel.geojson) has the field `nome` which should be displayed. Currently, the overlay shows boundaries without any extra information, and it is causing a lot of seemingly random `leisure=nature_reserve` to be traced by users.

**Comment by astoff** [comment]
Ok, now I see that the overlay is rasterized server-side. So I assume there is really no way to add a label afterwards.

**Comment by grischard** [comment]
Not from our side, unfortunately! Maybe there's a second layer for the names?
