### ISSUE TITLE
Add the IBGE Street Names layer

### ISSUE THREAD

**Issue by afmenez** [osmlab/editor-layer-index#645]
There's a [new layer with street names available for Brazil](https://www.openstreetmap.org/user/naoliv/diary/47882), it would be nice to have it available with the other IBGE layers.
It is already available in JOSM.

## URL of the imagery
https://maps.tilehosting.com/c/1c4f953c-e2be-42f4-ac76-ae6fed6f7534/styles/faces/{z}/{x}/{y}.png?key=YmPoUxbTlEHlrASzv56Z

## Two letter country code
BR

## Desired layer name
IBGE Street Names

## License
It is the same as the other IBGE layers already available.

## Is the license compatible with OSM?
It is the same as the other IBGE layers already available.

## Attribution (text, URL, required?)
IBGE

## Privacy policy (URL)
-

## Icon
-

## Bounding polygon
Brazil, the same as the other IBGE layers.

**Comment by naoliv** [comment]
It should be fixed after https://github.com/osmlab/editor-layer-index/pull/672

**Comment by afmenez** [comment]
The URL is different, is it the same layer?

**Comment by naoliv** [comment]
It's the same layer.
The URL had to be updated due to https://www.maptiler.com/blog/2019/04/maptiler-cloud-infrastructure-upgrade.html#new-domain

**Comment by afmenez** [comment]
Solved by #672
