### ISSUE TITLE
Removal of "best" parameter from "eox.at 2018 cloudless"

### ISSUE THREAD

**Issue by higa4** [osmlab/editor-layer-index#650]
Few days ago, an imagery named "eox.at 2018 cloudless" has been added.
https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/world/eox.at-2018-cloudless.geojson
But, in the header of geojson file, the "best" parameter is set as below:
"best": true,
As a result of this setting, it seems to be displayed at the top of iD editor's imagery list all around the world as the best one, I guess.
Is it possible to remove this parameter, or at least reduce the cover area? It seems quite unclear in Japan as below (iD preview website).
![iD preview site](https://i.imgur.com/pqTcjkI.png)

**Comment by grischard** [comment]
Yes! Fixed in 76cb95e5cb43682412061e23bc58bf2207f437fb
