### ISSUE TITLE
Locator Overlay

### ISSUE THREAD

**Issue by Thorwynn** [osmlab/editor-layer-index#692]
Is this the right place to complain, I mean inquire, about the "Locator Overlay" layer?
Is it maintained by Mapbox?
It is very out of date. How often is it updated?
It also has no town-lines which makes it almost useless as a locator map. I was able to prevent this from giving me an aneurysm by using a custom background of local town-lines. But it may prevent the untimely demise of our new mappers if town-lines were added to the locator overlay.

**Comment by bhousel** [comment]
Can you make your point without all the "aneurysms" and "untimely demise".   It's hard for me to take issues like this seriously when people act like an old overlay layer is killing people.  You're not funny.

**Comment by grischard** [comment]
It seems like there is no actionable item for the ELI maintainers here.

**Comment by bhousel** [comment]
It turns out that the Locator Overlay is using a legacy Mapbox API and we need to upgrade it to a new styles API, so rather than open a new issue, I'm just reopening this one and assigning to myself.  After the upgrade, it might get more frequent updates.

**Comment by andrewharvey** [comment]
That's the conclusion I came to in https://github.com/openstreetmap/iD/issues/7025

> I couldn't find any further details, is it using mapbox-streets tilesets? Perhaps it's using Mapbox Streets v6 or lower which are no longer receiving data updates from OSM?

I'll close that ticket in favour of this one here.

**Comment by grischard** [comment]
Yay, Bryan is back :).

**Comment by bhousel** [comment]
> Yay, Bryan is back :)

Not really “back”, I just need to do this thing or the overlay may stop working sometime next year.

**Comment by erickdeoliveiraleal** [comment]
This helps a lot along with the Strava layer to check where it is badly mapped.

**Comment by grischard** [comment]
@mikelmaron tag, you're it! :)

**Comment by grischard** [comment]
Fixed in #840

**Comment by erickdeoliveiraleal** [comment]
In JOSM this new layer hides when zoom is higher, how can I make it to work?

**Comment by erickdeoliveiraleal** [comment]
I changed it to tms[3,15] and it is now working.
