### ISSUE TITLE
Add additional NLS maps for GB

### ISSUE THREAD

**Issue by boothym** [osmlab/editor-layer-index#700]
I got in touch with the NLS and they have updated the wiki page with some additional out of copyright imagery layers, quite detailed and mostly covering Scotland. https://wiki.openstreetmap.org/w/index.php?title=National_Library_of_Scotland&type=revision&diff=1892687&oldid=1235691

I've detailed them below:

**NLS - OS/War Office - GSGS 3906 1:25,000, 1940-43**

tms:https://geo.nls.uk/mapdata3/gsgs3906/{z}/{x}/{y}.png (Max zoom 16)

**NLS - OS 1:10,560 National Grid Maps, 1940s-1960s (This layer covers most of Great Britain).**

tms:https://geo.nls.uk/mapdata3/os/britain10knatgrid/{z}/{x}/{y}.png (Max zoom 16)

**NLS - OS 1:1,250 National Grid Maps, 1940s-1960s**

tms:https://geo.nls.uk/mapdata3/os/scotland_1250_country/{z}/{x}/{y}.png (Max zoom 20)

**NLS - OS 1:2,500 National Grid Maps, 1940s-1960s - single sheets**

tms:https://geo.nls.uk/maps/os/scotland_2500_singles/{z}/{x}/{y}.png (Max zoom 18)

**NLS - OS 1:2,500 National Grid Maps, 1940s-1960s - double sheets**

tms:https://geo.nls.uk/maps/os/scotland_2500_doubles/{z}/{x}/{y}.png (Max zoom 18)

**Comment by grischard** [comment]
Thank you again!
