### ISSUE TITLE
OSMI-Layers not working anymore

### ISSUE THREAD

**Issue by mh166** [osmlab/editor-layer-index#706]
Their URLs seem to be broken:

![image](https://user-images.githubusercontent.com/3167596/64341501-c5d5db80-cfe8-11e9-992d-1932590dc99b.png)

Unfortunately, I don't know what replacement would be suitable as I don't know the original purpose of these layer.

**Comment by Nakaner** [comment]
This was caused by a misconfiguration on the server. It has been fixed. All layers listed in Editor Layer Index should work now.

**Comment by grischard** [comment]
Thank you @Nakaner
