### ISSUE TITLE
Potential source for Iowa

### ISSUE THREAD

**Issue by maxerickson** [osmlab/editor-layer-index#710]
When **requesting the addition of an imagery layer**, please provide the following information. Otherwise, delete the text and type your issue.

## URL of the imagery
https://athene.gis.iastate.edu/arcgis/rest/services/ortho/ortho_2018_nc/ImageServer
## Two letter country code
us

## Desired layer name
Iowa 2018 Ortho

## License
unclear

## Is the license compatible with OSM?
unclear

There's also a bunch more layers at https://athene.gis.iastate.edu/arcgis/rest/services/ortho

**Comment by cicku** [comment]
Your URL returns 404. I will close this one. However, I guess you mean https://www.arcgis.com/home/item.html?id=fa6231ebdf8a4111b5e2ac4c6417f1cd.

For Des Moines area, unfortunately all other sources are currently prohibited due to non-free license agreement.
