### ISSUE TITLE
Add SanGIS 2017 Imagery (San Diego County, California, US)

### ISSUE THREAD

**Issue by mds08011** [osmlab/editor-layer-index#711]
## URL of the imagery
https://gis.sangis.org/maps/rest/services/Public/Imagery_2017/MapServer

## Two letter country code
us

## Desired layer name
San Diego (SanGIS) 2017

## License
Public Domain.  All SanGIS data was placed in the Public Domain in December 22, 2005: https://wiki.openstreetmap.org/wiki/SanGIS
*"...After much discussion, the Board voted to discontinue licensing and sales of data, placing the data in the public domain."*

## Is the license compatible with OSM?
Yes it is Public Domain.

## Attribution (text, URL, required?)
>End users are encouraged to cite SanGIS with the following Modern Language Association (MLA) 2008 accepted citation format for websites and website content when it is included in reports, papers, publications, and presentations:

>< Name of Dataset Author >. "Name of Dataset as downloaded" Name of Organization associated with Author SanGIS Data Warehouse. < Date the Dataset was Created >. San Diego Geographic Information Source - JPA. < Date Downloaded > < http://www.sangis.org/download/index.html >.

## Privacy policy (URL)
See comment below: https://github.com/osmlab/editor-layer-index/issues/711#issuecomment-536134464

## Icon
See comment below: https://github.com/osmlab/editor-layer-index/issues/711#issuecomment-536134619

## Bounding polygon
San Diego County 5 mile buffer:
* JSON direct link: https://gis.sangis.org/maps/rest/services/Public/Imagery_2017/MapServer/0?f=pjson
* ArcGIS Rest Directory: https://gis.sangis.org/maps/rest/services/Public/Imagery_2017/MapServer/0

Imagery is based on a 5 mile buffer around the county, but if neither of the sources I provided above are workable formats (I am not very familiar with JSON), this is a .shp file of the county boundary (without the 5 mile buffer): [County_Boundary.ZIP](https://github.com/osmlab/editor-layer-index/files/3664905/County_Boundary.ZIP)

**Comment by grischard** [comment]
Privacy policy: http://sangis.org/privacy.html

**Comment by grischard** [comment]
http://sangis.org/favicon.ico converted to png might be a good icon.

**Comment by mds08011** [comment]
Thank you, those are good additions!
