### ISSUE TITLE
Reference: New data layer avaliable for Croatia

### ISSUE THREAD

**Issue by tordans** [osmlab/editor-layer-index#713]
For reference from http://weeklyosm.eu/archives/12408:

> <li id="wn479_20959">… of all the new aerial imagery that is available for OSM in Croatia? The Croatian State Geodetic Administration <a href="https://osm-hr.org/2019/06/04/pravo-koristenja-mreznih-usluga-prostornih-podataka-drzavne-geodetske-uprave/">changed</a> (automatic <a href="https://translate.google.com/translate?sl=auto&amp;tl=EN&amp;u=https://osm-hr.org/2019/06/04/pravo-koristenja-mreznih-usluga-prostornih-podataka-drzavne-geodetske-uprave/">translation</a>) their Geoportal terms of use to allow derivative works, so the aerial imagery and topographic maps can now be used for OSM. In addition, the cities of <a href="https://osm-hr.org/2019/04/11/digitalni-ortofoto-grada-knina-na-tms-serveru/">Knin</a> (automatic <a href="https://translate.google.com/translate?sl=auto&amp;tl=EN&amp;u=https://osm-hr.org/2019/04/11/digitalni-ortofoto-grada-knina-na-tms-serveru/">translation</a>) and <a href="https://osm-hr.org/2019/04/12/digitalni-ortofoto-grada-zagreba-2012-na-tms-serveru/">Zagreb</a> (automatic <a href="https://translate.google.com/translate?sl=auto&amp;tl=EN&amp;u=https://osm-hr.org/2019/04/12/digitalni-ortofoto-grada-zagreba-2012-na-tms-serveru/">translation</a>) have granted the use of their aerial imagery from 2007 and 2012 for use in OSM. Zagreb also <a href="https://osm-hr.org/2019/04/15/digitalni-ortofoto-grada-zagreba-2018-na-tms-serveru/">provides</a> (automatic <a href="https://translate.google.com/translate?sl=auto&amp;tl=EN&amp;u=https://osm-hr.org/2019/04/15/digitalni-ortofoto-grada-zagreba-2018-na-tms-serveru/">translation</a>) imagery with a resolution of 20 cm. Data has been processed and <a href="https://tms.osm-hr.org/">is served</a> as a TMS layer on the OSM Croatia server.</li>

From this, it look like there are more data layer that could be added to the index:

- [ ] Areal Images for the whole of Croatia
- [x] Knin 2007, https://osm-hr.org/2019/04/11/digitalni-ortofoto-grada-knina-na-tms-serveru/ => Done by @hbogner https://github.com/osmlab/editor-layer-index/pull/643 as far as I can see
- [ ] Knin 2012
- [ ] Zagreb 2007
- [ ] Zagreb 2012, https://osm-hr.org/2019/04/12/digitalni-ortofoto-grada-zagreba-2012-na-tms-serveru/
- [ ] Zagreb 2018, https://osm-hr.org/2019/04/15/digitalni-ortofoto-grada-zagreba-2018-na-tms-serveru/

**Comment by hbogner** [comment]
They combined 5 posts to 1 in osmweekly so there are some mistakes.
Knin 2007 is done
Knin 2012 does not exist
Zagreb 2007 does not exist
Zagreb 2012 is also added in https://github.com/osmlab/editor-layer-index/pull/663
Zagreb 2018 waiting in pull request: https://github.com/osmlab/editor-layer-index/pull/715
State Geodetic Administration layers are also being prepared as we speak.

**Comment by tordans** [comment]
@hbogner thanks for the update and details. I will close this issue since you are already on it.

**Comment by hbogner** [comment]
I'm on it for some time, unfortunately was busy, but OSM Weekly forced me to act.
Don't forget to merge my pull requests ;)

**Comment by tordans** [comment]
> I'm on it for some time, unfortunately was busy, but OSM Weekly forced me to act.

:-)

> Don't forget to merge my pull requests ;)

Just to be clear, I am just a contributor as you are.

**Comment by hbogner** [comment]
Ah, you shattered my dreams for a quick pull request ;)

**Comment by andrewharvey** [comment]
Thanks for the PR, it will get merged, if no one else does, then I can, but I just haven't merged it yet to give time for others to provide feedback.
