### ISSUE TITLE
Wrocław Orthophotomap 2018

### ISSUE THREAD

**Issue by maro-21** [osmlab/editor-layer-index#729]
New aerial imagery for Wrocław, Poland has been available since September 2018.

The license is compatible with OSM because it is available under the same license as 2015 version which is already here.

To do:
- Create a file /sources/europe/pl/WrocawOrthophotomap2018(aerialimage).geojson
Everything will be the same like here: https://github.com/osmlab/editor-layer-index/blob/f20589a74fd20e78c4222304f9148ce7c79c1a18/sources/europe/pl/WrocawOrthophotomap2015(aerialimage).geojson?short_path=da7890e
just change 2015 to 2018 and add
	- "best": true,
	- "start_date": "2018-04-06",
	- "end_date": "2018-04-07",
	- ""i18n": true"
- Move it to the top position on the list of layers, if it's possible
- add to editor-layer-index/i18n/en.yaml (https://github.com/osmlab/editor-layer-index/blob/f20589a74fd20e78c4222304f9148ce7c79c1a18/i18n/en.yaml) so the name of the layer can be translatable
- Don't remove the 2015 version – although it's older, it may be still helpful because the angle of the photos is different

sources:
- https://forum.openstreetmap.org/viewtopic.php?id=63644
- http://geoportal.wroclaw.pl/en/resources/

Thank you in advance!

**Comment by grischard** [comment]
They don't have a privacy policy, do they?

**Comment by maro-21** [comment]
I think they don't. I haven't found it.

**Comment by maro-21** [comment]
Is privacy policy really necessary to add this imagery?

**Comment by andrewharvey** [comment]
In my opinion if upstream has no privacy policy we should still accept the source, anyone who cares about this downstream can just then assume they have are afforded no privacy.

**Comment by grischard** [comment]
@maro-21 we can add https://www.wroclaw.pl/polityka-prywatnosci

**Comment by grischard** [comment]
@andrewharvey I think @simonpoole and LWG believe that we must?

**Comment by simonpoole** [comment]
Well it depends on the definitions of "we" and "must".

People providing an editor clearly (as in: it's the law) need to indicate when personal data is being made available to a third party and in the case of background imagery this is not obvious as for example clicking on a link on a website is. And from an UX pov it would be user friendlier to make a privacy policy link available than only to popup a dire warning.

But the above is the responsibility of the app operator and not "ours", but if the goal of this isn't to make life easier for those operators, what is the point of doing all the work in the 1st place

**Comment by grischard** [comment]
But that's two different things - making the user aware that data is being sent, and making the user aware of how that data will be used, no?

Sorry for derailing your ticket, @maro-21 :)

**Comment by andrewharvey** [comment]
> People providing an editor clearly (as in: it's the law) need to indicate when personal data is being made available to a third party and in the case of background imagery 

@simonpoole @grischard Can't those editors just have a generic notice that by accessing third party imagery layers you're using an external service and some usage data will be provided to that third party if you choose to enable that imagery layer?

If the upstream imagery provider has to privacy policy we set it to `null` here and then each editor can decide what to do when they encounter a source with no privacy policy. It shouldn't be a blocker for people to use that imagery for OpenStreetMap.

**Comment by grischard** [comment]
Yeah, setting it to 'null' if there isn't one at all sounds good to me.

**Comment by pawelcegiela** [comment]
What is the status of this issue? Is the orthophotomap going to be added to OSM? If so, when can we expect it?

**Comment by grischard** [comment]
@tslipa Welcome to github! Someone needs to create what's called a pull request with the appropriate geojson to add this to the index.

The good news is that you can mostly copy sources/europe/pl/WrocawOrthophotomap2015(aerialimage).geojson, and that there's a howto linked in Contributing.md in the project root.

Would you like to give it a go, and tell us here if you run into any trouble?

**Comment by pawelcegiela** [comment]
Well, there's just a problem that I have no experience in such things at all and I don't feel like I'd manage. So, in my opinion, it would be better if someone more experienced created such a pull request. Of course, if nobody comes forward to doing it in the nearest future, I will try.

**Comment by wiktorn** [comment]
@grischard, @andrewharvey: I tried to create PR for that, but Travis checks fail on privacy policy. It can't be null and has to be reachable.

Should I modify the schema and checks so it's possible to set `privacy_policy_url` to `null`?

**Comment by grischard** [comment]
Even better, set it to http://bip.um.wroc.pl/artykul/7/32673/dane-osobowe or https://www.wroclaw.pl/polityka-prywatnosci :)

**Comment by grischard** [comment]
And we're good to go :)

**Comment by maro-21** [comment]
Thank you!
