### ISSUE TITLE
Remove PolandGeoportal.geojson and edit other

### ISSUE THREAD

**Issue by maro-21** [osmlab/editor-layer-index#741]
- [x] Please remove "PolandGeoportal.geojson"
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/PolandGeoportal.geojson - it doesn't work anymore.

- [ ] edit  /sources/europe/pl/WrocawOrthophotomap2015(aerialimage).geojson
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/WrocawOrthophotomap2015(aerialimage).geojson
and add
	- `"start_date": "2015-06-05",`
	- `"end_date": "2015-06-06",`
	- `"i18n": true"`

- [ ] edit /sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson
add
	- `"i18n": true"`

- [ ] edit sources/europe/pl/polskae-mapanetBuildings.geojson
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/polskae-mapanetBuildings.geojson
add
	- `"i18n": true"`

**Comment by grischard** [comment]
Hello @maro-21, and welcome! I see this is your first issue; thank you for reporting this.

Would you like to try creating a pull request yourself to change these? Happy to assist if you need a hand.

**Comment by maro-21** [comment]
Second :)

Yes, please. But I don't use Linux now, so I don't think I can do it by myself.

**Comment by SomeoneElseOSM** [comment]
Does https://www.openstreetmap.org/user/SomeoneElse/diary/391681 help?  That's talking about a different repository, but it should explain how to do a textual change "just online". There are also git clients for Windows etc. Of course.

**Comment by andrewharvey** [comment]
Looks like this was closed by #1277
