### ISSUE TITLE
Strict check for files added in PR fails

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#757]
When commiting to gh-pages, the 'strict' check fails.

See https://travis-ci.org/osmlab/editor-layer-index/builds/629804044?utm_source=github_status&utm_medium=notification

CC @rbuffat

**Comment by grischard** [comment]
Maybe we need to check whether TRAVIS_PULL_REQUEST is set?

**Comment by rbuffat** [comment]
@grischard can you disable the strict test for now? I will have to look into it.

**Comment by grischard** [comment]
Yes, it's simply commented out in the makefile for now.

**Comment by grischard** [comment]
WIP in #762
