### ISSUE TITLE
Jupyter notebooks to facilitate creation of sources

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#799]
I'm not sure if this belongs here.

When creating new sources, I found two things a bit cumbersome:
* Creating the geometry for the source
* Creating the correct WMS urls.

I created two jupyter notebooks to support these tasks. 
They can be accessed with the following url: https://mybinder.org/v2/gh/rbuffat/eli-helper/master
The source code is here https://github.com/rbuffat/eli-helper

create_simplified_geometry.ipynb helps to create geometries by first getting boundaries using Nominatim queries. These administrative areas are then simplified using a very naive and inefficient algorithm generating boxes of equal size and only keeping the ones touching the administrative boundaries. 

create_wms_template.ipynb helps to create a template for wms sources.

Jupyter Notebooks offer not the most user-friendly interface, especially for people not familiar with Python. Nonetheless, it might save some time. 

If you like the notebooks I could create a PR to add them to eli.

**Comment by andrewharvey** [comment]
I'd be happy to see these tools added to CONTRIBUTING.md if you want to submit a PR.
