### ISSUE TITLE
But some layers have already been added

### ISSUE THREAD

**Issue by jidanni** [osmlab/editor-layer-index#812]
Clicking on the map produces:

> Available layers at this location:
> NLSC General Map with Contour line [iD] [JOSM]
> Taiwan e-Map Open Data [iD] [JOSM]
> Taiwan Land-Section Data [iD] [JOSM]
> Taiwan Village Boundaries [iD] [JOSM]

And clicking further gives "Add to iD" etc.

The problem is some of these layers have already been added to iD etc.
and proceeding to "Add to iD" would be a big waste of time for the user,
when the layer is already available there.

Therefore the two cases (already added, not yet added) should somehow be
shown by these link (color)s or whatever.

**Comment by grischard** [comment]
That sounds like an iD issue; I'd recommend opening an issue in their tracker.

**Comment by jidanni** [comment]
I'm saying that https://osmlab.github.io/editor-layer-index/ doesn't reflect the current state of JOSM or iD.
I'm saying that it assumes no layer has ever been added yet to those editors already.

**Comment by simonpoole** [comment]
And how do you suggest that it "knows" which layers are available in JOSM and iD? (its not an issue in Vespucci as you can simply update your complete configuration from ELI at any time).

**Comment by jidanni** [comment]
Maybe have a daily cronjob that gets the lists of those layers already in iD and JOSM, and then makes the found ones blue, and non-found ones red etc.

**Comment by grischard** [comment]
It's currently been the other way around - iD fetches the data from here every once in a while.

Our friends from JOSM track the differences at https://josm.openstreetmap.de/wiki/ImageryCompare - there are many!

**Comment by jidanni** [comment]
I see. So what possibly could be the use of the  "Add to iD"  links?
I mean I am glad I stumbled into them. I never knew one could control iD with just a URL like that,
and I then submitted https://github.com/openstreetmap/iD/issues/7426 .
But still, aren't they all "Added to iD" already?

**Comment by andrewharvey** [comment]
I originally added the Add to iD to workaround an issue where iD took up to a few months to update the layers so this was a shortcut, but regardless I still think it's a good feature so that regardless what iD decides to do you can always add ELI layers to it. Even more relevant now that iD isn't using ELI anymore.

**Comment by grischard** [comment]
We could call it 'show in iD'?

**Comment by andrewharvey** [comment]
> We could call it 'show in iD'?

If you want, but to me it means exactly the same as "Add to iD".
