### ISSUE TITLE
Get more Taiwan layers

### ISSUE THREAD

**Issue by jidanni** [osmlab/editor-layer-index#814]
Let's get more Taiwan government layers!

Let's review the situation to see if there things have changed since https://github.com/osmlab/editor-layer-index/pull/255.

The problem is I'm not a copyright expert. However @chihchun is!, so I hope he will compare

```
====== 臺灣通用電子地圖正射影像
授權方式 內政部國土測繪中心「國土測繪圖資服務雲」服務條款
授權說明網址 http://maps.nlsc.gov.tw//pro/use_clause.jsp
====== 臺灣通用電子地圖圖磚封裝檔
授權方式 1
授權說明網址 http://data.gov.tw/license
====== 臺灣通用電子地圖(不含等高線)
授權方式 內政部國土測繪中心「國土測繪圖資服務雲」服務條款
授權說明網址 http://maps.nlsc.gov.tw//pro/use_clause.jsp
====== 段籍圖
授權方式 1
====== 臺灣通用電子地圖(套疊等高線，比例尺小於一萬八千分之一)
授權方式 1
====== 臺灣通用電子地圖(不含等高線，比例尺小於一萬八千分之一)
授權方式 1
====== 臺灣通用電子地圖(套疊等高線)
授權方式 內政部國土測繪中心「國土測繪圖資服務雲」服務條款
授權說明網址 http://maps.nlsc.gov.tw//pro/use_clause.jsp
====== 五千分之一基本地形圖
授權方式 內政部國土測繪中心「國土測繪圖資服務雲」服務條款
授權說明網址 http://maps.nlsc.gov.tw//pro/use_clause.jsp
```
which is a list I made with shell script
```
set '
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=D9E44C4B-A5CD-4E44-BBF7-0C208513FA8E
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=05B8C6D1-B92F-41B6-85D6-CEF84BFD4D17
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=EAF031FB-8834-4947-91A0-4BDA69342785
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=A5CFF0A0-4DB1-4EFC-A533-5144708EF5C4
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=067C5474-539C-45D4-A743-55A7C6113511
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=75B4CCCB-0CDD-4104-A370-99CB2D3303BA
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=8001F4E6-7035-49E4-ADFC-DF43E755F824
https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=19D06D04-09FB-4CF5-BE78-07CE82E879EA
'
lynx -width=333 -nolist -dump $@ |
perl -nwle '
 s/.*首頁 >> 資料集清單 >>/====== / && print;
 /授權方式|授權說明網址/  && print;'
```
and see if any more layers can be added yet. Thanks!

**Comment by chihchun** [comment]
I'm not aware of the license change since then. I believe they are still [incompatible](https://github.com/osmlab/editor-layer-index/blob/gh-pages/FAQ.md#what-imagery-licenses-are-compatible-with-this-index) with the the index.

**Comment by grischard** [comment]
Thank you @chihchun!

**Comment by jidanni** [comment]
請 @audreyt  介入，協調內政部允許 OSM,
製圖時，能參考該航照層（臺灣通用電子地圖正射影像），因只有該航照層才是零無差，
方始 OSM 台灣圖正確無偏移。

**Comment by audreyt** [comment]
https://data.gov.tw/suggests is the main channel to make such a suggestion.
https://presidential-hackathon.taiwan.gov.tw/ProposalAgreement.aspx is another possible way to demonstrate social value that warrants a license change.

**Comment by jidanni** [comment]
OK! I submitted
1. https://data.gov.tw/node/119566
1. https://presidential-hackathon.taiwan.gov.tw/ProposalContentStr.aspx?ProposalID=44

**Comment by jidanni** [comment]
＠audreyt  https://data.gov.tw/node/119566 遭否定。

**Comment by jidanni** [comment]
@audreyt https://data.gov.tw/node/119566 遭否定。
