### ISSUE TITLE
Policy/practice on additional attributes?

### ISSUE THREAD

**Issue by systemed** [osmlab/editor-layer-index#84]
I'm interested in the idea of adding a simple geometry-extraction API to "rendered" layers, such as the US Forest Service one I've recently added.

This would work pretty simply:

1. User clicks location in editor
2. Editor requests http://osm.cycle.travel/extract-forest.geojson?lat=-107.255916&lon=37.725650
3. Server returns GeoJSON (or whatever) for all features at that location

It could also be of use for the TIGER 2014 tiles, CORINE, etc. etc., encouraging people to bring third-party content in manually rather than through a troublesome bulk import.

This would require one or potentially more new attributes in imagery sources - at the least, an API endpoint. Currently the list of attributes carried through to http://osmlab.github.io/editor-imagery-index/imagery.json (etc.) is limited and hardcoded.

What would be the preferred way of adding an additional attribute? Simply patching the build scripts, or...?

**Comment by pnorman** [comment]
Ping @systemed. Any plans on this?

**Comment by bhousel** [comment]
closing as stale.. I don't think there is any objection to adding additional attributes to this index.
