### ISSUE TITLE
Geoportal2 (primary aerial in Poland) is broken in parts of the country

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/editor-layer-index#845]
In iD it is showing as a blank white space. The same in JOSM and Vespucci.

JOSM lists also Geoportal WMTS that works fine.

https://github.com/osmlab/editor-layer-index/blob/d9ac23080bb038385279477f000c28a95e61be36/sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson

See also https://josm.openstreetmap.de/ticket/19656

EDIT: it actually is limited to Województwo Małopolskie....

https://www.openstreetmap.org/edit?editor=id#map=10/50.2714/20.9313

![screen06](https://user-images.githubusercontent.com/899988/89934461-e652e080-dc10-11ea-86c7-d0ae3554511e.png)

**Comment by matkoniecz** [comment]
As temporary fix it may be useful to set Bing as the best aerial in Poland to prevent malfunctioning aerial in iD.

**Comment by maro-21** [comment]
It's not broken, it works. I map almost every day and haven't seen any blank tiles.
They are black just before loading, but never seen white tiles.
In which region do you map?

**Comment by matkoniecz** [comment]
Kraków

**Comment by maro-21** [comment]
I've checked several major cities in Poland (Warszawa, Łódź, Wrocław, Poznań, Gdańsk, Bydgoszcz) and it works there. Looks like there is only some issue with Kraków.

Maybe you should set Bing as default imagery for Kraków for now.

**Comment by matkoniecz** [comment]
Have you checked Kraków? Because I would expect local simultaneous independent issues on all hardware/networks that I tested (not so many) rather than Kraków lag in Geoportal WMS

**Comment by matkoniecz** [comment]
Wait what. It is actually location-based with Kraków heavily impacted.

https://www.openstreetmap.org/edit?editor=id#map=17/50.63030/17.99701 https://www.openstreetmap.org/edit?editor=id#map=19/50.06186/19.94080

![screen04](https://user-images.githubusercontent.com/899988/89933680-b6570d80-dc0f-11ea-8574-093f4f87caec.png)
![screen05](https://user-images.githubusercontent.com/899988/89933691-b8b96780-dc0f-11ea-86ec-3f68316dcbb2.png)

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/edit?editor=id#map=10/50.2714/20.9313

![screen06](https://user-images.githubusercontent.com/899988/89934461-e652e080-dc10-11ea-86c7-d0ae3554511e.png)

**Comment by matkoniecz** [comment]
@maro-21  Again thanks for noticing - and see #893 (I self-reverted myself as something less brutal that disabling Geoportal as default everywhere in Poland)

**Comment by maro-21** [comment]
No problem.
Mateusz, could take a look at https://github.com/osmlab/editor-layer-index/issues/741 and make a pull request in free time? It's just a small change making imageries for Poland translatable.

**Comment by rbuffat** [comment]
Can we close this issue or is this still a problem?

**Comment by matkoniecz** [comment]
seems to be fixed
