### ISSUE TITLE
Portugal ortophotos in iD

### ISSUE THREAD

**Issue by AntMadeira** [osmlab/editor-layer-index#850]
Hi there.
I've noticed that JOSM uses Portuguese Ortophotos from 2015 and 2018.
I would like to know why it isn't implemented also in iD?

Regards.

**Comment by maro-21** [comment]
> I would like to know why it isn't implemented also in iD?

Because there hasn't been anyone to do it or the ortophotos aren't in WMS format.

**Comment by rbuffat** [comment]
JOSM includes an entry for a 2018 imagery using a wmts server: https://josm.openstreetmap.de/wiki/Maps/Portugal#OrtofotosDGT2018WMTS

The metadata can be found here:
https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/daf5479d-29c8-4e0c-b7b8-0e1791891186


> Legal restrictions:
>  Unrestricted public access Unrestricted viewing service. Data download on request. Whenever the user publishes and / or disseminates, by analogue or digital means, geographic information owned by the Directorate-General for the Territory, even if partially adapted, he should assign credits with the inclusion of the text "Geographic information provided by the Directorate-General for the Territory"

I'm not sure if this is a compatible license.

**Comment by AntMadeira** [comment]
The license is the same that was used for years in iD.
The Portuguese community sent the license for approval with Guillaume, from LWG, and it was approved.

So, is it possible to add these layers to iD?
https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/daf5479d-29c8-4e0c-b7b8-0e1791891186 [this one should substitute the non working [Ortofotos DGRF 2004-2006 (WMS)](https://github.com/osmlab/editor-layer-index/issues/1170)]
https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/b498e89c-1093-4793-ad22-63516062891b [this one should substitute the actual Carta de Uso do Solo 2010 (WMS)]

Regards.

**Comment by AntMadeira** [comment]
Please, remove one of these two layers (they are the same):
Maxar Premium Imagery (Beta)
Maxar Standard Imagery (Beta)

And two of these three (they're all the same):
OpenStreetMap (Basque Style)
OpenStreetMap (Breton Style)
OpenStreetMap (Occitan Style)


Finally, how can I translate the name strings of the new layers?
