### ISSUE TITLE
Tool to monitor layers

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#859]
Keeping track of layers is quite hard.

To solve this issue I created a prototype of a tool to check the sources if they are still alive. The status page can be found here https://rbuffat.github.io/eli_watchdog. The source code here: https://github.com/rbuffat/eli_watchdog.

The aim is, that a cron job executes the script every day. The script tests for the existence of the license and privacy URLs as well as the imagery. Not all imagery types are yet tested correctly.  Also, everything is quite rough, as I first just wanted to test the feasibility of it.

**Comment by grischard** [comment]
That's quite cool! The JOSM people have a similar test at https://josm.openstreetmap.de/jenkins/ (somewhere, I don't know where), and I was thinking we should just use that.

Are you on irc/Telegram/Slack/Riot/Element/any kind of chat?

**Comment by rbuffat** [comment]
I sent you an email using the osm wiki. Not sure if this works. 

I did not know that JOSM has similar tests.  Could be https://josm.openstreetmap.de/jenkins/job/JOSM-Imagery-Integration/lastCompletedBuild/testReport/

If it turns out the tests I implemented do work and are useful, they could maybe be integrated into the strict checks for PRs.

**Comment by rbuffat** [comment]
The strict check now includes most of the tests of the watchdog. https://rbuffat.github.io/eli_watchdog is still running. The number of broken sources went down from ~120 to <50 at the moment.
