### ISSUE TITLE
Travis @traviscibot deploy undoes recent commits 

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#894]
As reported by @Klumbumbus in https://github.com/osmlab/editor-layer-index/pull/866, the travisbot undoes commits when a job on travis is canceled. 
It happened again in https://github.com/osmlab/editor-layer-index/commit/a54c7570b4708c0572eea377c399fca72182e9b2

@grischard could you switch off auto cancellation in travis?
https://docs.travis-ci.com/user/customizing-the-build/#building-only-the-latest-commit

**Until this is configured, it is important that only one PR at a time is merged, each after all jobs on https://travis-ci.org/github/osmlab/editor-layer-index/builds have finished.** 

For long-term it would be good to separate the deploy branch:  e.g. having a trunk/main/sources branch, where stuff is committed to, and gh-pages, where it is deployed to.

**Comment by andrewharvey** [comment]
yikes, this happen before too.

I'm all for having a separate deployment branch. In my view dist files shouldn't be committed, at least not in the same branch as development work happens.

There was some work before to stop using the gh-pages branch, I'd be happy to see us move to master/main branch as the default for sources and then a dist branch for publishing the outputs.

**Comment by rbuffat** [comment]
> There was some work before to stop using the gh-pages branch, I'd be happy to see us move to master/main branch as the default for sources and then a dist branch for publishing the outputs.

This is probably quite a complex task.  This is a tool that might be helpful: https://github.com/sgillies/mainer But I never used it before, thus I don't know how good it works.

**Comment by grischard** [comment]
Editors used to have the gh-pages branch url hardcoded, so that was a no-no. Now that the most recent versions of everything but iD have switched…

**Comment by grischard** [comment]
It looks like I don't have the permissions to change the travis settings.

**Comment by simonpoole** [comment]
The actual proper solution is to create a release automatically, using a branch is just kicking the can a bit down the road. Apps can easily retrieve the latest release (see for example https://github.com/simonpoole/beautified-JOSM-preset/releases where I generate a github release from the build script, and, for example, https://github.com/simonpoole/beautified-JOSM-preset/releases/latest/download/vespucci_icons.zip gets the latest release of that specific file).

The main reason why this hasn't happened here is that the output file location tends to be hardwired in numerous places, so a move to a different solution requires some kind of transition solution.

a) deciding how often or / and on what kind of event a new release is authored and the versioning convention

b) providing updated files at the historic locations during transition (a year or so).

If a) is done manually then the build script could continue to generate the in repo output files for a while, if the release is generated by the CI system, then the files would have to manually be copied to the repo now and then, but given that is a transition hack, that could be semi automatically one per week or so.

**Comment by rbuffat** [comment]
I would argue the most crucial part is that there is a stable location as well as format. E.g. there is a schema available for each file considered to be part of the public API. If the schema changes, files for the old and the new schema are still generated for a transition period. Currently, this is not given. 

E.g. 
Now we would generate with each deployment:
https://osmlab.github.io/editor-layer-index/imagery_v1.geojson
https://osmlab.github.io/editor-layer-index/schemas/schema_v1.geojson

If there are changes to the schema we would deploy all currently supported versions (for a transition period or as long as it is possible):
https://osmlab.github.io/editor-layer-index/imagery_v1.geojson
https://osmlab.github.io/editor-layer-index/schemas/schema_v1.geojson
https://osmlab.github.io/editor-layer-index/imagery_v2.geojson
https://osmlab.github.io/editor-layer-index/schemas/schema_v2.geojson

**Comment by rbuffat** [comment]
> It looks like I don't have the permissions to change the travis settings.

Do you know how has permission to travis? Otherwise, I could implement a github action to replace travis. I assume here that travis needs a github API key that can be revoked.

**Comment by andrewharvey** [comment]
@bhousel do you hold any of the permissions for this repo or travis? If you do is it possible to enable either myself or @grischard permissions to manage travis? In the short term per https://github.com/osmlab/editor-layer-index/issues/894#issue-683407001 we are looking to turn off auto-cancellation in travis, to stop travis reverting merged PRs.

**Comment by rbuffat** [comment]
Travis was replaced and the new deploy actions only updates imagery* files and i18/en.yml, thus this issue should not happen anymore.
