### ISSUE TITLE
User-Agent encoded in URL

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#905]
A few sources encode "User-Agent" in source['properties']['url']:
https://github.com/osmlab/editor-layer-index/search?q=User-Agent&unscoped_q=User-Agent

Is this something that is expected. If not, should the tests be adapted to check for this?

**Comment by simonpoole** [comment]
Seems to be a, slightly crazy, JOSMism. It simply defines a header to be set/added on the request for the image.

BUT this should simply be an additional field in the configuration (and that goes for JOSM too).

In ELI this should be added to custom-http-headers though I suspect this might not be necessary for other clients.

**Comment by rbuffat** [comment]
The schema specifies custom-http-headers as follows. I'm not an expert with JSON schema, but would this not only allow to specify only one custom HTTP header?
```
"custom-http-headers": {
    "description": "HTTP headers to be sent to server. It has two attributes header-name and header-value. May be specified multiple times.",
    "type": "object",
    "properties": {
        "header-name": {
            "type": "string"
        },
        "header-value": {
            "type": "string"
        }
    },
    "additionalProperties": false
},
```

This should allow to specify multiple headers:
```
    "custom-http-headers": {
        "type": "array",
        "items": {
            "description": "HTTP headers to be sent to server. It has two attributes header-name and header-value. May be specified multiple times.",
            "type": "object",
            "properties": {
                "header-name": {
                    "type": "string"
                },
                "header-value": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }
    }
```

**Comment by grischard** [comment]
Or since it's a JOSMim and likely won't be necessary for ELI consumers, we can drop it in the URL.

**Comment by Klumbumbus** [comment]
It doesn't need to be in the URL for JOSM as well afaik. JOSM has the `custom-http-headers` property for this.

**Comment by rbuffat** [comment]
@grischard They can easily be moved to `custom-http-headers`, but could you look at the schema for it? 

https://github.com/osmlab/editor-layer-index/blob/cbf072b61508bddbe2a6dcbf617ed699defe0a40/schema.json#L210

Let's imagine a source needs two custom HTTP headers, e.g. a `X-WAAPI-TOKEN` and a `User-Agent` header. According to the current schema, I think these headers need to be specified as follows (please correct me if I'm wrong, I'm not that used to JSON schema):
```
{
    "type": "Feature",
    "properties": {
       ...,
        "custom-http-headers": {
            "header-name": "X-WAAPI-TOKEN",
            "header-value": "sometoken"
        },
        "custom-http-headers": {
            "header-name": "User-Agent",
            "header-value": "Some user agent string"
        },
        ...
   }
}
```

In this example, the key "custom-http-headers" occurs multiple times. The schema descriptions mentions `May be specified multiple times.`, but while this may or may not be valid according to the JSON specification, this can lead to issues with JSON implementations. In Python for this example, one of they keys will override the other in the dict representing the json data. There is a discussion on StackOverflow on this topic:  https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object

**Comment by Klumbumbus** [comment]
User-Agents included directly in the URL were removed in JOSM in https://josm.openstreetmap.de/wiki/Maps/Poland?action=diff&version=175

**Comment by rbuffat** [comment]
@Klumbumbus Thanks for notifying. https://github.com/osmlab/editor-layer-index/pull/943 is still open. I'm a bit hesitant to progress this PR, as I think maybe it would be better to fix ELI's schema first. I haven't seen a source that has multiple http-headers yet, but this doesn't mean that there will be any at one time.

Also while we discussing it, for headers like "User-Agent,Mozilla/5.0 (JOSM)", would it be good to have a token that is replaced by the actual osm editor, or would it be better to use a cross-editor string. I suppose normally the relevant part is the  "Mozilla/5.0" and not what is next.

**Comment by Klumbumbus** [comment]
>Also while we discussing it, for headers like "User-Agent,Mozilla/5.0 (JOSM)", would it be good to have a token that is replaced by the actual osm editor, or would it be better to use a cross-editor string. I suppose normally the relevant part is the "Mozilla/5.0" and not what is next.

For ELI I think it makes more sense to remove the "(JOSM)" in the user agent, because ELI is mainly used by iD.
(In general for iD it is probably not even needed. In JOSM it was introduced because there are some imagery servers which simply block all Java applications.)

**Comment by rbuffat** [comment]
That's true, for all web-based editors the user-agent HTTP header is not needed. However, it would be good as an imagery index to think about all possible editors and not just one (regardless if only one is actually using the index).

**Comment by grischard** [comment]
Before moving forward with this and adding another complexity, there should be a use case of editors that will want to use this property. I suggest talking to maintainers first.

**Comment by bhousel** [comment]
Browser based editors like iD and RapiD will not be able to control the user agent or referrer or any other request headers.

This comes up for discussion sometimes:  https://github.com/openstreetmap/iD/issues/3420

**Comment by rbuffat** [comment]
> Before moving forward with this and adding another complexity, there should be a use case of editors that will want to use this property. I suggest talking to maintainers first.

@grischard I assume you mean the `custom-http-headers` property. It is already in the schema and thus in the public "API" of ELI. Although as highlighted in https://github.com/osmlab/editor-layer-index/issues/905#issuecomment-706306607 I think the schema should be fixed, as it promises something that it cannot hold (Either the schema itself should be changed or the description that says that multiple `custom-http-headers` can be added).

Looking at it from the other way, there are currently 3 sources with  `custom-http-headers`: https://github.com/osmlab/editor-layer-index/search?q=custom-http-headers 
Two sources have a `User-Agent` HTTP header, [one source](https://github.com/osmlab/editor-layer-index/blob/6961ad4c1da7ec147e2d0a6c94d18ac9b1ee3256/sources/europe/no/NorwayOrthophoto(historic).geojson) includes an `X-WAAPI-TOKEN` token (it is a wms_endpoint source). I use this token in https://rbuffat.github.io/eli_watchdog as it is required to test if the server is alive.

So I think there is a demand for having a `custom-http-headers` property. Each editor can choose how he wants to use it. E.g. filter sources requiring an incompatible HTTP header or just ignore the poperty.

**Comment by rbuffat** [comment]
No source contains the HTTP headers in the URL anymore. However, at some point, the schema should be changed as it is not impossible that a source could require more than one HTTP header to be set.
