### ISSUE TITLE
Please update eox.at layer to 2019 version

### ISSUE THREAD

**Issue by jetta20162** [osmlab/editor-layer-index#907]
There is a new version for eox.at layer:

https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2019_3857/default/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.jpg
https://tiles.maps.eox.at/wmts/1.0.0/WMTSCapabilities.xml

Would be cool to update the old 2018 layer or add it as a new option

**Comment by rbuffat** [comment]
@jetta20162 It looks as it was given explicit permission for the existing eox.at data:

> We, EOX IT Services GmbH, explicitly allow use of both Sentinel-2 cloudless 2018 and Sentinel-2 cloudless 2016 layers as background imagery for the purpose of manually deriving geometries to be included in OpenStreetMap in non-commercial OpenStreetMap editing applications. Attribution as described at https://s2maps.eu/#license must be provided in a suitable OpenStreetMap changeset tag. EOX IT Services GmbH offers the layers as-is and as-available and makes no warranties of any kind concerning source or derived data. EOX IT Services GmbH does not claim any rights in data created under this provision.

https://wiki.openstreetmap.org/wiki/Eox.at

Thus before other datasets from eox.at can be added somebody needs to contact them first for permission.

CC @simonpoole

**Comment by cicku** [comment]
Solved in #1998
