### ISSUE TITLE
Travis sunsetting?

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#981]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

We will get 1000 free minutes before we have to do something.

**Comment by andrewharvey** [comment]
Maybe now we'll be able to merge two PRs at the same time without Travis reverting the changes made in the first one... :wink: 

On a more serious note, maybe we can move to GitHub Actions? I'm most familiar with GitLab CI/CD, but understand GitHub Actions should work.

**Comment by rbuffat** [comment]
If the minutes renew every month then I suppose this should not be a problem If it's a one-time credit, then we should switch. 

I tried to implement gihub actions https://github.com/osmlab/editor-layer-index/compare/gh-pages...rbuffat:gh-pages?expand=1 but I need to test it a bit more, especially the part where only the changed files are passed to the strict checks.

The deploy/overwrite issue probably can only be solved if we switch to a "main" branch, and then deploy everything to gh-pages.

**Comment by grischard** [comment]
https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

Looks like once the 1000 minutes are gone, that's it.

I think our efforts would be better invested if we could take what's good about ELI - the great tools René has written, the repository of permissions - and port them over to run on the JOSM index.

**Comment by simonpoole** [comment]
IMHO the OSMF should not be relying on "give aways" for key services, in particular such for which we know that they don't and can't make long term sense for the companies offering them (aka this comment is just as applicable to github actions). Either we subscribe to a service (naturally at a good rate) or we run it ourselves.

**Comment by simonpoole** [comment]
> I think our efforts would be better invested if we could take what's good about ELI - the great tools René has written, the repository of permissions - and port them over to run on the JOSM index.

As long as the issue with the WMS servers isn't resolved, which is naturally an even larger problem for iD (which currently doesn't support WMS server endpoints at all, but if it did, the loss of meta information would be the same no-go), it just doesn't make any sense.  

To reiterate this is not a technical issue, but one of policy, at least anything with the best flag in ELI should not be de-duped in JOSM as a bare minimum.

**Comment by grischard** [comment]
iD supports WMS in the "usual" projections.

How many layers are `best` in ELI but tucked inside a `wms_endpoint` in JOSM?

**Comment by Klumbumbus** [comment]
> How many layers are best in ELI but tucked inside a wms_endpoint in JOSM?

None. All best marked layers are in JOSM too. The only difference is with one layer regarding tms vs. wms:

```
wms is marked best. tms is in ELI separate but not marked best. tms is in mirror of best marked wms in JOSM
Ignore | * Quality differs (null != eli-best): [EE] Estonia Ortho (Maaamet) [Maaamet-Estonia_Ortho_mirror2]
```

In general there are very few layers which are in ELI but not in JOSM where JOSM has the wms_endpoint. Here is the list:

```
Ignore | -  [LU] Basemap geoportail.lu [lu.geoportail.opendata.basemap]
Ignore | -  [LU] Cadastre geoportail.lu [lu.geoportail.opendata.cadastre]
Ignore | -  [LU] Ortho 2018 geoportail.lu [lu.geoportail.opendata.ortho2018]
Ignore | -  [LU] Ortho 2017 geoportail.lu [lu.geoportail.opendata.ortho2017]
Ignore | -  [LU] Topographical Map geoportail.lu [lu.geoportail.opendata.topo]
Ignore | -  [AT] VoGIS: DGM (Terrain model) [vogis.cnv.at-DGM]
Ignore | -  [AT] VoGIS: DOM (Surface model) [vogis.cnv.at-DOM]
Ignore | -  OSM Inspector: Addresses [OSM_Inspector-Addresses]
Ignore | -  OSM Inspector: Area [OSM_Inspector-Multipolygon]
Ignore | -  OSM Inspector: Geometry [OSM_Inspector-Geometry]
Ignore | -  OSM Inspector: Highways [OSM_Inspector-Highways]
Ignore | -  OSM Inspector: Places [OSM_Inspector-Places]
Ignore | -  OSM Inspector: Routing [OSM_Inspector-Routing]
Ignore | -  OSM Inspector: Tagging [OSM_Inspector-Tagging]
Ignore | -  [NO] Kartverket Hiking Trails [kartverket-friluft]
```
And for example regarding geoportail.lu JOSM has the probably most important one from the wms_endpoint, the latest Ortho as own tms layer (like ELI).

**Comment by simonpoole** [comment]
My point with "best" was that it is a requirement, not that it is currently violated (one of the problems is in a hypothetical demise of ELI is how you are even going to notice). Likely it should be reformulated as in "any per layer metadata that can't be provided on an wms_endpoint entry". @grischard the point is that iD doesn't support wms_endpoints, not that it doesn't support wms servers per se.

The layers for which I first noticed the issue are the OSM Inspector layers, which are extremely unwieldy to access via the WMS server endpoint.

**Comment by grischard** [comment]
https://travis-ci.community/t/extremely-poor-official-communication-of-the-org-shutdown/10568 👎 

@rbuffat what do your tools say if you run them on https://josm.openstreetmap.de/maps?format=geojson ?

**Comment by rbuffat** [comment]
@grischard I can't really say. 

- For https://rbuffat.github.io/eli_watchdog using different input data would probably not be that difficult, as long as the data model is similar. However, I'm not sure if there will be anyone that wants to use it, as there seem to be already some Jenkins tests.
- I suppose there is no use for the strict tests, as JOSM philosophy seems to be to not require quality checks in advance and fix errors later.
- The WMS sync bot could also probably be quite easily adapted to another input source. However, I don't know if the JOSM index could be updated programmatically. Also, in my opinion, such automatic change should always go through a human review process, which is really easy to integrate with GitHub. I don't know how easy this would be for JOSM and without this the bot is useless. Also, it seems as the JOSM index did not replicate the WMS related updates, which could indicate that these changes are not wanted.

**Comment by grischard** [comment]
* it should be exactly the same data model. Maybe the whitespace is slightly different, but probably not even that much. Different editors just switched their source URLs.

* some checks get done when you submit a wiki change, others later. I'm sure some checks could be integrated into the JOSM trac plugin code, which is already python. Maybe I can share that python code with you if that's cool with @don-vip?

* It might just be lack of time from @Klumbumbus. I think the work you've done on projections is excellent, and the part to exclude supported projections that are used in another area is both clever and elegant. I'm not sure how automatic edits to the trac wiki would work.

**Comment by rbuffat** [comment]
> * some checks get done when you submit a wiki change, others later. I'm sure some checks could be integrated into the JOSM trac plugin code, which is already python. Maybe I can share that python code with you if that's cool with @don-vip?

Sure. I assume they will not be useful "out-of-the-box", but I guess they can be used as inspiration.  I guess the scripts of ELI are subject to the following license: https://github.com/osmlab/editor-layer-index/blob/gh-pages/scripts/LICENSE

**Comment by rbuffat** [comment]
Travis is now replaced with a github action.
