### ISSUE TITLE
South-america / Brazil / BC250

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#983]
Currently, all south-america / Brazil / BC250 layers are broken (Layer names CCAR:BC250_* have changed to CCAR:BC250_2017_*). 

The WMS server is linked (but with the old URLs) from https://dados.gov.br: E.g. https://dados.gov.br/dataset/ccar_bc250_trecho_drenagem_l

In the left column it says: 

>License not specified

but on the bottom it says 

>All content licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License

Some of them seem to have been added in https://github.com/osmlab/editor-layer-index/pull/318

@naoliv @Skippern @tyrasd I did not yet find a waiver yet. Does somebody know more about these sources?

**Comment by eduardoaddad** [comment]
https://dados.gov.br/pagina/dados-abertos

The site license is under open data

Open data corresponds to the idea that certain data must be available for everyone to use and publish, without restrictions on copyrights and patents or other control mechanisms.

**Comment by naoliv** [comment]
https://dados.gov.br/pagina/dados-abertos explains what is open data, but it doesn't specify a license for each available data.

Also note that they point to https://opendefinition.org/licenses/, with licenses considered open; some are not compatible with OpenStreetMap, even though they consider it open.

In the footer of the entire https://dados.gov.br/ site, for example, it says that `All content is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.`

https://dados.gov.br/dataset/ccar_bc250_trecho_drenagem_l for example, has "License not specified" in the `License` part.

It is incorrect to assume that "open data" is equivalent to a permissive license for OpenStreetMap.

**Comment by rbuffat** [comment]
@naoliv What is your opinion about this data? 

There seems to be new 2019 BC250 data available. If the data is considered compatible with OSM we should update the sources or otherwise we should remove them. 

There seems to be different mentions of IBGE in the osm wiki:

> License to use the data: Data produced by IBGE are considered to be "Public Domain", can be used in OSM, subject to the requirement to cite the source as "IBGE"; as registered in Brazilian data sources , CNEFE_data, _IBGE, _Brasil_import # Legality and Imports mailing list
> https://wiki.openstreetmap.org/wiki/Pt:IBGE_Import#Como_importar_os_dados

> IBGE has not provided a clear license statement, but informal communications have been recorded showing that IBGE's data is indeed considered "public domain" [1] [2] [3].
> https://wiki.openstreetmap.org/wiki/CNEFE_data,_IBGE,_Brasil_import#Legality

>  IBGE: Data produced by IBGE and made available on the ibge.gov.br Portal are considered "Public Domain", can be used in the OSM, subject to the requirement to cite the source as "IBGE"; for more information, see IBGE's official communication at Talk-br 2013-7-1 ; also CNEFE_data, _IBGE, _Brasil_import # Legality and Imports mailing list
> https://wiki.openstreetmap.org/wiki/Pt:Brazilian_data_sources
>

**Comment by matheusgomesms** [comment]
I fixed (or tried to fix) all broken layers coming directly from IBGE servers on PR #1249.

Regarding IBGE license, I wouldn't be very concerned about it. As René mentioned on last message, [there is understanding that](https://lists.openstreetmap.org/pipermail/imports/2013-July/001981.html) (and based on e-mails from IBGE explicitely allowing usage) that all IBGE data is available to use on OSM.

On [Brazilian Open Data website](https://dados.gov.br/organization/instituto-brasileiro-de-geografia-e-estatistica-ibge), to be fair most of IBGE data doesn't specify any license.

Additionally, on [IBGE website](https://www.ibge.gov.br/acesso-informacao/dados-abertos.html) there are a couple of plans to move towards Open Data. Also, [Article 4 of Decree Law 8777/2016](http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/d8777.htm) states that "The data provided by the federal government and the active transparency information are free to use by public authorities and society."

The same law uses this definition of Open Data (Article 2): "data accessible to the public, represented in digital media, structured in an open format, processable by machine, referenced on the internet and made available under an open license that allows its free use, consumption or crossing, limited to crediting the authorship or source". So I believe that we are good if we properly give attribution to IBGE as author.

Finally, a very large portion of the Brazilian data on OSM comes from IBGE. If we are not allowed to use IBGE data, then I would be very worried about OSM in Brazil.
