### ISSUE TITLE
Tool to check min_zoom attribute

### ISSUE THREAD

**Issue by rbuffat** [osmlab/editor-layer-index#998]
Long-term, it would be nice to have a check for the quality of the min-zoom attribute. But I'm not sure if it is possible to find a universal working algorithm for that. 

For the short-term, I created a simple tool that displays an image for the same location for all zoom levels between 0 and 20: 
https://mybinder.org/v2/gh/rbuffat/eli-helper/master?urlpath=apps%2F/check_minzoom.ipynb (The first start can be quite slow when the image needs to be built)

The zoom level set in the source is marked with ELI, the zoom level determined by a (not yet always working) heuristic is marked with <==. Below the image, the image hash, as well as the number of pixels not having the same color as the maximum occurring color, are displayed. Currently, the tool only supports tms and wms sources.

**Comment by don-vip** [comment]
It seems ELI now checks min-zoom as we suddenly get hundreds of differences. Didn't check them all but there is at least one problem:
`* Minzoom differs (6 != null): [NZ] LINZ NZ Topo50 Gridless Maps [LINZ_NZ_Topo50_Gridless_Maps]`
https://tiles-a.data-cdn.linz.govt.nz/services;key=56742d94dd12449bb5d9ea994389aa6f/tiles/v4/layer=2343/EPSG:3857/0/0/0.png
![image](https://user-images.githubusercontent.com/596867/108602166-de82ae80-73a0-11eb-95b0-6612b7dfccce.png)

**Comment by rbuffat** [comment]
@don-vip  The link above shows for me just a white image. Also, the URL seems to be different: https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/oceania/nz/LINZ-NZ-Topo50-Gridless-Maps.geojson

The `No data` could imply some network error, I need to look into this.

![LINZ-NZ-Topo50-Gridless-Maps](https://user-images.githubusercontent.com/259530/108607682-12220080-73c2-11eb-9ad2-698d3ce9bf85.png)

![Screenshot_20210220_212222](https://user-images.githubusercontent.com/259530/108607627-c5d6c080-73c1-11eb-9d80-67601bb98888.png)


I did not really find a consistent use of min_zoom in JOSM or ELI. If you set a min-zoom, what are the criteria that you apply?

Imho, in "the real world" I don't think there is a big impact if the geometry of a source covers 1, 2, or 5 pixels of a min_zoom tile. For most cases, I chose the first tile the [average image hash](http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html) was not all the same. This does not guarantee that there is absolutely no pixel shown at a higher zoom level, but the probability that this pixel is usable for anything is 0.

**Comment by don-vip** [comment]
> I did not really find a consistent use of min_zoom in JOSM or ELI. If you set a min-zoom, what are the criteria that you apply?

I only check we receive an image at specified zoom in a reasonable time. Sometimes I had to increase the min-zoom from 0/1 to an higher value because on some servers, requesting a low zoom took a lot of time (up to dozens of seconds or several minutes) to answer.
